// Generated by sart-facadegen. Do not edit by hand —
// regenerate via `sbt sartFacadesRegen` (see facadegen.conf).
package flutter.services

import sart.dart.*

// ─── autofill.dart ────────────────────────────────────────

@native
@DartImport("package:flutter/services.dart")
abstract class AutofillHints extends DartObject

@native
@DartImport("package:flutter/services.dart")
object AutofillHints:
  def addressCity: String = native.value
  def addressCityAndState: String = native.value
  def addressState: String = native.value
  def birthday: String = native.value
  def birthdayDay: String = native.value
  def birthdayMonth: String = native.value
  def birthdayYear: String = native.value
  def countryCode: String = native.value
  def countryName: String = native.value
  def creditCardExpirationDate: String = native.value
  def creditCardExpirationDay: String = native.value
  def creditCardExpirationMonth: String = native.value
  def creditCardExpirationYear: String = native.value
  def creditCardFamilyName: String = native.value
  def creditCardGivenName: String = native.value
  def creditCardMiddleName: String = native.value
  def creditCardName: String = native.value
  def creditCardNumber: String = native.value
  def creditCardSecurityCode: String = native.value
  def creditCardType: String = native.value
  def email: String = native.value
  def familyName: String = native.value
  def fullStreetAddress: String = native.value
  def gender: String = native.value
  def givenName: String = native.value
  def impp: String = native.value
  def jobTitle: String = native.value
  def language: String = native.value
  def location: String = native.value
  def middleInitial: String = native.value
  def middleName: String = native.value
  def name: String = native.value
  def namePrefix: String = native.value
  def nameSuffix: String = native.value
  def newPassword: String = native.value
  def newUsername: String = native.value
  def nickname: String = native.value
  def oneTimeCode: String = native.value
  def organizationName: String = native.value
  def password: String = native.value
  def photo: String = native.value
  def postalAddress: String = native.value
  def postalAddressExtended: String = native.value
  def postalAddressExtendedPostalCode: String = native.value
  def postalCode: String = native.value
  def streetAddressLevel1: String = native.value
  def streetAddressLevel2: String = native.value
  def streetAddressLevel3: String = native.value
  def streetAddressLevel4: String = native.value
  def streetAddressLine1: String = native.value
  def streetAddressLine2: String = native.value
  def streetAddressLine3: String = native.value
  def sublocality: String = native.value
  def telephoneNumber: String = native.value
  def telephoneNumberAreaCode: String = native.value
  def telephoneNumberCountryCode: String = native.value
  def telephoneNumberDevice: String = native.value
  def telephoneNumberExtension: String = native.value
  def telephoneNumberLocal: String = native.value
  def telephoneNumberLocalPrefix: String = native.value
  def telephoneNumberLocalSuffix: String = native.value
  def telephoneNumberNational: String = native.value
  def transactionAmount: String = native.value
  def transactionCurrency: String = native.value
  def url: String = native.value
  def username: String = native.value

// ─── text_input.dart ────────────────────────────────────────

@native
@DartImport("package:flutter/services.dart")
class TextInputType extends DartObject:
  def index: Int = native.value
  def signed: Boolean = native.value
  def decimal: Boolean = native.value
  def toJson(): Map[String, Any] = native.value

@native
@DartImport("package:flutter/services.dart")
object TextInputType:
  def text: TextInputType = native.value
  def multiline: TextInputType = native.value
  def number: TextInputType = native.value
  def phone: TextInputType = native.value
  def datetime: TextInputType = native.value
  def emailAddress: TextInputType = native.value
  def url: TextInputType = native.value
  def visiblePassword: TextInputType = native.value
  def name: TextInputType = native.value
  def streetAddress: TextInputType = native.value
  def none: TextInputType = native.value
  def webSearch: TextInputType = native.value
  def twitter: TextInputType = native.value
  def values: List[TextInputType] = native.value
  def numberWithOptions(signed: Boolean = native.value, decimal: Boolean = native.value): TextInputType = native.value

@native
@DartImport("package:flutter/services.dart")
class TextInput extends DartObject:
  def scribbleInProgress: Boolean = native.value

@native
@DartImport("package:flutter/services.dart")
object TextInput:
  def scribbleClients: Map[String, DartObject] = native.value
  def setChannel(newChannel: DartObject): Unit = native.value
  def setInputControl(newControl: DartObject): Unit = native.value
  def restorePlatformInputControl(): Unit = native.value
  def ensureInitialized(): Unit = native.value
  def attach(client: DartObject, configuration: DartObject): DartObject = native.value
  def updateEditingValue(value: DartObject): Unit = native.value
  def finishAutofillContext(shouldSave: Boolean = native.value): Unit = native.value
  def registerScribbleElement(elementIdentifier: String, scribbleClient: DartObject): Unit = native.value
  def unregisterScribbleElement(elementIdentifier: String): Unit = native.value

@native
@DartImport("package:flutter/services.dart")
class TextInputAction extends DartObject

@native
@DartImport("package:flutter/services.dart")
object TextInputAction:
  val none: TextInputAction = native.value
  val unspecified: TextInputAction = native.value
  val done: TextInputAction = native.value
  val go: TextInputAction = native.value
  val search: TextInputAction = native.value
  val send: TextInputAction = native.value
  val next: TextInputAction = native.value
  val previous: TextInputAction = native.value
  val continueAction: TextInputAction = native.value
  val join: TextInputAction = native.value
  val route: TextInputAction = native.value
  val emergencyCall: TextInputAction = native.value
  val newline: TextInputAction = native.value

// ─── mouse_cursor.dart ────────────────────────────────────────

@native
@DartImport("package:flutter/services.dart")
abstract class SystemMouseCursors extends DartObject

@native
@DartImport("package:flutter/services.dart")
object SystemMouseCursors:
  def none: DartObject = native.value
  def basic: DartObject = native.value
  def click: DartObject = native.value
  def forbidden: DartObject = native.value
  def progress: DartObject = native.value
  def contextMenu: DartObject = native.value
  def help: DartObject = native.value
  def text: DartObject = native.value
  def verticalText: DartObject = native.value
  def cell: DartObject = native.value
  def precise: DartObject = native.value
  def move: DartObject = native.value
  def grab: DartObject = native.value
  def grabbing: DartObject = native.value
  def noDrop: DartObject = native.value
  def alias: DartObject = native.value
  def copy: DartObject = native.value
  def disappearing: DartObject = native.value
  def allScroll: DartObject = native.value
  def resizeLeftRight: DartObject = native.value
  def resizeUpDown: DartObject = native.value
  def resizeUpLeftDownRight: DartObject = native.value
  def resizeUpRightDownLeft: DartObject = native.value
  def resizeUp: DartObject = native.value
  def resizeDown: DartObject = native.value
  def resizeLeft: DartObject = native.value
  def resizeRight: DartObject = native.value
  def resizeUpLeft: DartObject = native.value
  def resizeUpRight: DartObject = native.value
  def resizeDownLeft: DartObject = native.value
  def resizeDownRight: DartObject = native.value
  def resizeColumn: DartObject = native.value
  def resizeRow: DartObject = native.value
  def zoomIn: DartObject = native.value
  def zoomOut: DartObject = native.value

// ─── text_formatter.dart ────────────────────────────────────────

@native
@DartImport("package:flutter/services.dart")
abstract class TextInputFormatter extends DartObject:
  def formatEditUpdate(oldValue: DartObject, newValue: DartObject): DartObject = native.value

@native
@DartImport("package:flutter/services.dart")
object TextInputFormatter:
  def withFunction(formatFunction: (DartObject, DartObject) => DartObject): TextInputFormatter = native.value

// ─── text_editing.dart ────────────────────────────────────────

@native
@DartImport("package:flutter/services.dart")
class TextSelection(
  val baseOffset: Int,
  val extentOffset: Int,
  val affinity: DartObject = native.value,
  val isDirectional: Boolean = native.value
) extends DartObject:
  def base: DartObject = native.value
  def extent: DartObject = native.value
  def copyWith(baseOffset: Int = native.value, extentOffset: Int = native.value, affinity: DartObject = native.value, isDirectional: Boolean = native.value): TextSelection = native.value
  def expandTo(position: DartObject, extentAtIndex: Boolean = native.value): TextSelection = native.value
  def extendTo(position: DartObject): TextSelection = native.value

@native
@DartImport("package:flutter/services.dart")
object TextSelection:
  def collapsed(offset: Int, affinity: DartObject = native.value): TextSelection = native.value
  def fromPosition(position: DartObject): TextSelection = native.value

// ─── hardware_keyboard.dart ────────────────────────────────────────

@native
@DartImport("package:flutter/services.dart")
abstract class KeyEvent(
  val physicalKey: DartObject,
  val logicalKey: LogicalKeyboardKey,
  val character: String = native.value,
  val timeStamp: sart.stdlib.Duration,
  val deviceType: DartObject = native.value,
  val synthesized: Boolean = native.value
) extends DartObject:
  def debugFillProperties(properties: DartObject): Unit = native.value

@native
@DartImport("package:flutter/services.dart")
class KeyDownEvent(
  val physicalKey: DartObject,
  val logicalKey: LogicalKeyboardKey,
  val character: String = native.value,
  val timeStamp: sart.stdlib.Duration,
  val synthesized: Boolean = native.value,
  val deviceType: DartObject = native.value
) extends DartObject

@native
@DartImport("package:flutter/services.dart")
class KeyRepeatEvent(
  val physicalKey: DartObject,
  val logicalKey: LogicalKeyboardKey,
  val character: String = native.value,
  val timeStamp: sart.stdlib.Duration,
  val deviceType: DartObject = native.value
) extends DartObject

// ─── keyboard_key.g.dart ────────────────────────────────────────

@native
@DartImport("package:flutter/services.dart")
class LogicalKeyboardKey(
  val keyId: Int
) extends DartObject:
  def keyLabel: String = native.value
  def debugName: String = native.value
  def isAutogenerated: Boolean = native.value
  def synonyms: Set[LogicalKeyboardKey] = native.value
  def debugFillProperties(properties: DartObject): Unit = native.value

@native
@DartImport("package:flutter/services.dart")
object LogicalKeyboardKey:
  def valueMask: Int = native.value
  def planeMask: Int = native.value
  def unicodePlane: Int = native.value
  def unprintablePlane: Int = native.value
  def flutterPlane: Int = native.value
  def startOfPlatformPlanes: Int = native.value
  def androidPlane: Int = native.value
  def fuchsiaPlane: Int = native.value
  def iosPlane: Int = native.value
  def macosPlane: Int = native.value
  def gtkPlane: Int = native.value
  def windowsPlane: Int = native.value
  def webPlane: Int = native.value
  def glfwPlane: Int = native.value
  def space: LogicalKeyboardKey = native.value
  def exclamation: LogicalKeyboardKey = native.value
  def quote: LogicalKeyboardKey = native.value
  def numberSign: LogicalKeyboardKey = native.value
  def dollar: LogicalKeyboardKey = native.value
  def percent: LogicalKeyboardKey = native.value
  def ampersand: LogicalKeyboardKey = native.value
  def quoteSingle: LogicalKeyboardKey = native.value
  def parenthesisLeft: LogicalKeyboardKey = native.value
  def parenthesisRight: LogicalKeyboardKey = native.value
  def asterisk: LogicalKeyboardKey = native.value
  def add: LogicalKeyboardKey = native.value
  def comma: LogicalKeyboardKey = native.value
  def minus: LogicalKeyboardKey = native.value
  def period: LogicalKeyboardKey = native.value
  def slash: LogicalKeyboardKey = native.value
  def digit0: LogicalKeyboardKey = native.value
  def digit1: LogicalKeyboardKey = native.value
  def digit2: LogicalKeyboardKey = native.value
  def digit3: LogicalKeyboardKey = native.value
  def digit4: LogicalKeyboardKey = native.value
  def digit5: LogicalKeyboardKey = native.value
  def digit6: LogicalKeyboardKey = native.value
  def digit7: LogicalKeyboardKey = native.value
  def digit8: LogicalKeyboardKey = native.value
  def digit9: LogicalKeyboardKey = native.value
  def colon: LogicalKeyboardKey = native.value
  def semicolon: LogicalKeyboardKey = native.value
  def less: LogicalKeyboardKey = native.value
  def equal: LogicalKeyboardKey = native.value
  def greater: LogicalKeyboardKey = native.value
  def question: LogicalKeyboardKey = native.value
  def at: LogicalKeyboardKey = native.value
  def bracketLeft: LogicalKeyboardKey = native.value
  def backslash: LogicalKeyboardKey = native.value
  def bracketRight: LogicalKeyboardKey = native.value
  def caret: LogicalKeyboardKey = native.value
  def underscore: LogicalKeyboardKey = native.value
  def backquote: LogicalKeyboardKey = native.value
  def keyA: LogicalKeyboardKey = native.value
  def keyB: LogicalKeyboardKey = native.value
  def keyC: LogicalKeyboardKey = native.value
  def keyD: LogicalKeyboardKey = native.value
  def keyE: LogicalKeyboardKey = native.value
  def keyF: LogicalKeyboardKey = native.value
  def keyG: LogicalKeyboardKey = native.value
  def keyH: LogicalKeyboardKey = native.value
  def keyI: LogicalKeyboardKey = native.value
  def keyJ: LogicalKeyboardKey = native.value
  def keyK: LogicalKeyboardKey = native.value
  def keyL: LogicalKeyboardKey = native.value
  def keyM: LogicalKeyboardKey = native.value
  def keyN: LogicalKeyboardKey = native.value
  def keyO: LogicalKeyboardKey = native.value
  def keyP: LogicalKeyboardKey = native.value
  def keyQ: LogicalKeyboardKey = native.value
  def keyR: LogicalKeyboardKey = native.value
  def keyS: LogicalKeyboardKey = native.value
  def keyT: LogicalKeyboardKey = native.value
  def keyU: LogicalKeyboardKey = native.value
  def keyV: LogicalKeyboardKey = native.value
  def keyW: LogicalKeyboardKey = native.value
  def keyX: LogicalKeyboardKey = native.value
  def keyY: LogicalKeyboardKey = native.value
  def keyZ: LogicalKeyboardKey = native.value
  def braceLeft: LogicalKeyboardKey = native.value
  def bar: LogicalKeyboardKey = native.value
  def braceRight: LogicalKeyboardKey = native.value
  def tilde: LogicalKeyboardKey = native.value
  def unidentified: LogicalKeyboardKey = native.value
  def backspace: LogicalKeyboardKey = native.value
  def tab: LogicalKeyboardKey = native.value
  def enter: LogicalKeyboardKey = native.value
  def escape: LogicalKeyboardKey = native.value
  def delete: LogicalKeyboardKey = native.value
  def accel: LogicalKeyboardKey = native.value
  def altGraph: LogicalKeyboardKey = native.value
  def capsLock: LogicalKeyboardKey = native.value
  def fn: LogicalKeyboardKey = native.value
  def fnLock: LogicalKeyboardKey = native.value
  def hyper: LogicalKeyboardKey = native.value
  def numLock: LogicalKeyboardKey = native.value
  def scrollLock: LogicalKeyboardKey = native.value
  def superKey: LogicalKeyboardKey = native.value
  def symbol: LogicalKeyboardKey = native.value
  def symbolLock: LogicalKeyboardKey = native.value
  def shiftLevel5: LogicalKeyboardKey = native.value
  def arrowDown: LogicalKeyboardKey = native.value
  def arrowLeft: LogicalKeyboardKey = native.value
  def arrowRight: LogicalKeyboardKey = native.value
  def arrowUp: LogicalKeyboardKey = native.value
  def `end`: LogicalKeyboardKey = native.value
  def home: LogicalKeyboardKey = native.value
  def pageDown: LogicalKeyboardKey = native.value
  def pageUp: LogicalKeyboardKey = native.value
  def clear: LogicalKeyboardKey = native.value
  def copy: LogicalKeyboardKey = native.value
  def crSel: LogicalKeyboardKey = native.value
  def cut: LogicalKeyboardKey = native.value
  def eraseEof: LogicalKeyboardKey = native.value
  def exSel: LogicalKeyboardKey = native.value
  def insert: LogicalKeyboardKey = native.value
  def paste: LogicalKeyboardKey = native.value
  def redo: LogicalKeyboardKey = native.value
  def undo: LogicalKeyboardKey = native.value
  def accept: LogicalKeyboardKey = native.value
  def again: LogicalKeyboardKey = native.value
  def attn: LogicalKeyboardKey = native.value
  def cancel: LogicalKeyboardKey = native.value
  def contextMenu: LogicalKeyboardKey = native.value
  def execute: LogicalKeyboardKey = native.value
  def find: LogicalKeyboardKey = native.value
  def help: LogicalKeyboardKey = native.value
  def pause: LogicalKeyboardKey = native.value
  def play: LogicalKeyboardKey = native.value
  def props: LogicalKeyboardKey = native.value
  def select: LogicalKeyboardKey = native.value
  def zoomIn: LogicalKeyboardKey = native.value
  def zoomOut: LogicalKeyboardKey = native.value
  def brightnessDown: LogicalKeyboardKey = native.value
  def brightnessUp: LogicalKeyboardKey = native.value
  def camera: LogicalKeyboardKey = native.value
  def eject: LogicalKeyboardKey = native.value
  def logOff: LogicalKeyboardKey = native.value
  def power: LogicalKeyboardKey = native.value
  def powerOff: LogicalKeyboardKey = native.value
  def printScreen: LogicalKeyboardKey = native.value
  def hibernate: LogicalKeyboardKey = native.value
  def standby: LogicalKeyboardKey = native.value
  def wakeUp: LogicalKeyboardKey = native.value
  def allCandidates: LogicalKeyboardKey = native.value
  def alphanumeric: LogicalKeyboardKey = native.value
  def codeInput: LogicalKeyboardKey = native.value
  def compose: LogicalKeyboardKey = native.value
  def convert: LogicalKeyboardKey = native.value
  def finalMode: LogicalKeyboardKey = native.value
  def groupFirst: LogicalKeyboardKey = native.value
  def groupLast: LogicalKeyboardKey = native.value
  def groupNext: LogicalKeyboardKey = native.value
  def groupPrevious: LogicalKeyboardKey = native.value
  def modeChange: LogicalKeyboardKey = native.value
  def nextCandidate: LogicalKeyboardKey = native.value
  def nonConvert: LogicalKeyboardKey = native.value
  def previousCandidate: LogicalKeyboardKey = native.value
  def process: LogicalKeyboardKey = native.value
  def singleCandidate: LogicalKeyboardKey = native.value
  def hangulMode: LogicalKeyboardKey = native.value
  def hanjaMode: LogicalKeyboardKey = native.value
  def junjaMode: LogicalKeyboardKey = native.value
  def eisu: LogicalKeyboardKey = native.value
  def hankaku: LogicalKeyboardKey = native.value
  def hiragana: LogicalKeyboardKey = native.value
  def hiraganaKatakana: LogicalKeyboardKey = native.value
  def kanaMode: LogicalKeyboardKey = native.value
  def kanjiMode: LogicalKeyboardKey = native.value
  def katakana: LogicalKeyboardKey = native.value
  def romaji: LogicalKeyboardKey = native.value
  def zenkaku: LogicalKeyboardKey = native.value
  def zenkakuHankaku: LogicalKeyboardKey = native.value
  def f1: LogicalKeyboardKey = native.value
  def f2: LogicalKeyboardKey = native.value
  def f3: LogicalKeyboardKey = native.value
  def f4: LogicalKeyboardKey = native.value
  def f5: LogicalKeyboardKey = native.value
  def f6: LogicalKeyboardKey = native.value
  def f7: LogicalKeyboardKey = native.value
  def f8: LogicalKeyboardKey = native.value
  def f9: LogicalKeyboardKey = native.value
  def f10: LogicalKeyboardKey = native.value
  def f11: LogicalKeyboardKey = native.value
  def f12: LogicalKeyboardKey = native.value
  def f13: LogicalKeyboardKey = native.value
  def f14: LogicalKeyboardKey = native.value
  def f15: LogicalKeyboardKey = native.value
  def f16: LogicalKeyboardKey = native.value
  def f17: LogicalKeyboardKey = native.value
  def f18: LogicalKeyboardKey = native.value
  def f19: LogicalKeyboardKey = native.value
  def f20: LogicalKeyboardKey = native.value
  def f21: LogicalKeyboardKey = native.value
  def f22: LogicalKeyboardKey = native.value
  def f23: LogicalKeyboardKey = native.value
  def f24: LogicalKeyboardKey = native.value
  def soft1: LogicalKeyboardKey = native.value
  def soft2: LogicalKeyboardKey = native.value
  def soft3: LogicalKeyboardKey = native.value
  def soft4: LogicalKeyboardKey = native.value
  def soft5: LogicalKeyboardKey = native.value
  def soft6: LogicalKeyboardKey = native.value
  def soft7: LogicalKeyboardKey = native.value
  def soft8: LogicalKeyboardKey = native.value
  def close: LogicalKeyboardKey = native.value
  def mailForward: LogicalKeyboardKey = native.value
  def mailReply: LogicalKeyboardKey = native.value
  def mailSend: LogicalKeyboardKey = native.value
  def mediaPlayPause: LogicalKeyboardKey = native.value
  def mediaStop: LogicalKeyboardKey = native.value
  def mediaTrackNext: LogicalKeyboardKey = native.value
  def mediaTrackPrevious: LogicalKeyboardKey = native.value
  def newKey: LogicalKeyboardKey = native.value
  def open: LogicalKeyboardKey = native.value
  def print: LogicalKeyboardKey = native.value
  def save: LogicalKeyboardKey = native.value
  def spellCheck: LogicalKeyboardKey = native.value
  def audioVolumeDown: LogicalKeyboardKey = native.value
  def audioVolumeUp: LogicalKeyboardKey = native.value
  def audioVolumeMute: LogicalKeyboardKey = native.value
  def launchApplication2: LogicalKeyboardKey = native.value
  def launchCalendar: LogicalKeyboardKey = native.value
  def launchMail: LogicalKeyboardKey = native.value
  def launchMediaPlayer: LogicalKeyboardKey = native.value
  def launchMusicPlayer: LogicalKeyboardKey = native.value
  def launchApplication1: LogicalKeyboardKey = native.value
  def launchScreenSaver: LogicalKeyboardKey = native.value
  def launchSpreadsheet: LogicalKeyboardKey = native.value
  def launchWebBrowser: LogicalKeyboardKey = native.value
  def launchWebCam: LogicalKeyboardKey = native.value
  def launchWordProcessor: LogicalKeyboardKey = native.value
  def launchContacts: LogicalKeyboardKey = native.value
  def launchPhone: LogicalKeyboardKey = native.value
  def launchAssistant: LogicalKeyboardKey = native.value
  def launchControlPanel: LogicalKeyboardKey = native.value
  def browserBack: LogicalKeyboardKey = native.value
  def browserFavorites: LogicalKeyboardKey = native.value
  def browserForward: LogicalKeyboardKey = native.value
  def browserHome: LogicalKeyboardKey = native.value
  def browserRefresh: LogicalKeyboardKey = native.value
  def browserSearch: LogicalKeyboardKey = native.value
  def browserStop: LogicalKeyboardKey = native.value
  def audioBalanceLeft: LogicalKeyboardKey = native.value
  def audioBalanceRight: LogicalKeyboardKey = native.value
  def audioBassBoostDown: LogicalKeyboardKey = native.value
  def audioBassBoostUp: LogicalKeyboardKey = native.value
  def audioFaderFront: LogicalKeyboardKey = native.value
  def audioFaderRear: LogicalKeyboardKey = native.value
  def audioSurroundModeNext: LogicalKeyboardKey = native.value
  def avrInput: LogicalKeyboardKey = native.value
  def avrPower: LogicalKeyboardKey = native.value
  def channelDown: LogicalKeyboardKey = native.value
  def channelUp: LogicalKeyboardKey = native.value
  def colorF0Red: LogicalKeyboardKey = native.value
  def colorF1Green: LogicalKeyboardKey = native.value
  def colorF2Yellow: LogicalKeyboardKey = native.value
  def colorF3Blue: LogicalKeyboardKey = native.value
  def colorF4Grey: LogicalKeyboardKey = native.value
  def colorF5Brown: LogicalKeyboardKey = native.value
  def closedCaptionToggle: LogicalKeyboardKey = native.value
  def dimmer: LogicalKeyboardKey = native.value
  def displaySwap: LogicalKeyboardKey = native.value
  def exit: LogicalKeyboardKey = native.value
  def favoriteClear0: LogicalKeyboardKey = native.value
  def favoriteClear1: LogicalKeyboardKey = native.value
  def favoriteClear2: LogicalKeyboardKey = native.value
  def favoriteClear3: LogicalKeyboardKey = native.value
  def favoriteRecall0: LogicalKeyboardKey = native.value
  def favoriteRecall1: LogicalKeyboardKey = native.value
  def favoriteRecall2: LogicalKeyboardKey = native.value
  def favoriteRecall3: LogicalKeyboardKey = native.value
  def favoriteStore0: LogicalKeyboardKey = native.value
  def favoriteStore1: LogicalKeyboardKey = native.value
  def favoriteStore2: LogicalKeyboardKey = native.value
  def favoriteStore3: LogicalKeyboardKey = native.value
  def guide: LogicalKeyboardKey = native.value
  def guideNextDay: LogicalKeyboardKey = native.value
  def guidePreviousDay: LogicalKeyboardKey = native.value
  def info: LogicalKeyboardKey = native.value
  def instantReplay: LogicalKeyboardKey = native.value
  def link: LogicalKeyboardKey = native.value
  def listProgram: LogicalKeyboardKey = native.value
  def liveContent: LogicalKeyboardKey = native.value
  def lock: LogicalKeyboardKey = native.value
  def mediaApps: LogicalKeyboardKey = native.value
  def mediaFastForward: LogicalKeyboardKey = native.value
  def mediaLast: LogicalKeyboardKey = native.value
  def mediaPause: LogicalKeyboardKey = native.value
  def mediaPlay: LogicalKeyboardKey = native.value
  def mediaRecord: LogicalKeyboardKey = native.value
  def mediaRewind: LogicalKeyboardKey = native.value
  def mediaSkip: LogicalKeyboardKey = native.value
  def nextFavoriteChannel: LogicalKeyboardKey = native.value
  def nextUserProfile: LogicalKeyboardKey = native.value
  def onDemand: LogicalKeyboardKey = native.value
  def pInPDown: LogicalKeyboardKey = native.value
  def pInPMove: LogicalKeyboardKey = native.value
  def pInPToggle: LogicalKeyboardKey = native.value
  def pInPUp: LogicalKeyboardKey = native.value
  def playSpeedDown: LogicalKeyboardKey = native.value
  def playSpeedReset: LogicalKeyboardKey = native.value
  def playSpeedUp: LogicalKeyboardKey = native.value
  def randomToggle: LogicalKeyboardKey = native.value
  def rcLowBattery: LogicalKeyboardKey = native.value
  def recordSpeedNext: LogicalKeyboardKey = native.value
  def rfBypass: LogicalKeyboardKey = native.value
  def scanChannelsToggle: LogicalKeyboardKey = native.value
  def screenModeNext: LogicalKeyboardKey = native.value
  def settings: LogicalKeyboardKey = native.value
  def splitScreenToggle: LogicalKeyboardKey = native.value
  def stbInput: LogicalKeyboardKey = native.value
  def stbPower: LogicalKeyboardKey = native.value
  def subtitle: LogicalKeyboardKey = native.value
  def teletext: LogicalKeyboardKey = native.value
  def tv: LogicalKeyboardKey = native.value
  def tvInput: LogicalKeyboardKey = native.value
  def tvPower: LogicalKeyboardKey = native.value
  def videoModeNext: LogicalKeyboardKey = native.value
  def wink: LogicalKeyboardKey = native.value
  def zoomToggle: LogicalKeyboardKey = native.value
  def dvr: LogicalKeyboardKey = native.value
  def mediaAudioTrack: LogicalKeyboardKey = native.value
  def mediaSkipBackward: LogicalKeyboardKey = native.value
  def mediaSkipForward: LogicalKeyboardKey = native.value
  def mediaStepBackward: LogicalKeyboardKey = native.value
  def mediaStepForward: LogicalKeyboardKey = native.value
  def mediaTopMenu: LogicalKeyboardKey = native.value
  def navigateIn: LogicalKeyboardKey = native.value
  def navigateNext: LogicalKeyboardKey = native.value
  def navigateOut: LogicalKeyboardKey = native.value
  def navigatePrevious: LogicalKeyboardKey = native.value
  def pairing: LogicalKeyboardKey = native.value
  def mediaClose: LogicalKeyboardKey = native.value
  def audioBassBoostToggle: LogicalKeyboardKey = native.value
  def audioTrebleDown: LogicalKeyboardKey = native.value
  def audioTrebleUp: LogicalKeyboardKey = native.value
  def microphoneToggle: LogicalKeyboardKey = native.value
  def microphoneVolumeDown: LogicalKeyboardKey = native.value
  def microphoneVolumeUp: LogicalKeyboardKey = native.value
  def microphoneVolumeMute: LogicalKeyboardKey = native.value
  def speechCorrectionList: LogicalKeyboardKey = native.value
  def speechInputToggle: LogicalKeyboardKey = native.value
  def appSwitch: LogicalKeyboardKey = native.value
  def call: LogicalKeyboardKey = native.value
  def cameraFocus: LogicalKeyboardKey = native.value
  def endCall: LogicalKeyboardKey = native.value
  def goBack: LogicalKeyboardKey = native.value
  def goHome: LogicalKeyboardKey = native.value
  def headsetHook: LogicalKeyboardKey = native.value
  def lastNumberRedial: LogicalKeyboardKey = native.value
  def notification: LogicalKeyboardKey = native.value
  def mannerMode: LogicalKeyboardKey = native.value
  def voiceDial: LogicalKeyboardKey = native.value
  def tv3DMode: LogicalKeyboardKey = native.value
  def tvAntennaCable: LogicalKeyboardKey = native.value
  def tvAudioDescription: LogicalKeyboardKey = native.value
  def tvAudioDescriptionMixDown: LogicalKeyboardKey = native.value
  def tvAudioDescriptionMixUp: LogicalKeyboardKey = native.value
  def tvContentsMenu: LogicalKeyboardKey = native.value
  def tvDataService: LogicalKeyboardKey = native.value
  def tvInputComponent1: LogicalKeyboardKey = native.value
  def tvInputComponent2: LogicalKeyboardKey = native.value
  def tvInputComposite1: LogicalKeyboardKey = native.value
  def tvInputComposite2: LogicalKeyboardKey = native.value
  def tvInputHDMI1: LogicalKeyboardKey = native.value
  def tvInputHDMI2: LogicalKeyboardKey = native.value
  def tvInputHDMI3: LogicalKeyboardKey = native.value
  def tvInputHDMI4: LogicalKeyboardKey = native.value
  def tvInputVGA1: LogicalKeyboardKey = native.value
  def tvMediaContext: LogicalKeyboardKey = native.value
  def tvNetwork: LogicalKeyboardKey = native.value
  def tvNumberEntry: LogicalKeyboardKey = native.value
  def tvRadioService: LogicalKeyboardKey = native.value
  def tvSatellite: LogicalKeyboardKey = native.value
  def tvSatelliteBS: LogicalKeyboardKey = native.value
  def tvSatelliteCS: LogicalKeyboardKey = native.value
  def tvSatelliteToggle: LogicalKeyboardKey = native.value
  def tvTerrestrialAnalog: LogicalKeyboardKey = native.value
  def tvTerrestrialDigital: LogicalKeyboardKey = native.value
  def tvTimer: LogicalKeyboardKey = native.value
  def key11: LogicalKeyboardKey = native.value
  def key12: LogicalKeyboardKey = native.value
  def suspend: LogicalKeyboardKey = native.value
  def resume: LogicalKeyboardKey = native.value
  def sleep: LogicalKeyboardKey = native.value
  def abort: LogicalKeyboardKey = native.value
  def lang1: LogicalKeyboardKey = native.value
  def lang2: LogicalKeyboardKey = native.value
  def lang3: LogicalKeyboardKey = native.value
  def lang4: LogicalKeyboardKey = native.value
  def lang5: LogicalKeyboardKey = native.value
  def intlBackslash: LogicalKeyboardKey = native.value
  def intlRo: LogicalKeyboardKey = native.value
  def intlYen: LogicalKeyboardKey = native.value
  def controlLeft: LogicalKeyboardKey = native.value
  def controlRight: LogicalKeyboardKey = native.value
  def shiftLeft: LogicalKeyboardKey = native.value
  def shiftRight: LogicalKeyboardKey = native.value
  def altLeft: LogicalKeyboardKey = native.value
  def altRight: LogicalKeyboardKey = native.value
  def metaLeft: LogicalKeyboardKey = native.value
  def metaRight: LogicalKeyboardKey = native.value
  def control: LogicalKeyboardKey = native.value
  def shift: LogicalKeyboardKey = native.value
  def alt: LogicalKeyboardKey = native.value
  def meta: LogicalKeyboardKey = native.value
  def numpadEnter: LogicalKeyboardKey = native.value
  def numpadParenLeft: LogicalKeyboardKey = native.value
  def numpadParenRight: LogicalKeyboardKey = native.value
  def numpadMultiply: LogicalKeyboardKey = native.value
  def numpadAdd: LogicalKeyboardKey = native.value
  def numpadComma: LogicalKeyboardKey = native.value
  def numpadSubtract: LogicalKeyboardKey = native.value
  def numpadDecimal: LogicalKeyboardKey = native.value
  def numpadDivide: LogicalKeyboardKey = native.value
  def numpad0: LogicalKeyboardKey = native.value
  def numpad1: LogicalKeyboardKey = native.value
  def numpad2: LogicalKeyboardKey = native.value
  def numpad3: LogicalKeyboardKey = native.value
  def numpad4: LogicalKeyboardKey = native.value
  def numpad5: LogicalKeyboardKey = native.value
  def numpad6: LogicalKeyboardKey = native.value
  def numpad7: LogicalKeyboardKey = native.value
  def numpad8: LogicalKeyboardKey = native.value
  def numpad9: LogicalKeyboardKey = native.value
  def numpadEqual: LogicalKeyboardKey = native.value
  def gameButton1: LogicalKeyboardKey = native.value
  def gameButton2: LogicalKeyboardKey = native.value
  def gameButton3: LogicalKeyboardKey = native.value
  def gameButton4: LogicalKeyboardKey = native.value
  def gameButton5: LogicalKeyboardKey = native.value
  def gameButton6: LogicalKeyboardKey = native.value
  def gameButton7: LogicalKeyboardKey = native.value
  def gameButton8: LogicalKeyboardKey = native.value
  def gameButton9: LogicalKeyboardKey = native.value
  def gameButton10: LogicalKeyboardKey = native.value
  def gameButton11: LogicalKeyboardKey = native.value
  def gameButton12: LogicalKeyboardKey = native.value
  def gameButton13: LogicalKeyboardKey = native.value
  def gameButton14: LogicalKeyboardKey = native.value
  def gameButton15: LogicalKeyboardKey = native.value
  def gameButton16: LogicalKeyboardKey = native.value
  def gameButtonA: LogicalKeyboardKey = native.value
  def gameButtonB: LogicalKeyboardKey = native.value
  def gameButtonC: LogicalKeyboardKey = native.value
  def gameButtonLeft1: LogicalKeyboardKey = native.value
  def gameButtonLeft2: LogicalKeyboardKey = native.value
  def gameButtonMode: LogicalKeyboardKey = native.value
  def gameButtonRight1: LogicalKeyboardKey = native.value
  def gameButtonRight2: LogicalKeyboardKey = native.value
  def gameButtonSelect: LogicalKeyboardKey = native.value
  def gameButtonStart: LogicalKeyboardKey = native.value
  def gameButtonThumbLeft: LogicalKeyboardKey = native.value
  def gameButtonThumbRight: LogicalKeyboardKey = native.value
  def gameButtonX: LogicalKeyboardKey = native.value
  def gameButtonY: LogicalKeyboardKey = native.value
  def gameButtonZ: LogicalKeyboardKey = native.value
  def knownLogicalKeys: List[LogicalKeyboardKey] = native.value
  def findKeyByKeyId(keyId: Int): LogicalKeyboardKey = native.value
  def isControlCharacter(label: String): Boolean = native.value
  def collapseSynonyms(input: Set[LogicalKeyboardKey]): Set[LogicalKeyboardKey] = native.value
  def expandSynonyms(input: Set[LogicalKeyboardKey]): Set[LogicalKeyboardKey] = native.value

// ─── clipboard.dart ────────────────────────────────────────

@native
@DartImport("package:flutter/services.dart")
class ClipboardData(
  val text: String
) extends DartObject

@native
@DartImport("package:flutter/services.dart")
abstract class Clipboard extends DartObject

@native
@DartImport("package:flutter/services.dart")
object Clipboard:
  def kTextPlain: String = native.value
  def setData(data: ClipboardData): scala.concurrent.Future[Unit] = native.value
  def getData(format: String): scala.concurrent.Future[ClipboardData] = native.value
  def hasStrings(): scala.concurrent.Future[Boolean] = native.value

