// Generated by sart-facadegen. Do not edit by hand —
// regenerate via `sbt sartFacadesRegen` (see facadegen.conf).
package flutter.services

import sart.dart.*

// ─── autofill.dart ────────────────────────────────────────

@native
@DartImport("package:flutter/services.dart")
abstract class AutofillHints extends DartObject

@native
@DartImport("package:flutter/services.dart")
object AutofillHints:
  def addressCity: String = native.value
  def addressCityAndState: String = native.value
  def addressState: String = native.value
  def birthday: String = native.value
  def birthdayDay: String = native.value
  def birthdayMonth: String = native.value
  def birthdayYear: String = native.value
  def countryCode: String = native.value
  def countryName: String = native.value
  def creditCardExpirationDate: String = native.value
  def creditCardExpirationDay: String = native.value
  def creditCardExpirationMonth: String = native.value
  def creditCardExpirationYear: String = native.value
  def creditCardFamilyName: String = native.value
  def creditCardGivenName: String = native.value
  def creditCardMiddleName: String = native.value
  def creditCardName: String = native.value
  def creditCardNumber: String = native.value
  def creditCardSecurityCode: String = native.value
  def creditCardType: String = native.value
  def email: String = native.value
  def familyName: String = native.value
  def fullStreetAddress: String = native.value
  def gender: String = native.value
  def givenName: String = native.value
  def impp: String = native.value
  def jobTitle: String = native.value
  def language: String = native.value
  def location: String = native.value
  def middleInitial: String = native.value
  def middleName: String = native.value
  def name: String = native.value
  def namePrefix: String = native.value
  def nameSuffix: String = native.value
  def newPassword: String = native.value
  def newUsername: String = native.value
  def nickname: String = native.value
  def oneTimeCode: String = native.value
  def organizationName: String = native.value
  def password: String = native.value
  def photo: String = native.value
  def postalAddress: String = native.value
  def postalAddressExtended: String = native.value
  def postalAddressExtendedPostalCode: String = native.value
  def postalCode: String = native.value
  def streetAddressLevel1: String = native.value
  def streetAddressLevel2: String = native.value
  def streetAddressLevel3: String = native.value
  def streetAddressLevel4: String = native.value
  def streetAddressLine1: String = native.value
  def streetAddressLine2: String = native.value
  def streetAddressLine3: String = native.value
  def sublocality: String = native.value
  def telephoneNumber: String = native.value
  def telephoneNumberAreaCode: String = native.value
  def telephoneNumberCountryCode: String = native.value
  def telephoneNumberDevice: String = native.value
  def telephoneNumberExtension: String = native.value
  def telephoneNumberLocal: String = native.value
  def telephoneNumberLocalPrefix: String = native.value
  def telephoneNumberLocalSuffix: String = native.value
  def telephoneNumberNational: String = native.value
  def transactionAmount: String = native.value
  def transactionCurrency: String = native.value
  def url: String = native.value
  def username: String = native.value

// ─── text_input.dart ────────────────────────────────────────

@native
@DartImport("package:flutter/services.dart")
class TextInput extends DartObject:
  def scribbleInProgress: Boolean = native.value

@native
@DartImport("package:flutter/services.dart")
object TextInput:
  def scribbleClients: Map[String, DartObject] = native.value
  def setChannel(newChannel: DartObject): Unit = native.value
  def setInputControl(newControl: DartObject): Unit = native.value
  def restorePlatformInputControl(): Unit = native.value
  def ensureInitialized(): Unit = native.value
  def attach(client: DartObject, configuration: DartObject): DartObject = native.value
  def updateEditingValue(value: DartObject): Unit = native.value
  def finishAutofillContext(shouldSave: Boolean = native.value): Unit = native.value
  def registerScribbleElement(elementIdentifier: String, scribbleClient: DartObject): Unit = native.value
  def unregisterScribbleElement(elementIdentifier: String): Unit = native.value

// ─── text_formatter.dart ────────────────────────────────────────

@native
@DartImport("package:flutter/services.dart")
abstract class TextInputFormatter extends DartObject:
  def formatEditUpdate(oldValue: DartObject, newValue: DartObject): DartObject = native.value

@native
@DartImport("package:flutter/services.dart")
object TextInputFormatter:
  def withFunction(formatFunction: (DartObject, DartObject) => DartObject): TextInputFormatter = native.value

