package sart.compiler

import scala.tasty.inspector.{Inspector, Tasty}
import scala.quoted.Quotes
import scala.collection.mutable
import java.nio.file.{Files, Path}
import java.nio.charset.StandardCharsets

/** The Sart Dart emitter.
 *
 *  Structured in two passes over the incoming TASTy:
 *
 *    1. [[collect]] walks every tree, noting every `@DartImport` and
 *       `@DartPackage` it encounters on referenced symbols. These drive
 *       the emitted Dart file's `import` header and the generated
 *       `pubspec.yaml`.
 *    2. [[emit]] walks again and writes the Dart source into a StringBuilder.
 *
 *  The emitter is deliberately limited to the subset of Scala 3 used by the
 *  counter-app PoC: classes, `val`/`var` fields, `override def`, constructor
 *  params as final fields, `Apply`/`Select`/`Ident`, string literals and
 *  interpolation, `List(...)` literals, and zero-arg `() => ...` closures.
 *  Any tree shape the emitter doesn't recognize produces a `/* TODO: … */`
 *  comment in the output, which makes unsupported constructs loud rather
 *  than silent.
 */
class DartEmitter(outDir: Path) extends Inspector:

  // ── State collected across inspection runs ─────────────────────────────
  private val imports       = mutable.LinkedHashSet[String]()
  private val packages      = mutable.LinkedHashSet[DartPkg]()
  private val pubspecBlocks = mutable.LinkedHashSet[String]()
  private val bodyBuf       = new StringBuilder

  private case class DartPkg(name: String, version: String, sdk: String)

  // ── Inspector entry point ──────────────────────────────────────────────
  def inspect(using quotes: Quotes)(tastys: List[Tasty[quotes.type]]): Unit =
    val e = new Pass[quotes.type](bodyBuf, imports, packages, pubspecBlocks)
    for tasty <- tastys do
      e.run(tasty.ast)

  // ── Output ─────────────────────────────────────────────────────────────
  def writeOutput(): Unit =
    val libDir = outDir.resolve("lib")
    Files.createDirectories(libDir)

    val header = new StringBuilder
    for i <- imports.toList.sorted do
      header.append(s"import '$i';\n")
    if imports.nonEmpty then header.append('\n')

    val mainDart = header.toString + bodyBuf.toString
    Files.writeString(libDir.resolve("main.dart"), mainDart, StandardCharsets.UTF_8)

    val pubspec = renderPubspec()
    Files.writeString(outDir.resolve("pubspec.yaml"), pubspec, StandardCharsets.UTF_8)

  private def renderPubspec(): String =
    val b = new StringBuilder
    b.append("# Generated by Sart — do not edit by hand.\n")
    b.append("name: sart_example\n")
    b.append("description: Scala-authored Flutter app, compiled via Sart.\n")
    b.append("publish_to: 'none'\n")
    b.append("version: 0.1.0\n\n")
    b.append("environment:\n")
    b.append("  sdk: '>=3.0.0 <4.0.0'\n\n")
    b.append("dependencies:\n")
    for p <- packages.toList.sortBy(_.name) do
      if p.sdk.nonEmpty then
        b.append(s"  ${p.name}:\n")
        b.append(s"    sdk: ${p.sdk}\n")
      else if p.version.nonEmpty then
        b.append(s"  ${p.name}: ${p.version}\n")
      else
        b.append(s"  ${p.name}: any\n")
    for block <- pubspecBlocks do
      val normalized = normalizePubspecBlock(block)
      if normalized.nonEmpty then
        b.append('\n')
        b.append(normalized)
        if !normalized.endsWith("\n") then b.append('\n')
    b.toString

  /** Produce a canonical indentation for a `@DartPubspec` block so a
   *  sloppily-written annotation (`"""` with surrounding blank lines or
   *  leading whitespace matching the source indentation) still lands in
   *  the pubspec as valid YAML.
   *
   *  Steps: drop leading/trailing blank lines, find the minimum indent of
   *  non-blank lines, strip that indent from every line.
   */
  private def normalizePubspecBlock(raw: String): String =
    val lines = raw.split('\n').toList
      .dropWhile(_.trim.isEmpty)
      .reverse.dropWhile(_.trim.isEmpty).reverse
    if lines.isEmpty then ""
    else
      val minIndent = lines
        .filter(_.trim.nonEmpty)
        .map(_.takeWhile(_ == ' ').length)
        .minOption
        .getOrElse(0)
      lines.map(l => if l.length >= minIndent then l.drop(minIndent) else l)
        .mkString("\n")

  // ── Per-run emitter, parameterized over Quotes ─────────────────────────
  //
  // Keeping everything inside a nested class means the reflect types stay
  // path-dependent on a stable `quotes` — we don't have to thread it through
  // every method signature by hand.
  private class Pass[Q <: Quotes & Singleton](
    out: StringBuilder,
    imports: mutable.LinkedHashSet[String],
    packages: mutable.LinkedHashSet[DartPkg],
    pubspecBlocks: mutable.LinkedHashSet[String]
  )(using val q: Q):
    import q.reflect.*

    private var indent = 0
    private def ind(): String = "  " * indent
    private def line(s: String): Unit = { out.append(ind()); out.append(s); out.append('\n') }
    private def blank(): Unit = out.append('\n')

    // ── Annotation helpers ───────────────────────────────────────────────

    private def annoFqn(a: Term): String = a.tpe.typeSymbol.fullName

    private def hasNative(sym: Symbol): Boolean =
      sym.annotations.exists(a => annoFqn(a) == "sart.dart.native")

    /** Unwrap a `Literal(Constant(...))` into its underlying value, whatever
     *  the concrete `Constant` subtype is.
     */
    private def litValue(t: Term): Option[Any] = t match
      case Literal(c) => Some(c.value)
      case _ => None

    /** Extract constant args (Strings/Ints/Booleans) from an annotation tree. */
    private def constArgs(a: Term): List[Any] =
      a match
        case Apply(_, args) =>
          args.flatMap {
            case t if litValue(t).isDefined => litValue(t).toList
            case NamedArg(_, t) if litValue(t).isDefined => litValue(t).toList
            case _ => Nil
          }
        case _ => Nil

    /** Named-arg lookup on an annotation (falls back to positional). */
    private def annoArg(a: Term, name: String, positional: Int): Option[Any] =
      a match
        case Apply(_, args) =>
          val named = args.collectFirst {
            case NamedArg(n, t) if n == name && litValue(t).isDefined => litValue(t).get
          }
          named.orElse {
            args.zipWithIndex.collectFirst {
              case (t, i) if i == positional && litValue(t).isDefined => litValue(t).get
            }
          }
        case _ => None

    private def recordAnnotations(sym: Symbol): Unit =
      for a <- sym.annotations do
        annoFqn(a) match
          case "sart.dart.DartImport" =>
            constArgs(a).collectFirst { case s: String => s }.foreach(imports += _)
          case "sart.dart.DartPackage" =>
            val name    = annoArg(a, "name",    0).collect { case s: String => s }.getOrElse("")
            val version = annoArg(a, "version", 1).collect { case s: String => s }.getOrElse("")
            val sdk     = annoArg(a, "sdk",     2).collect { case s: String => s }.getOrElse("")
            if name.nonEmpty then packages += DartPkg(name, version, sdk)
          case "sart.dart.DartPubspec" =>
            constArgs(a).collectFirst { case s: String => s }.foreach(pubspecBlocks += _)
          case _ =>

    /** Pull the emitted Dart name from `@DartName(...)` if present. */
    private def dartName(sym: Symbol): String =
      sym.annotations.collectFirst {
        case a if annoFqn(a) == "sart.dart.DartName" =>
          constArgs(a).collectFirst { case s: String => s }
      }.flatten.getOrElse(sym.name)

    // ── Top-level driver ─────────────────────────────────────────────────

    def run(tree: Tree): Unit = tree match
      case p: PackageClause =>
        p.stats.foreach(runTop)
      case other =>
        runTop(other)

    private def runTop(t: Tree): Unit = t match
      case _: Import =>
        () // Scala imports are irrelevant; we emit our own Dart imports
      case p: PackageClause =>
        p.stats.foreach(runTop)
      case cd: ClassDef =>
        val sym = cd.symbol
        val name = sym.name
        if hasNative(sym) then
          recordAnnotations(sym)
        else if name.endsWith("$package$") || name.endsWith("$package") then
          // Scala 3 stores top-level defs inside a synthetic package class;
          // descend and treat its stats as top-level trees.
          cd.body.foreach(runTop)
        else if isMainWrapper(cd) then
          () // `@main def foo` generates a wrapper class we don't want to emit.
        else if sym.flags.is(Flags.Enum) && !sym.flags.is(Flags.Case) then
          // The enum parent class (`enum Filter { case All, … }` produces
          // a sealed `class Filter extends scala.reflect.Enum`). Skip —
          // we emit the Dart enum from the companion object below instead.
          ()
        else if name.endsWith("$") then
          // A module class. Three interesting varieties:
          //   - enum companion → contains the enum's case values
          //   - case-object module (`case object Foo`) → emit a class `Foo`
          //   - anything else (regular `object` companion) → skip for now
          val companion = sym.companionClass
          if companion.exists && companion.flags.is(Flags.Enum) then
            emitEnumFromCompanion(cd, companion)
          else if sym.flags.is(Flags.Case) then
            emitCaseObject(cd)
          // Regular companion objects: no Dart payload yet.
        else if name.contains("$") || sym.flags.is(Flags.Synthetic) then
          () // Synthetic/anonymous classes — skip.
        else
          emitClassDef(cd)
      case dd: DefDef =>
        if dd.symbol.flags.is(Flags.ExtensionMethod) then emitExtensionMethod(dd)
        else emitTopLevelDef(dd)
      case vd: ValDef =>
        emitTopLevelVal(vd)
      case _ =>
        line(s"/* TODO top-level: ${t.getClass.getSimpleName} */")

    /** Emit a Dart class for a Scala `case object`. The module class has
     *  the form `FooName$` in TASTy; we strip the trailing `$` for the
     *  Dart name. For now the emission is an empty class (no singleton
     *  value-level support); references to the object as a value will
     *  need follow-up work to translate as `FooName()` or a const instance.
     */
    private def emitCaseObject(cd: ClassDef): Unit =
      val objName = cd.symbol.name.stripSuffix("$")
      val parentTpt = realParent(cd)
      val ext = parentTpt.map(t => s" extends ${emitTypeRef(t.tpe)}").getOrElse("")
      line(s"class $objName$ext {}")
      blank()

    /** Emit a Dart enum from the companion module of a Scala 3 enum class.
     *
     *  Simple enum cases (no parameters) are stored as `val` members of the
     *  companion, each typed as the enum class itself. For these we emit
     *  `enum Name { A, B, C }`.
     *
     *  Parameterised cases (e.g. `case Foo(x: Int)`) appear as their own
     *  subclass `ClassDef`s elsewhere in the tree; this helper leaves a
     *  TODO marker for that path — sealed-hierarchy emission (task 15)
     *  will handle it.
     */
    private def emitEnumFromCompanion(companionCd: ClassDef, enumCls: Symbol): Unit =
      val caseVals = companionCd.body.collect {
        case vd: ValDef
            if !vd.symbol.flags.is(Flags.Synthetic)
            && vd.tpt.tpe.typeSymbol == enumCls =>
          vd
      }
      if caseVals.nonEmpty then
        val names = caseVals.map(_.name).mkString(", ")
        line(s"enum ${enumCls.name} { $names }")
        blank()
      else
        line(s"/* TODO: parameterised enum ${enumCls.name} — cases are subclasses */")
        blank()

    /** Recognise the `@main def foo` wrapper class Scala 3 synthesises.
     *  Heuristic: the class contains a `main(args: Array[String])` method.
     *  The synthesised main may or may not be flagged `Synthetic` across
     *  Scala 3 minor versions, so we check the method signature directly.
     */
    private def isMainWrapper(cd: ClassDef): Boolean =
      cd.body.exists {
        case dd: DefDef if dd.symbol.name == "main" =>
          val ps = dd.paramss.flatMap(_.params).collect { case vd: ValDef => vd }
          ps match
            case List(vd) => vd.tpt.tpe.typeSymbol.fullName == "scala.Array"
            case _        => false
        case _ => false
      }

    // ── Classes ──────────────────────────────────────────────────────────

    // Scala auto-parents (roots, case-class/serializable markers) we never
    // carry into Dart. Matching both fully-qualified and simple names
    // because `Serializable` can resolve as `scala.` or `java.io.` depending
    // on alias path.
    private val skippedParentFqns = Set(
      "java.lang.Object", "scala.Any", "sart.dart.DartObject",
      "scala.Product", "scala.Serializable", "scala.Equals",
      "java.io.Serializable"
    )
    private val skippedParentSimples = Set("Product", "Serializable", "Equals")

    /** Walk tree shapes like `Apply(TypeApply(Select(New(tt), "<init>"),
     *  tpArgs), valArgs)` to the underlying parent `TypeTree`.
     */
    private def findParentType(t: Tree): Option[TypeTree] = t match
      case tt: TypeTree        => Some(tt)
      case New(tt: TypeTree)   => Some(tt)
      case Apply(inner, _)     => findParentType(inner)
      case TypeApply(inner, _) => findParentType(inner)
      case Select(inner, _)    => findParentType(inner)
      case _                   => None

    /** First "real" parent type from a ClassDef's parent list (i.e. dropping
     *  scala.Any / Object / DartObject / case-class markers).
     */
    private def realParent(cd: ClassDef): Option[TypeTree] =
      cd.parents.flatMap(findParentType).find { tt =>
        val s = tt.tpe.typeSymbol
        !skippedParentFqns(s.fullName) && !skippedParentSimples(s.name)
      }

    private def emitClassDef(cd: ClassDef): Unit =
      val sym = cd.symbol
      if hasNative(sym) then
        recordAnnotations(sym)
        return

      // Scala 3 synthesises a companion for every `object` definition, but
      // a module class's body is emitted as the class itself. For objects,
      // we rename to drop the trailing `$`. A top-level `object Foo` becomes
      // `class Foo` in Dart with static-ish members; for the counter app we
      // don't actually emit any user objects, only the `@main` entrypoint.
      val rawName = sym.name
      if rawName.endsWith("$") then return
      // Anonymous / synthesised classes the compiler generates (e.g. for
      // `@main` wrappers) — skip them.
      if rawName.contains("$") || sym.flags.is(Flags.Synthetic) then return

      val className = rawName

      val parentTpt = realParent(cd)
      val extendsClause = parentTpt.map(tt => s" extends ${emitTypeRef(tt.tpe)}").getOrElse("")

      // Primary-constructor parameters become `final` fields in Dart, plus
      // a named constructor of the form `ClassName({required this.field});`.
      val ctor = cd.constructor
      val ctorParams: List[ValDef] = ctor.paramss.flatMap(_.params).collect { case vd: ValDef => vd }
      val typeParams: String = typeParamSig(ctor)

      // Member stats (val/var/def/override def); the primary-ctor body is
      // in `cd.body`, separate from the constructor params.
      val memberStats = cd.body.collect {
        case vd: ValDef => vd
        case dd: DefDef => dd
      }.filterNot { stat =>
        // Drop compiler-synthesised accessors for ctor params; we emit the
        // fields ourselves.
        stat.symbol.flags.is(Flags.ParamAccessor) ||
        stat.symbol.flags.is(Flags.Synthetic) ||
        stat.symbol.name == "<init>"
      }

      // Sealed parents (`sealed trait Shape`) legitimately have empty
      // bodies, so we no longer short-circuit on emptiness here — the
      // `@main` wrapper we used to catch via this rule is now caught by
      // `isMainWrapper` upstream.
      val prefix =
        if sym.flags.is(Flags.Sealed) then "sealed "
        else if sym.flags.is(Flags.Abstract) && !sym.flags.is(Flags.Trait) then "abstract "
        else ""

      line(s"${prefix}class $className$typeParams$extendsClause {")
      indent += 1

      for p <- ctorParams do
        line(s"final ${emitTypeRef(p.tpt.tpe)} ${p.name};")

      // User classes get a **positional** primary constructor (matching how
      // Scala call sites actually invoke them). Named args in Scala source
      // compile to the same `Apply`, so when we emit the call we strip the
      // `NamedArg` wrapper for user-class constructions. Facade classes are
      // different — they use Dart-native named parameters and are handled
      // via the @native annotation path (no Dart ctor is ever emitted for
      // them; the user writes `Widget(title = …)` and the emitter keeps the
      // name because the facade's actual Dart class uses named params).
      if ctorParams.nonEmpty then
        val paramList = ctorParams.map(p => s"this.${p.name}").mkString(", ")
        line(s"$className($paramList);")
        blank()

      for stat <- memberStats do
        stat match
          case vd: ValDef => emitField(vd)
          case dd: DefDef => emitMethod(dd)

      if sym.flags.is(Flags.Case) && ctorParams.nonEmpty then
        emitCaseClassSynths(className, ctorParams)

      indent -= 1
      line("}")
      blank()

    /** Emit the Dart equivalents of a Scala case class's auto-generated
     *  members: `==`, `hashCode`, `toString`, `copyWith`. Scala's synthesised
     *  versions (`equals`, `canEqual`, etc.) are `Synthetic` so they're
     *  filtered out above and we write our own instead.
     *
     *  Nullability caveat: `copyWith({T? field})` with `field ?? this.field`
     *  can't distinguish "not provided" from "provided null" for nullable
     *  fields. Good enough while case-class fields are non-nullable; when
     *  `Option[T]` → `T?` lands (Phase 2), swap in a sentinel.
     */
    private def emitCaseClassSynths(className: String, params: List[ValDef]): Unit =
      val names = params.map(_.name)
      val types = params.map(p => emitTypeRef(p.tpt.tpe))

      // ==  (the constructor above already emitted a trailing blank line).
      line("@override")
      line("bool operator ==(Object other) =>")
      indent += 1
      val eqCheck = names.map(n => s"other.$n == $n").mkString(" && ")
      line(s"identical(this, other) ||")
      line(s"other is $className && $eqCheck;")
      indent -= 1
      blank()

      // hashCode
      line("@override")
      if names.size == 1 then
        line(s"int get hashCode => ${names.head}.hashCode;")
      else
        line(s"int get hashCode => Object.hash(${names.mkString(", ")});")
      blank()

      // toString — each `$$name` in Scala source becomes `$name` in the
      // emitted Dart, which Dart then interpolates at runtime.
      line("@override")
      val tsParts = names.map(n => s"$n: $$$n").mkString(", ")
      line(s"String toString() => '$className($tsParts)';")
      blank()

      // copyWith — method's own parameters are named (Dart convention for
      // `copyWith`), but the body's constructor call is positional to
      // match the class's positional primary ctor.
      val cwParams = names.zip(types).map { case (n, t) => s"$t? $n" }.mkString(", ")
      val cwArgs   = names.map(n => s"$n ?? this.$n").mkString(", ")
      line(s"$className copyWith({$cwParams}) =>")
      indent += 1
      line(s"$className($cwArgs);")
      indent -= 1

    private def emitField(vd: ValDef): Unit =
      val isMutable = vd.symbol.flags.is(Flags.Mutable)
      val prefix = if isMutable then "" else "final "
      val init = vd.rhs.map(r => s" = ${emitExpr(r)}").getOrElse("")
      line(s"$prefix${emitTypeRef(vd.tpt.tpe)} ${vd.name}$init;")

    private def emitMethod(dd: DefDef): Unit =
      val sym = dd.symbol
      if sym.flags.is(Flags.Synthetic) then return

      if sym.flags.is(Flags.Override) then line("@override")

      val retType = emitTypeRef(dd.returnTpt.tpe)
      val params = dd.paramss.flatMap(_.params).collect { case vd: ValDef => vd }
      val paramStr = params.map(p => s"${emitTypeRef(p.tpt.tpe)} ${p.name}").mkString(", ")
      val tparams = typeParamSig(dd)

      dd.rhs match
        case Some(body) =>
          line(s"$retType ${sym.name}$tparams($paramStr) {")
          indent += 1
          emitBodyAsStatements(body, returnLast = retType != "void")
          indent -= 1
          line("}")
          blank()
        case None =>
          line(s"$retType ${sym.name}$tparams($paramStr);")

    /** Extract `[T, U]`-style type parameters from a `DefDef` (including the
     *  primary constructor, which is how class-level type params surface in
     *  TASTy). Returns `""` when none, or `"<T, U>"` for Dart.
     */
    private def typeParamSig(dd: DefDef): String =
      val names = dd.paramss.collect {
        case tpc: TypeParamClause => tpc.params.map(_.name)
      }.flatten
      if names.isEmpty then "" else names.mkString("<", ", ", ">")

    // ── Top-level defs & vals ────────────────────────────────────────────

    /** Emit a Scala 3 extension method as a Dart `extension` block with
     *  one member.
     *
     *  Scala shape:  `extension (n: Int) def squared: Int = n * n`
     *  TASTy shape:  DefDef `squared` with `Flags.ExtensionMethod`, whose first
     *                term-param-clause has a single ValDef (the receiver),
     *                and whose body may reference the receiver by name.
     *  Dart shape:   `extension SartIntSquared on int { int get squared {
     *                  final int n = this; return n * n; } }`
     *
     *  We inject `final T n = this;` as the first statement of the body so
     *  references to the receiver in the original body transfer unchanged.
     *  A future pass can rewrite refs to `this` directly and drop the alias.
     */
    private def emitExtensionMethod(dd: DefDef): Unit =
      val sym = dd.symbol
      val termClauses: List[List[ValDef]] = dd.paramss.collect {
        case tpc: TermParamClause => tpc.params
      }
      if termClauses.isEmpty then
        line(s"/* TODO extension $sym — no term params */")
        return

      val receiver = termClauses.head.headOption match
        case Some(vd: ValDef) => vd
        case _ =>
          line(s"/* TODO extension $sym — unexpected receiver shape */")
          return

      val methodParams = termClauses.drop(1).flatten
      val receiverTpe  = emitTypeRef(receiver.tpt.tpe)
      val retType      = emitTypeRef(dd.returnTpt.tpe)
      val tparams      = typeParamSig(dd)

      val extName = s"Sart${receiver.tpt.tpe.typeSymbol.name}${sym.name.capitalize}"
      line(s"extension $extName$tparams on $receiverTpe {")
      indent += 1

      val methodHeader =
        if methodParams.isEmpty then
          s"$retType get ${sym.name} {"
        else
          val paramStr = methodParams.map(p => s"${emitTypeRef(p.tpt.tpe)} ${p.name}").mkString(", ")
          s"$retType ${sym.name}($paramStr) {"
      line(methodHeader)
      indent += 1
      line(s"final $receiverTpe ${receiver.name} = this;")
      dd.rhs match
        case Some(body) => emitBodyAsStatements(body, returnLast = retType != "void")
        case None       => ()
      indent -= 1
      line("}")

      indent -= 1
      line("}")
      blank()

    private def emitTopLevelDef(dd: DefDef): Unit =
      val sym = dd.symbol
      if sym.flags.is(Flags.Synthetic) then return
      // The `@main def foo` pattern produces (a) a method inside the
      // synthetic package-object class (carrying the @main annotation), and
      // (b) a wrapper class we skip elsewhere. We only want the def.
      val mainFqns = Set("scala.main", "scala.annotation.newMain", "scala.annotation.main")
      val isMainAnnotated = sym.annotations.exists(a => mainFqns.contains(annoFqn(a)))
      if !isMainAnnotated then return

      dd.rhs match
        case Some(body) =>
          line("void main() {")
          indent += 1
          emitBodyAsStatements(body, returnLast = false)
          indent -= 1
          line("}")
          blank()
        case None => ()

    private def emitTopLevelVal(vd: ValDef): Unit = ()

    // ── Body emission ────────────────────────────────────────────────────

    /** Emit a tree as a sequence of Dart statements. When `returnLast` is
     *  true, the final expression is prefixed with `return`.
     */
    private def emitBodyAsStatements(t: Tree, returnLast: Boolean): Unit = t match
      case Block(stats, expr) =>
        stats.foreach(emitStmt)
        emitTerminal(expr, returnLast)
      case tryTree: Try =>
        emitTryStatement(tryTree, returnLast)
      case other: Term =>
        emitTerminal(other, returnLast)
      case other =>
        line(s"/* TODO body ${other.getClass.getSimpleName} */")

    /** Emit `try { … } on E catch (e) { … } finally { … }` as a Dart
     *  statement. Each catch-clause body is itself dispatched back through
     *  `emitBodyAsStatements`, so `return` still lands correctly when this
     *  Try is the tail of a non-Unit method.
     */
    private def emitTryStatement(t: Try, returnLast: Boolean): Unit =
      line("try {")
      indent += 1
      emitBodyAsStatements(t.body, returnLast)
      indent -= 1

      for c <- t.cases do
        val header = c.pattern match
          // `case _: E => …`                 → `on E { … }`
          case Typed(Ident("_"), tpt) =>
            s"} on ${emitTypeRef(tpt.tpe)} {"
          // `case e: E => …`                 → `on E catch (e) { … }`
          case Bind(name, Typed(Ident("_"), tpt)) =>
            s"} on ${emitTypeRef(tpt.tpe)} catch ($name) {"
          // `case e => …` (type inferred)   → `catch (e) { … }`
          case Bind(name, Ident("_")) =>
            s"} catch ($name) {"
          case Ident("_") =>
            s"} catch (_) {"
          case _ =>
            s"} catch (_) { /* TODO complex catch pattern */"
        line(header)
        indent += 1
        emitBodyAsStatements(c.rhs, returnLast)
        indent -= 1

      t.finalizer match
        case Some(body) =>
          line("} finally {")
          indent += 1
          emitBodyAsStatements(body, returnLast = false)
          indent -= 1
          line("}")
        case None =>
          line("}")

    private def emitTerminal(t: Tree, returnLast: Boolean): Unit = t match
      case Literal(c) if c.value == () =>
        () // nothing to emit; a Unit-valued body trails off
      case term: Term =>
        if returnLast then line(s"return ${emitExpr(term)};")
        else line(s"${emitExpr(term)};")
      case _ =>
        line(s"/* TODO terminal ${t.getClass.getSimpleName} */")

    private def emitStmt(t: Tree): Unit = t match
      case vd: ValDef =>
        val prefix = if vd.symbol.flags.is(Flags.Mutable) then "" else "final "
        val init = vd.rhs.map(r => s" = ${emitExpr(r)}").getOrElse("")
        line(s"$prefix${emitTypeRef(vd.tpt.tpe)} ${vd.name}$init;")
      case Assign(lhs, rhs) =>
        line(s"${emitExpr(lhs)} = ${emitExpr(rhs)};")
      case tryTree: Try =>
        emitTryStatement(tryTree, returnLast = false)
      case term: Term =>
        line(s"${emitExpr(term)};")
      case _: DefDef =>
        // Nested defs (e.g. lambda-lifted) shouldn't appear at statement
        // position in the subset we support.
        line(s"/* TODO nested def */")
      case _ =>
        line(s"/* TODO stmt ${t.getClass.getSimpleName} */")

    // ── Expressions ──────────────────────────────────────────────────────

    private def emitExpr(t: Term): String = t match
      case Literal(c) => emitConstant(c)
      // Hand-ported stdlib singletons — must precede the generic `Ident` /
      // `Select` fallbacks or those would swallow the reference.
      case t if isSartRef(t, "sart.stdlib.None") => "null"
      case Ident(name) => name
      case This(_) => "this"

      // Scala's Predef auto-inserts implicit wrappers (`augmentString(s)`,
      // `intWrapper(n)`, etc.) so its stdlib-style methods/operators are
      // reachable. Dart's native `String`/`int`/`double` provide equivalent
      // operators directly, so we strip the wrapper and emit just the
      // underlying argument. This case has to run before the generic
      // `Apply(Select(qual, name), args)` branch would otherwise emit
      // `Predef.augmentString(s)` literally.
      case Apply(fn, List(arg)) if isScalaImplicitWrapper(fn) =>
        emitExpr(arg)
      case Apply(TypeApply(fn, _), List(arg)) if isScalaImplicitWrapper(fn) =>
        emitExpr(arg)

      // s"..." → Dart single-quoted string with $x / ${e} interpolation.
      // The qualifier of `.s(args*)` is a StringContext construction; we
      // accept several tree shapes the compiler may produce.
      case Apply(Select(qual, "s"), args) if stringContextParts(qual).nonEmpty =>
        val parts = stringContextParts(qual)
        val actualArgs = args match
          case List(Typed(Repeated(items, _), _)) => items
          case List(Repeated(items, _))           => items
          case other                              => other
        emitInterpolationParts(parts, actualArgs)

      // List(a, b, ...) → [a, b, ...]
      case Apply(TypeApply(Select(Ident("List"), "apply"), _), List(Typed(Repeated(items, _), _))) =>
        items.map(emitExpr).mkString("[", ", ", "]")
      case Apply(Select(Ident("List"), "apply"), List(Typed(Repeated(items, _), _))) =>
        items.map(emitExpr).mkString("[", ", ", "]")

      // `new Foo(args)` → `Foo(args)`. For facade classes (@native) we keep
      // Scala named args as Dart named args (Dart constructor is named-form).
      // For user classes we strip names — the emitted Dart ctor is positional.
      case Apply(Select(New(tpt), _), args) =>
        recordAnnotations(tpt.tpe.typeSymbol)
        val ctorName = dartName(tpt.tpe.typeSymbol)
        val argStr = if hasNative(tpt.tpe.typeSymbol) then emitArgs(args) else emitPositionalArgs(args)
        s"$ctorName($argStr)"
      case Apply(TypeApply(Select(New(tpt), _), _), args) =>
        recordAnnotations(tpt.tpe.typeSymbol)
        val ctorName = dartName(tpt.tpe.typeSymbol)
        val argStr = if hasNative(tpt.tpe.typeSymbol) then emitArgs(args) else emitPositionalArgs(args)
        s"$ctorName($argStr)"

      // `sart.stdlib.Some(x)` → just `x` — Dart promotes the non-null value
      // into the nullable type automatically.
      case Apply(Select(qual, "apply"), args) if isSartRef(qual, "sart.stdlib.Some") =>
        args.headOption.map(emitExpr).getOrElse("null")
      case Apply(TypeApply(Select(qual, "apply"), _), args) if isSartRef(qual, "sart.stdlib.Some") =>
        args.headOption.map(emitExpr).getOrElse("null")

      // (`sart.stdlib.None` is handled at the top of `emitExpr` — before
      //  the generic `Ident` fallback — so a bare `None` reference lands
      //  as `null`.)

      // Closure: Block(List(DefDef), Closure) — zero-arg `() => expr` or
      // `() => { stmts; expr }`.
      case Block(List(dd: DefDef), _: Closure) =>
        emitClosure(dd)

      // A Block with no statements is just a wrapper around the trailing
      // expression — pass through. Scala 3 compiles `case x => 0` into
      // `Block(Nil, Literal(0))` for tree uniformity, so this unwrap is
      // what makes pattern-match arms land as clean Dart expressions.
      case Block(Nil, expr) =>
        emitExpr(expr)

      // Block with actual statements in expression position — Dart has no
      // block-expression. Leave a loud TODO.
      case Block(stats, expr) =>
        s"/* TODO block-expr (${stats.size} stmts) */"

      // Binary operator: `a + b`, `a == b`, etc.
      case Apply(Select(lhs, op), List(rhs)) if isBinaryOp(op) =>
        s"${emitExpr(lhs)} ${op} ${emitExpr(rhs)}"

      // `runApp.apply(arg)` — the `@native` singleton pattern for top-level
      // Dart functions. Emit as a bare call.
      case Apply(Select(idQual, "apply"), args) if isNativeSingleton(idQual) =>
        val fn = dartName(idQual.tpe.termSymbol)
        recordAnnotations(idQual.tpe.termSymbol)
        s"$fn(${emitArgs(args)})"

      // Normal call: `obj.method(args)` or `Ident(method)(args)` for local calls.
      case Apply(Select(qual, name), args) =>
        recordAnnotations(qual.tpe.typeSymbol)
        s"${selectPrefix(qual)}${name}(${emitArgs(args)})"
      case Apply(fn, args) =>
        s"${emitExpr(fn)}(${emitArgs(args)})"

      // Field / method ref (no parens): `widget.title`, `Colors.deepPurple`.
      case Select(qual, name) =>
        recordAnnotations(qual.tpe.typeSymbol)
        recordAnnotations(t.tpe.typeSymbol)
        // Singleton object references: `Theme` / `Colors` etc. The qual is
        // an Ident to the companion; we don't want `Theme$.foo`.
        s"${selectPrefix(qual)}$name"

      // Assignment as an expression (Dart allows this). Also handles the
      // case where a method body is a bare `x = y` — `emitBodyAsStatements`
      // routes non-Block terms through `emitExpr` via `emitTerminal`.
      case Assign(lhs, rhs) =>
        s"${emitExpr(lhs)} = ${emitExpr(rhs)}"

      // `if cond then t else e` → Dart ternary. Good enough when the if is
      // at expression position; statement-level if/else would want a block
      // shape, which we'll add when a fixture hits it.
      case If(cond, thenp, elsep) =>
        s"${emitExpr(cond)} ? ${emitExpr(thenp)} : ${emitExpr(elsep)}"

      // `scrutinee match { case p => rhs; … }` → Dart 3 switch expression.
      // Emitted on a single line; `dart format` reformats to multi-line.
      case Match(scrutinee, cases) =>
        val arms = cases.map { c =>
          val pat   = emitPattern(c.pattern)
          val guard = c.guard.map(g => s" when ${emitExpr(g)}").getOrElse("")
          val rhs   = emitExpr(c.rhs)
          s"$pat$guard => $rhs"
        }.mkString(", ")
        s"switch (${emitExpr(scrutinee)}) { $arms }"

      case Typed(expr, _) =>
        emitExpr(expr)

      case Inlined(_, _, expansion) =>
        emitExpr(expansion)

      case other =>
        s"/* TODO expr ${other.getClass.getSimpleName} */"

    private def isNativeSingleton(t: Term): Boolean =
      val sym = t.tpe.termSymbol
      sym.exists && hasNative(sym)

    /** Match a term that resolves to a specific fully-qualified Scala name,
     *  used for hand-ported stdlib special-cases (`sart.stdlib.Some`,
     *  `sart.stdlib.None`, etc.).
     */
    private def isSartRef(t: Term, fqn: String): Boolean =
      val sym = t match
        case id: Ident  => id.symbol
        case s: Select  => s.symbol
        case _          => Symbol.spliceOwner   // a dummy non-matching symbol
      sym.exists && sym.fullName == fqn

    /** Scala 3 inserts Predef-side implicit wrappers (`augmentString(s)`,
     *  `intWrapper(n)`, etc.) so `StringOps` / `RichInt` methods and
     *  operators are reachable on primitives. Dart's native `String`/`int`
     *  /`double` already provide those operators, so we strip the wrapper.
     *
     *  Matching by **simple name** rather than FQN because these methods
     *  are inherited through several `LowPriorityImplicits` parents and
     *  their FQN varies across Scala versions; the simple names are stable
     *  and unlikely to clash with user code.
     */
    private val scalaImplicitWrapperSimples = Set(
      "augmentString", "unaugmentString",
      "intWrapper", "longWrapper", "floatWrapper", "doubleWrapper",
      "charWrapper", "byteWrapper", "shortWrapper", "booleanWrapper",
      "wrapRefArray", "wrapIntArray", "wrapDoubleArray", "wrapLongArray",
      "wrapFloatArray", "wrapCharArray", "wrapByteArray", "wrapShortArray",
      "wrapBooleanArray", "wrapUnitArray", "genericWrapArray",
      "refArrayOps"
    )

    private def isScalaImplicitWrapper(t: Term): Boolean =
      val sym = t match
        case id: Ident           => id.symbol
        case s: Select           => s.symbol
        case TypeApply(inner, _) => inner match
          case id: Ident => id.symbol
          case s: Select => s.symbol
          case _         => Symbol.spliceOwner
        case _ => Symbol.spliceOwner
      sym.exists
        && scalaImplicitWrapperSimples(sym.name)
        && sym.fullName.startsWith("scala.")

    /** Produce the `"<qual>."` prefix for a member access, or `""` when the
     *  qualifier is `this` (Dart makes `this.` optional everywhere except a
     *  constructor initializer list, which we never emit via this path).
     *
     *  A more cautious version would preserve `this.` when a local variable
     *  in scope shadows the field; for the current subset we have no
     *  shadowing, so unconditional elision is safe.
     */
    private def selectPrefix(qual: Term): String = qual match
      case This(_) => ""
      case _       => s"${emitExpr(qual)}."

    private def isBinaryOp(op: String): Boolean =
      Set("+", "-", "*", "/", "%", "==", "!=", "<", ">", "<=", ">=", "&&", "||").contains(op)

    /** Drop references to Scala's synthesised default-argument methods
     *  (e.g. `Text.$lessinit$greater$default$2`). Dart named args with
     *  defaults simply go unmentioned at the call site.
     */
    private def isDefaultArg(t: Term): Boolean = t match
      case s: Select if s.name.contains("$default$") => true
      case Ident(n) if n.contains("$default$") => true
      case Apply(inner, _) => isDefaultArg(inner)
      case TypeApply(inner, _) => isDefaultArg(inner)
      case NamedArg(_, inner) => isDefaultArg(inner)
      case _ => false

    private def emitArgs(args: List[Term]): String =
      args.filterNot(isDefaultArg).map {
        case NamedArg(name, value) => s"$name: ${emitExpr(value)}"
        case other => emitExpr(other)
      }.mkString(", ")

    /** Variant of `emitArgs` that drops any `NamedArg` wrapper, emitting
     *  every argument positionally. Used when the target has a positional
     *  Dart constructor (user classes) but the Scala source passed values
     *  using named-argument syntax.
     */
    private def emitPositionalArgs(args: List[Term]): String =
      args.filterNot(isDefaultArg).map {
        case NamedArg(_, value) => emitExpr(value)
        case other              => emitExpr(other)
      }.mkString(", ")

    private def emitConstant(c: Constant): String = c.value match
      case s: String  => "'" + escapeDartString(s) + "'"
      case b: Boolean => b.toString
      case n: Int     => n.toString
      case n: Long    => n.toString
      case n: Double  => n.toString
      case n: Float   => n.toString
      case ()         => "null"
      case null       => "null"
      case other      => s"/* TODO const $other */"

    private def escapeDartString(s: String): String =
      s.flatMap {
        case '\\' => "\\\\"
        case '\'' => "\\'"
        case '\n' => "\\n"
        case '\r' => "\\r"
        case '\t' => "\\t"
        case '$'  => "\\$"
        case c    => c.toString
      }

    /** Translate a Scala match-pattern tree to a Dart 3 pattern arm.
     *
     *  Supported:
     *    - `case 0 => …`                →  `0 => …`
     *    - `case "foo" => …`            →  `'foo' => …`
     *    - `case _ => …`                →  `_ => …`
     *    - `case x => …`                →  `var x => …`  (wildcard bind)
     *    - `case _: Foo => …`           →  `Foo _ => …`  (type match, no bind)
     *    - `case x: Foo => …`           →  `Foo x => …`  (type match, bind)
     *    - `case Ident` referring to an enum case / singleton → name as-is.
     *
     *  Defers: constructor patterns on case classes (`case Point(x, y)`)
     *  and alternatives (`case 1 | 2`). Those get TODO markers.
     */
    private def emitPattern(p: Tree): String = p match
      case Literal(c)                               => emitConstant(c)
      case Ident("_")                               => "_"
      case Bind(name, Ident("_"))                   => s"var $name"
      case Typed(Ident("_"), tpt)                   => s"${emitTypeRef(tpt.tpe)} _"
      case Bind(name, Typed(Ident("_"), tpt))       => s"${emitTypeRef(tpt.tpe)} $name"
      // `case Filter.All` or `case Foo` — a stable reference (enum case,
      // singleton). Dart treats it as a constant pattern when wrapped in
      // `const`; for enum cases a bare reference works.
      case s: Select => emitExpr(s)
      case Ident(n)  => n
      case _         => s"/* TODO pattern ${p.getClass.getSimpleName} */"

    /** Strip `Inlined(...)` wrappers the compiler sometimes adds. */
    private def unwrap(t: Term): Term = t match
      case Inlined(_, _, e) => unwrap(e)
      case _ => t

    private def isStringContextRef(t: Term): Boolean = unwrap(t) match
      case Ident("StringContext") => true
      case Select(_, "StringContext") => true
      case _ => false

    /** Attempt to recognise a `StringContext(parts...)` construction at any
     *  of the shapes the compiler may produce and return the constant string
     *  parts. Empty list means "not a StringContext construction."
     */
    private def stringContextParts(t: Term): List[String] =
      unwrap(t) match
        case Apply(Select(ref, "apply"), argList) if isStringContextRef(ref) =>
          val partsTerms = argList match
            case List(Typed(Repeated(ps, _), _)) => ps
            case List(Repeated(ps, _))           => ps
            case ps                              => ps
          partsTerms.flatMap(p => litValue(p).collect { case s: String => s })
        case Apply(TypeApply(Select(ref, "apply"), _), argList) if isStringContextRef(ref) =>
          val partsTerms = argList match
            case List(Typed(Repeated(ps, _), _)) => ps
            case List(Repeated(ps, _))           => ps
            case ps                              => ps
          partsTerms.flatMap(p => litValue(p).collect { case s: String => s })
        case _ => Nil

    /** Render `'prefix $x middle ${expr} suffix'` given the string parts and
     *  the interpolation argument expressions.
     */
    private def emitInterpolationParts(parts: List[String], args: List[Term]): String =
      val b = new StringBuilder("'")
      val partsIter = parts.iterator
      val argsIter  = args.iterator
      if partsIter.hasNext then b.append(escapeDartString(partsIter.next()))
      while argsIter.hasNext do
        val a = argsIter.next()
        a match
          case Ident(n) => b.append("$").append(n)
          case Select(This(_), n) => b.append("$").append(n)
          case other => b.append("${").append(emitExpr(other)).append('}')
        if partsIter.hasNext then b.append(escapeDartString(partsIter.next()))
      b.append('\'')
      b.toString

    /** Emit the body of a lifted anonymous function as a Dart arrow or block
     *  expression. DefDef's `rhs` is the lambda body.
     */
    private def emitClosure(dd: DefDef): String =
      val params = dd.paramss.flatMap(_.params).collect { case vd: ValDef => vd }
      val paramStr = params.map(p => p.name).mkString(", ")
      dd.rhs match
        case Some(body) =>
          body match
            case Block(stats, expr) =>
              val sb = new StringBuilder(s"($paramStr) { ")
              stats.foreach { s =>
                sb.append(stmtInline(s))
                sb.append(' ')
              }
              expr match
                case Literal(c) if c.value == () => ()
                case term: Term => sb.append(emitExpr(term)).append("; ")
                case _ => ()
              sb.append("}")
              sb.toString
            case Assign(lhs, rhs) =>
              s"($paramStr) { ${emitExpr(lhs)} = ${emitExpr(rhs)}; }"
            case term: Term =>
              s"($paramStr) => ${emitExpr(term)}"
        case None => s"($paramStr) => null"

    private def stmtInline(t: Tree): String = t match
      case Assign(lhs, rhs) => s"${emitExpr(lhs)} = ${emitExpr(rhs)};"
      case term: Term       => s"${emitExpr(term)};"
      case _                => s"/* TODO stmt-inline */"

    // ── Type references ──────────────────────────────────────────────────

    private def emitTypeRef(tpe: TypeRepr): String =
      val sym = tpe.typeSymbol
      recordAnnotations(sym)

      // Hand-ported stdlib types with custom Dart representations — these
      // need to bypass the standard `base<T, U>` template because they
      // format differently (e.g. `Option[T]` → `T?`, not `Option<T>`).
      sym.fullName match
        case "sart.stdlib.Option" =>
          return tpe match
            case AppliedType(_, List(arg: TypeRepr)) => s"${emitTypeRef(arg)}?"
            case _                                   => "Object?"
        case _ =>

      val base = sym.fullName match
        case "scala.Int"     => "int"
        case "scala.Long"    => "int"
        case "scala.Double"  => "double"
        case "scala.Float"   => "double"
        case "scala.Boolean" => "bool"
        case "scala.Unit"    => "void"
        case "scala.Any" | "scala.AnyRef" | "java.lang.Object" => "Object"
        case "scala.AnyVal"  => "Object"
        case "scala.Nothing" => "Never"
        case "java.lang.String" | "scala.Predef.String" => "String"
        case _ => dartName(sym)

      // Render type arguments for `State[MyHomePage]` etc.
      tpe match
        case AppliedType(_, args) if args.nonEmpty =>
          val argStr = args.map {
            case t: TypeRepr => emitTypeRef(t)
          }.mkString("<", ", ", ">")
          base + argStr
        case _ =>
          base
