package sart.compiler

import scala.tasty.inspector.{Inspector, Tasty}
import scala.quoted.Quotes
import scala.collection.mutable
import java.nio.file.{Files, Path}
import java.nio.charset.StandardCharsets

/** The Sart Dart emitter.
 *
 *  **Stability**: internal. Integrators should invoke `sart.compiler.Main`
 *  as a CLI (stable contract) rather than instantiating this class
 *  directly. Its constructor signature, member visibility, and internal
 *  `Pass` class are not stable across minor versions.
 *
 *  Internally: one pass over the incoming TASTy that simultaneously
 *  records annotations driving the import header / pubspec / shim
 *  selection, and writes Dart source into a `StringBuilder`.
 *
 *  Any tree shape the emitter doesn't recognise produces a `/* TODO … */`
 *  comment in the output. `sart.compiler.Main --strict` fails the build
 *  when any such comment is emitted.
 */
class DartEmitter(
  outDir: Path,
  sourceRoot: Option[Path] = None,
  projectName: String = "sart_example",
  projectDescription: String = "Scala-authored Flutter app, compiled via Sart."
) extends Inspector:

  // ── State collected across inspection runs ─────────────────────────────
  private val imports       = mutable.LinkedHashSet[String]()
  private val packages      = mutable.LinkedHashSet[DartPkg]()
  private val pubspecBlocks = mutable.LinkedHashSet[String]()
  private val shimsNeeded   = mutable.LinkedHashSet[DartShim]()
  private val bodyBuf       = new StringBuilder

  private case class DartPkg(name: String, version: String, sdk: String)

  /** A Dart-side helper library the emitter ships alongside `main.dart`
   *  so Scala stdlib method calls (e.g. `Option.map`) resolve in Dart.
   *  Each shim is written to `lib/<fileName>` and an `import 'fileName';`
   *  line is added to the emitted imports header.
   */
  private case class DartShim(fileName: String, content: String)

  private val optionShim = DartShim(
    "sart_option.dart",
    """// Generated by Sart — do not edit.
      |// Extension methods mirroring sart.stdlib.Option's Scala vocabulary
      |// on Dart nullable types.
      |
      |extension SartOption<T extends Object> on T? {
      |  R? map<R extends Object>(R Function(T) f) =>
      |    this == null ? null : f(this as T);
      |
      |  R? flatMap<R extends Object>(R? Function(T) f) =>
      |    this == null ? null : f(this as T);
      |
      |  R fold<R>(R ifEmpty, R Function(T) ifPresent) =>
      |    this == null ? ifEmpty : ifPresent(this as T);
      |
      |  void foreach(void Function(T) f) {
      |    if (this != null) f(this as T);
      |  }
      |}
      |""".stripMargin
  )

  private val tryShim = DartShim(
    "sart_try.dart",
    """// Generated by Sart — do not edit.
      |// Scala's Try as a sealed Dart hierarchy. Mirrors the facades in
      |// sart.stdlib.Try / Success / Failure.
      |
      |sealed class Try<T> {
      |  const Try();
      |
      |  Try<R> map<R>(R Function(T) f);
      |  Try<R> flatMap<R>(Try<R> Function(T) f);
      |  R fold<R>(R Function(Object) onFailure, R Function(T) onSuccess);
      |  T getOrElse(T fallback);
      |  bool get isSuccess;
      |  bool get isFailure;
      |}
      |
      |final class Success<T> extends Try<T> {
      |  final T value;
      |  const Success(this.value);
      |
      |  @override
      |  Try<R> map<R>(R Function(T) f) => Success<R>(f(value));
      |  @override
      |  Try<R> flatMap<R>(Try<R> Function(T) f) => f(value);
      |  @override
      |  R fold<R>(R Function(Object) onFailure, R Function(T) onSuccess) =>
      |      onSuccess(value);
      |  @override
      |  T getOrElse(T fallback) => value;
      |  @override
      |  bool get isSuccess => true;
      |  @override
      |  bool get isFailure => false;
      |}
      |
      |final class Failure<T> extends Try<T> {
      |  final Object error;
      |  const Failure(this.error);
      |
      |  @override
      |  Try<R> map<R>(R Function(T) f) => Failure<R>(error);
      |  @override
      |  Try<R> flatMap<R>(Try<R> Function(T) f) => Failure<R>(error);
      |  @override
      |  R fold<R>(R Function(Object) onFailure, R Function(T) onSuccess) =>
      |      onFailure(error);
      |  @override
      |  T getOrElse(T fallback) => fallback;
      |  @override
      |  bool get isSuccess => false;
      |  @override
      |  bool get isFailure => true;
      |}
      |""".stripMargin
  )

  private val eitherShim = DartShim(
    "sart_either.dart",
    """// Generated by Sart — do not edit.
      |// Right-biased Either as a sealed Dart hierarchy. Mirrors the
      |// facades in sart.stdlib.Either / Left / Right.
      |
      |sealed class Either<L, R> {
      |  const Either();
      |
      |  Either<L, R2> map<R2>(R2 Function(R) f);
      |  Either<L, R2> flatMap<R2>(Either<L, R2> Function(R) f);
      |  X fold<X>(X Function(L) onLeft, X Function(R) onRight);
      |  bool get isLeft;
      |  bool get isRight;
      |}
      |
      |final class Left<L, R> extends Either<L, R> {
      |  final L value;
      |  const Left(this.value);
      |
      |  @override
      |  Either<L, R2> map<R2>(R2 Function(R) f) => Left<L, R2>(value);
      |  @override
      |  Either<L, R2> flatMap<R2>(Either<L, R2> Function(R) f) =>
      |      Left<L, R2>(value);
      |  @override
      |  X fold<X>(X Function(L) onLeft, X Function(R) onRight) =>
      |      onLeft(value);
      |  @override
      |  bool get isLeft => true;
      |  @override
      |  bool get isRight => false;
      |}
      |
      |final class Right<L, R> extends Either<L, R> {
      |  final R value;
      |  const Right(this.value);
      |
      |  @override
      |  Either<L, R2> map<R2>(R2 Function(R) f) => Right<L, R2>(f(value));
      |  @override
      |  Either<L, R2> flatMap<R2>(Either<L, R2> Function(R) f) => f(value);
      |  @override
      |  X fold<X>(X Function(L) onLeft, X Function(R) onRight) =>
      |      onRight(value);
      |  @override
      |  bool get isLeft => false;
      |  @override
      |  bool get isRight => true;
      |}
      |""".stripMargin
  )

  // ── Inspector entry point ──────────────────────────────────────────────
  def inspect(using quotes: Quotes)(tastys: List[Tasty[quotes.type]]): Unit =
    val e = new Pass[quotes.type](
      bodyBuf, imports, packages, pubspecBlocks, shimsNeeded,
      optionShim, tryShim, eitherShim, sourceRoot
    )
    for tasty <- tastys do
      e.run(tasty.ast)

  // ── Output ─────────────────────────────────────────────────────────────
  def writeOutput(): Unit =
    val libDir = outDir.resolve("lib")
    Files.createDirectories(libDir)

    // Write every stdlib shim that was flagged as needed during emission.
    // The shim filename goes into the import header so user code resolves
    // against it without any manual setup.
    for shim <- shimsNeeded do
      Files.writeString(libDir.resolve(shim.fileName), shim.content, StandardCharsets.UTF_8)

    // All imports (including shim filenames) flow through the `imports`
    // set — sart.stdlib.Option adds its shim filename in emitTypeRef, and
    // facades like Try/Either add theirs via `@DartImport`. Emitting here
    // without deduplicating would double-import the shim filenames.
    val header = new StringBuilder
    for i <- imports.toList.sorted do
      header.append(s"import '$i';\n")
    if imports.nonEmpty then header.append('\n')

    val mainDart = header.toString + bodyBuf.toString
    Files.writeString(libDir.resolve("main.dart"), mainDart, StandardCharsets.UTF_8)

    val pubspec = renderPubspec()
    Files.writeString(outDir.resolve("pubspec.yaml"), pubspec, StandardCharsets.UTF_8)

  /** Lower-bound Dart SDK version the emitter targets. Single source of
   *  truth: drives the pubspec's `environment.sdk` constraint, and the
   *  format step extracts the major.minor from the written pubspec to
   *  pass as `dart format --language-version`. Bump this to roll forward
   *  to a newer Dart language version. */
  private val sdkFloor = "3.11.0"

  private def renderPubspec(): String =
    val b = new StringBuilder
    b.append("# Generated by Sart — do not edit by hand.\n")
    b.append(s"name: $projectName\n")
    b.append(s"description: $projectDescription\n")
    b.append("publish_to: 'none'\n")
    b.append("version: 0.1.0\n\n")
    b.append("environment:\n")
    b.append(s"  sdk: '>=$sdkFloor <4.0.0'\n\n")
    b.append("dependencies:\n")
    for p <- packages.toList.sortBy(_.name) do
      if p.sdk.nonEmpty then
        b.append(s"  ${p.name}:\n")
        b.append(s"    sdk: ${p.sdk}\n")
      else if p.version.nonEmpty then
        b.append(s"  ${p.name}: ${p.version}\n")
      else
        b.append(s"  ${p.name}: any\n")
    for block <- pubspecBlocks do
      val normalized = normalizePubspecBlock(block)
      if normalized.nonEmpty then
        b.append('\n')
        b.append(normalized)
        if !normalized.endsWith("\n") then b.append('\n')
    b.toString

  /** Produce a canonical indentation for a `@DartPubspec` block so a
   *  sloppily-written annotation (`"""` with surrounding blank lines or
   *  leading whitespace matching the source indentation) still lands in
   *  the pubspec as valid YAML.
   *
   *  Steps: drop leading/trailing blank lines, find the minimum indent of
   *  non-blank lines, strip that indent from every line.
   */
  private def normalizePubspecBlock(raw: String): String =
    val lines = raw.split('\n').toList
      .dropWhile(_.trim.isEmpty)
      .reverse.dropWhile(_.trim.isEmpty).reverse
    if lines.isEmpty then ""
    else
      val minIndent = lines
        .filter(_.trim.nonEmpty)
        .map(_.takeWhile(_ == ' ').length)
        .minOption
        .getOrElse(0)
      lines.map(l => if l.length >= minIndent then l.drop(minIndent) else l)
        .mkString("\n")

  // ── Per-run emitter, parameterized over Quotes ─────────────────────────
  //
  // Keeping everything inside a nested class means the reflect types stay
  // path-dependent on a stable `quotes` — we don't have to thread it through
  // every method signature by hand.
  private class Pass[Q <: Quotes & Singleton](
    out: StringBuilder,
    imports: mutable.LinkedHashSet[String],
    packages: mutable.LinkedHashSet[DartPkg],
    pubspecBlocks: mutable.LinkedHashSet[String],
    shimsNeeded: mutable.LinkedHashSet[DartShim],
    optionShim: DartShim,
    tryShim: DartShim,
    eitherShim: DartShim,
    sourceRoot: Option[Path]
  )(using val q: Q):
    import q.reflect.*

    private var indent = 0
    private def ind(): String = "  " * indent
    private def line(s: String): Unit = { out.append(ind()); out.append(s); out.append('\n') }
    private def blank(): Unit = out.append('\n')

    // ── Annotation helpers ───────────────────────────────────────────────

    private def annoFqn(a: Term): String = a.tpe.typeSymbol.fullName

    private def hasNative(sym: Symbol): Boolean =
      sym.annotations.exists(a => annoFqn(a) == "sart.dart.native")

    /** Unwrap a `Literal(Constant(...))` into its underlying value, whatever
     *  the concrete `Constant` subtype is.
     */
    private def litValue(t: Term): Option[Any] = t match
      case Literal(c) => Some(c.value)
      case _ => None

    /** Extract constant args (Strings/Ints/Booleans) from an annotation tree. */
    private def constArgs(a: Term): List[Any] =
      a match
        case Apply(_, args) =>
          args.flatMap {
            case t if litValue(t).isDefined => litValue(t).toList
            case NamedArg(_, t) if litValue(t).isDefined => litValue(t).toList
            case _ => Nil
          }
        case _ => Nil

    /** Named-arg lookup on an annotation (falls back to positional). */
    private def annoArg(a: Term, name: String, positional: Int): Option[Any] =
      a match
        case Apply(_, args) =>
          val named = args.collectFirst {
            case NamedArg(n, t) if n == name && litValue(t).isDefined => litValue(t).get
          }
          named.orElse {
            args.zipWithIndex.collectFirst {
              case (t, i) if i == positional && litValue(t).isDefined => litValue(t).get
            }
          }
        case _ => None

    private def recordAnnotations(sym: Symbol): Unit =
      for a <- sym.annotations do
        annoFqn(a) match
          case "sart.dart.DartImport" =>
            constArgs(a).collectFirst { case s: String => s }.foreach { path =>
              imports += path
              // If the @DartImport names a stdlib shim, register the shim
              // file for emission. The shim's own filename already lands
              // in `imports` so there's no double-import.
              path match
                case "sart_try.dart"    => shimsNeeded += tryShim
                case "sart_either.dart" => shimsNeeded += eitherShim
                case "sart_option.dart" => shimsNeeded += optionShim
                case _                  => ()
            }
          case "sart.dart.DartPackage" =>
            val name    = annoArg(a, "name",    0).collect { case s: String => s }.getOrElse("")
            val version = annoArg(a, "version", 1).collect { case s: String => s }.getOrElse("")
            val sdk     = annoArg(a, "sdk",     2).collect { case s: String => s }.getOrElse("")
            if name.nonEmpty then packages += DartPkg(name, version, sdk)
          case "sart.dart.DartPubspec" =>
            constArgs(a).collectFirst { case s: String => s }.foreach(pubspecBlocks += _)
          case _ =>

    /** Pull the emitted Dart name from `@DartName(...)` if present. */
    private def dartName(sym: Symbol): String =
      sym.annotations.collectFirst {
        case a if annoFqn(a) == "sart.dart.DartName" =>
          constArgs(a).collectFirst { case s: String => s }
      }.flatten.getOrElse(sym.name)

    // Dart reserved words that user-chosen Scala identifiers sometimes
    // collide with. We don't need the full keyword list — just the ones
    // that actually break code when used as identifiers.
    private val dartReserved = Set(
      "default", "class", "const", "enum", "extends", "false", "final",
      "null", "return", "super", "switch", "this", "true", "var",
      "void", "while", "with", "try", "throw", "is", "as", "in", "of",
      "new", "if", "else", "for", "do"
    )

    /** Rewrite Dart-keyword collisions for identifiers used in the emitted
     *  source (parameters, locals, field names). Adds a trailing underscore
     *  so the identifier is unambiguously Dart-valid while staying readable.
     */
    private def dartSafeName(name: String): String =
      if dartReserved(name) then s"${name}_" else name

    // ── Top-level driver ─────────────────────────────────────────────────

    def run(tree: Tree): Unit = tree match
      case p: PackageClause =>
        p.stats.foreach(runTop)
      case other =>
        runTop(other)

    private def runTop(t: Tree): Unit = t match
      case _: Import =>
        () // Scala imports are irrelevant; we emit our own Dart imports
      case p: PackageClause =>
        p.stats.foreach(runTop)
      case cd: ClassDef =>
        val sym = cd.symbol
        val name = sym.name
        if hasNative(sym) then
          recordAnnotations(sym)
        else if name.endsWith("$package$") || name.endsWith("$package") then
          // Scala 3 stores top-level defs inside a synthetic package class;
          // descend and treat its stats as top-level trees.
          cd.body.foreach(runTop)
        else if isMainWrapper(cd) then
          () // `@main def foo` generates a wrapper class we don't want to emit.
        else if sym.flags.is(Flags.Enum) && !sym.flags.is(Flags.Case) then
          // The enum parent class (`enum Filter { case All, … }` produces
          // a sealed `class Filter extends scala.reflect.Enum`). Skip —
          // we emit the Dart enum from the companion object below instead.
          ()
        else if name.endsWith("$") then
          // A module class. Interesting varieties:
          //   - enum companion                     → emit the Dart enum
          //   - `case object Foo` module           → emit `class Foo {}`
          //   - given-value module with impl body  → emit as concrete class
          //   - plain case-class / other companion → skip
          val companion = sym.companionClass
          if companion.exists && companion.flags.is(Flags.Enum) then
            emitEnumFromCompanion(cd, companion)
          else if sym.flags.is(Flags.Case) then
            emitCaseObject(cd)
          else if hasUserDefinedBody(cd) then
            // A `$`-class with user-written methods: typically the synthesised
            // module for `given X: T with { … }`. Emit as a concrete class so
            // the corresponding `val X = X$()` resolves.
            emitClassDef(cd)
          // Plain companions (case-class `$`, etc.) — skip.
        else if name.contains("$") || sym.flags.is(Flags.Synthetic) then
          () // Synthetic/anonymous classes — skip.
        else
          emitClassDef(cd)
      case dd: DefDef =>
        if dd.symbol.flags.is(Flags.ExtensionMethod) then emitExtensionMethod(dd)
        else emitTopLevelDef(dd)
      case vd: ValDef =>
        emitTopLevelVal(vd)
      case _ =>
        line(s"/* TODO top-level: ${t.getClass.getSimpleName} */")

    /** Emit a Dart class for a Scala `case object`. The module class has
     *  the form `FooName$` in TASTy; we strip the trailing `$` for the
     *  Dart name. For now the emission is an empty class (no singleton
     *  value-level support); references to the object as a value will
     *  need follow-up work to translate as `FooName()` or a const instance.
     */
    private def emitCaseObject(cd: ClassDef): Unit =
      val objName = cd.symbol.name.stripSuffix("$")
      val parentTpt = realParent(cd)
      val ext = parentTpt.map(t => s" extends ${emitTypeRef(t.tpe)}").getOrElse("")
      emitSourceAttribution(cd.symbol)
      line(s"class $objName$ext {}")
      blank()

    /** Emit a Dart enum from the companion module of a Scala 3 enum class.
     *
     *  Simple enum cases (no parameters) are stored as `val` members of the
     *  companion, each typed as the enum class itself. For these we emit
     *  `enum Name { A, B, C }`.
     *
     *  Parameterised cases (e.g. `case Foo(x: Int)`) appear as their own
     *  subclass `ClassDef`s elsewhere in the tree; this helper leaves a
     *  TODO marker for that path — sealed-hierarchy emission (task 15)
     *  will handle it.
     */
    private def emitEnumFromCompanion(companionCd: ClassDef, enumCls: Symbol): Unit =
      val caseVals = companionCd.body.collect {
        case vd: ValDef
            if !vd.symbol.flags.is(Flags.Synthetic)
            && vd.tpt.tpe.typeSymbol == enumCls =>
          vd
      }
      if caseVals.nonEmpty then
        val names = caseVals.map(_.name).mkString(", ")
        emitSourceAttribution(enumCls)
        line(s"enum ${enumCls.name} { $names }")
        blank()
      else
        line(s"/* TODO: parameterised enum ${enumCls.name} — cases are subclasses */")
        blank()

    /** Emit a `/// Source: <path>:<line>` dartdoc comment for the given
     *  symbol's source position. No-op when the symbol has no tracked
     *  position (e.g. synthetic classes we do still emit).
     *
     *  Path relativisation: if a `sourceRoot` was passed to the emitter
     *  (typically the sbt base directory) and the source file lives under
     *  it, we emit `<rel-path>:<line>`. Otherwise the absolute path goes
     *  through — verbose but never misleading.
     */
    private def emitSourceAttribution(sym: Symbol): Unit =
      val pos = sym.pos
      if pos.isEmpty then return
      // The compiler stores source-file paths relative to whatever dir
      // it was invoked from. Resolve a relative path against sourceRoot
      // (the sbt baseDirectory), not the JVM cwd which happens to be
      // the compiler module's dir.
      val raw = pos.get.sourceFile.getJPath
      val sourcePath = raw.map { p =>
        if p.isAbsolute then p
        else sourceRoot.getOrElse(java.nio.file.Paths.get(".").toAbsolutePath).resolve(p).normalize
      }
      sourcePath.foreach { sp =>
        val displayed = sourceRoot match
          case Some(root) if sp.startsWith(root) => root.relativize(sp).toString
          case _                                 => sp.toString
        line(s"/// Source: $displayed:${pos.get.startLine + 1}")
      }

    /** Does this class body carry a user-written (non-synthetic,
     *  non-`<init>`) method? We use this to distinguish `given X: T with
     *  { … }` modules (which have user methods to carry into Dart) from
     *  plain case-class/object companions (which only have synthetic
     *  `apply`/`unapply`/etc.).
     */
    private def hasUserDefinedBody(cd: ClassDef): Boolean =
      cd.body.exists {
        case dd: DefDef =>
          !dd.symbol.flags.is(Flags.Synthetic) && dd.symbol.name != "<init>"
        case _ => false
      }

    /** Recognise the `@main def foo` wrapper class Scala 3 synthesises.
     *  Heuristic: the class contains a `main(args: Array[String])` method.
     *  The synthesised main may or may not be flagged `Synthetic` across
     *  Scala 3 minor versions, so we check the method signature directly.
     */
    private def isMainWrapper(cd: ClassDef): Boolean =
      cd.body.exists {
        case dd: DefDef if dd.symbol.name == "main" =>
          val ps = dd.paramss.flatMap(_.params).collect { case vd: ValDef => vd }
          ps match
            case List(vd) => vd.tpt.tpe.typeSymbol.fullName == "scala.Array"
            case _        => false
        case _ => false
      }

    // ── Classes ──────────────────────────────────────────────────────────

    // Scala auto-parents (roots, case-class/serializable markers) we never
    // carry into Dart. Matching both fully-qualified and simple names
    // because `Serializable` can resolve as `scala.` or `java.io.` depending
    // on alias path.
    private val skippedParentFqns = Set(
      "java.lang.Object", "scala.Any", "sart.dart.DartObject",
      "scala.Product", "scala.Serializable", "scala.Equals",
      "java.io.Serializable"
    )
    private val skippedParentSimples = Set("Product", "Serializable", "Equals")

    /** Walk tree shapes like `Apply(TypeApply(Select(New(tt), "<init>"),
     *  tpArgs), valArgs)` to the underlying parent `TypeTree`.
     */
    private def findParentType(t: Tree): Option[TypeTree] = t match
      case tt: TypeTree        => Some(tt)
      case New(tt: TypeTree)   => Some(tt)
      case Apply(inner, _)     => findParentType(inner)
      case TypeApply(inner, _) => findParentType(inner)
      case Select(inner, _)    => findParentType(inner)
      case _                   => None

    /** First "real" parent type from a ClassDef's parent list (i.e. dropping
     *  scala.Any / Object / DartObject / case-class markers).
     */
    private def realParent(cd: ClassDef): Option[TypeTree] =
      cd.parents.flatMap(findParentType).find { tt =>
        val s = tt.tpe.typeSymbol
        !skippedParentFqns(s.fullName) && !skippedParentSimples(s.name)
      }

    private def emitClassDef(cd: ClassDef): Unit =
      val sym = cd.symbol
      if hasNative(sym) then
        recordAnnotations(sym)
        return

      // `runTop` already filters by name (skips $-ending companions unless
      // they're enum, case-object, or have a user-defined body) and
      // synthetic classes, so here we only guard against stray inner
      // synthesised helpers that somehow reached emitClassDef.
      val rawName = sym.name
      if sym.flags.is(Flags.Synthetic) then return
      val className = rawName

      val parentTpt = realParent(cd)
      val extendsClause = parentTpt.map(tt => s" extends ${emitTypeRef(tt.tpe)}").getOrElse("")

      // Primary-constructor parameters become `final` fields in Dart, plus
      // a named constructor of the form `ClassName({required this.field});`.
      val ctor = cd.constructor
      val ctorParams: List[ValDef] = ctor.paramss.flatMap(_.params).collect { case vd: ValDef => vd }
      val typeParams: String = typeParamSig(ctor)

      // Member stats (val/var/def/override def); the primary-ctor body is
      // in `cd.body`, separate from the constructor params.
      val memberStats = cd.body.collect {
        case vd: ValDef => vd
        case dd: DefDef => dd
      }.filterNot { stat =>
        // Drop compiler-synthesised accessors for ctor params; we emit the
        // fields ourselves.
        stat.symbol.flags.is(Flags.ParamAccessor) ||
        stat.symbol.flags.is(Flags.Synthetic) ||
        stat.symbol.name == "<init>"
      }

      // Sealed parents (`sealed trait Shape`) legitimately have empty
      // bodies, so we no longer short-circuit on emptiness here — the
      // `@main` wrapper we used to catch via this rule is now caught by
      // `isMainWrapper` upstream. Scala traits and abstract classes both
      // map to Dart `abstract class` — Dart has no trait-specific keyword.
      val prefix =
        if sym.flags.is(Flags.Sealed) then "sealed "
        else if sym.flags.is(Flags.Trait) || sym.flags.is(Flags.Abstract) then "abstract "
        else ""

      emitSourceAttribution(sym)
      line(s"${prefix}class $className$typeParams$extendsClause {")
      indent += 1

      for p <- ctorParams do
        line(s"final ${emitTypeRef(p.tpt.tpe)} ${p.name};")

      // User classes get a **positional** primary constructor (matching how
      // Scala call sites actually invoke them). Named args in Scala source
      // compile to the same `Apply`, so when we emit the call we strip the
      // `NamedArg` wrapper for user-class constructions. Facade classes are
      // different — they use Dart-native named parameters and are handled
      // via the @native annotation path (no Dart ctor is ever emitted for
      // them; the user writes `Widget(title = …)` and the emitter keeps the
      // name because the facade's actual Dart class uses named params).
      if ctorParams.nonEmpty then
        val paramList = ctorParams.map(p => s"this.${p.name}").mkString(", ")
        line(s"$className($paramList);")
        blank()

      for stat <- memberStats do
        stat match
          case vd: ValDef => emitField(vd)
          case dd: DefDef => emitMethod(dd)

      if sym.flags.is(Flags.Case) && ctorParams.nonEmpty then
        emitCaseClassSynths(className, ctorParams)

      indent -= 1
      line("}")
      blank()

    /** Emit the Dart equivalents of a Scala case class's auto-generated
     *  members: `==`, `hashCode`, `toString`, `copyWith`. Scala's synthesised
     *  versions (`equals`, `canEqual`, etc.) are `Synthetic` so they're
     *  filtered out above and we write our own instead.
     *
     *  Nullability caveat: `copyWith({T? field})` with `field ?? this.field`
     *  can't distinguish "not provided" from "provided null" for nullable
     *  fields. Good enough while case-class fields are non-nullable; when
     *  `Option[T]` → `T?` lands (Phase 2), swap in a sentinel.
     */
    private def emitCaseClassSynths(className: String, params: List[ValDef]): Unit =
      val names = params.map(_.name)
      val types = params.map(p => emitTypeRef(p.tpt.tpe))

      // ==  (the constructor above already emitted a trailing blank line).
      line("@override")
      line("bool operator ==(Object other) =>")
      indent += 1
      val eqCheck = names.map(n => s"other.$n == $n").mkString(" && ")
      line(s"identical(this, other) ||")
      line(s"other is $className && $eqCheck;")
      indent -= 1
      blank()

      // hashCode
      line("@override")
      if names.size == 1 then
        line(s"int get hashCode => ${names.head}.hashCode;")
      else
        line(s"int get hashCode => Object.hash(${names.mkString(", ")});")
      blank()

      // toString — each `$$name` in Scala source becomes `$name` in the
      // emitted Dart, which Dart then interpolates at runtime.
      line("@override")
      val tsParts = names.map(n => s"$n: $$$n").mkString(", ")
      line(s"String toString() => '$className($tsParts)';")
      blank()

      // copyWith — method's own parameters are named (Dart convention for
      // `copyWith`), but the body's constructor call is positional to
      // match the class's positional primary ctor.
      val cwParams = names.zip(types).map { case (n, t) => s"$t? $n" }.mkString(", ")
      val cwArgs   = names.map(n => s"$n ?? this.$n").mkString(", ")
      line(s"$className copyWith({$cwParams}) =>")
      indent += 1
      line(s"$className($cwArgs);")
      indent -= 1

    private def emitField(vd: ValDef): Unit =
      val isMutable = vd.symbol.flags.is(Flags.Mutable)
      val prefix = if isMutable then "" else "final "
      val baseTpe = emitTypeRef(vd.tpt.tpe)
      // Null-initialised fields: Dart's sound null safety rejects
      // `Foo x = null`, so add a `?` to the type when the RHS is a
      // literal null (or omitted on a mutable field, which Dart would
      // also treat as null-default).
      val tpe = vd.rhs match
        case Some(Literal(c)) if c.value == null      => if baseTpe.endsWith("?") then baseTpe else baseTpe + "?"
        case None if isMutable && !baseTpe.endsWith("?") => baseTpe + "?"
        case _                                        => baseTpe
      val init = vd.rhs.map(r => s" = ${emitExpr(r)}").getOrElse("")
      line(s"$prefix$tpe ${vd.name}$init;")

    private def emitMethod(dd: DefDef): Unit =
      val sym = dd.symbol
      if sym.flags.is(Flags.Synthetic) then return

      emitSourceAttribution(sym)
      if sym.flags.is(Flags.Override) then line("@override")

      val retType = emitTypeRef(dd.returnTpt.tpe)
      val params = dd.paramss.flatMap(_.params).collect { case vd: ValDef => vd }
      val paramStr = params.map(p => s"${emitTypeRef(p.tpt.tpe)} ${dartSafeName(p.name)}").mkString(", ")
      val tparams = typeParamSig(dd)

      // Scala paren-less `def foo: Int = …` → Dart getter `int get foo`.
      // Distinguishes from `def foo(): Int` (empty parens → Dart method).
      // Users' paren-less call sites `x.foo` work cleanly against a getter.
      val isGetter = dd.paramss.isEmpty

      dd.rhs match
        case Some(body) =>
          val header =
            if isGetter then s"$retType get ${sym.name} {"
            else s"$retType ${sym.name}$tparams($paramStr) {"
          line(header)
          indent += 1
          emitBodyAsStatements(body, returnLast = retType != "void")
          indent -= 1
          line("}")
          blank()
        case None =>
          if isGetter then line(s"$retType get ${sym.name};")
          else line(s"$retType ${sym.name}$tparams($paramStr);")

    /** Extract `[T <: Foo, U]`-style type parameters from a `DefDef`
     *  (including the primary constructor, which is how class-level type
     *  params surface in TASTy). Emits Dart `<T extends Foo, U>` form so
     *  bounds are preserved. Returns `""` when none.
     *
     *  Unbounded `T`s drop the `extends`. Scala's default upper bound of
     *  `Any` also drops the `extends` (Dart `Object?` is the equivalent
     *  and Dart's type inference handles it without the annotation).
     */
    private def typeParamSig(dd: DefDef): String =
      val tps: List[TypeDef] = dd.paramss.collect {
        case tpc: TypeParamClause => tpc.params
      }.flatten
      if tps.isEmpty then ""
      else
        val parts = tps.map { tp =>
          tp.rhs match
            case tb: TypeBoundsTree =>
              val upper = tb.hi.tpe
              val upperSym = upper.typeSymbol.fullName
              if upperSym == "scala.Any" || upperSym == "java.lang.Object" then tp.name
              else s"${tp.name} extends ${emitTypeRef(upper)}"
            case _ => tp.name
        }
        parts.mkString("<", ", ", ">")

    // ── Top-level defs & vals ────────────────────────────────────────────

    /** Emit a Scala 3 extension method as a Dart `extension` block with
     *  one member.
     *
     *  Scala shape:  `extension (n: Int) def squared: Int = n * n`
     *  TASTy shape:  DefDef `squared` with `Flags.ExtensionMethod`, whose first
     *                term-param-clause has a single ValDef (the receiver),
     *                and whose body may reference the receiver by name.
     *  Dart shape:   `extension SartIntSquared on int { int get squared {
     *                  final int n = this; return n * n; } }`
     *
     *  We inject `final T n = this;` as the first statement of the body so
     *  references to the receiver in the original body transfer unchanged.
     *  A future pass can rewrite refs to `this` directly and drop the alias.
     */
    private def emitExtensionMethod(dd: DefDef): Unit =
      val sym = dd.symbol
      val termClauses: List[List[ValDef]] = dd.paramss.collect {
        case tpc: TermParamClause => tpc.params
      }
      if termClauses.isEmpty then
        line(s"/* TODO extension $sym — no term params */")
        return

      val receiver = termClauses.head.headOption match
        case Some(vd: ValDef) => vd
        case _ =>
          line(s"/* TODO extension $sym — unexpected receiver shape */")
          return

      val methodParams = termClauses.drop(1).flatten
      val receiverTpe  = emitTypeRef(receiver.tpt.tpe)
      val retType      = emitTypeRef(dd.returnTpt.tpe)
      val tparams      = typeParamSig(dd)

      val extName = s"Sart${receiver.tpt.tpe.typeSymbol.name}${sym.name.capitalize}"
      line(s"extension $extName$tparams on $receiverTpe {")
      indent += 1

      val methodHeader =
        if methodParams.isEmpty then
          s"$retType get ${sym.name} {"
        else
          val paramStr = methodParams.map(p => s"${emitTypeRef(p.tpt.tpe)} ${p.name}").mkString(", ")
          s"$retType ${sym.name}($paramStr) {"
      line(methodHeader)
      indent += 1
      line(s"final $receiverTpe ${receiver.name} = this;")
      dd.rhs match
        case Some(body) => emitBodyAsStatements(body, returnLast = retType != "void")
        case None       => ()
      indent -= 1
      line("}")

      indent -= 1
      line("}")
      blank()

    private def emitTopLevelDef(dd: DefDef): Unit =
      val sym = dd.symbol
      if sym.flags.is(Flags.Synthetic) then return

      // `@main def foo` → emit as Dart `void main()`.
      val mainFqns = Set("scala.main", "scala.annotation.newMain", "scala.annotation.main")
      val isMainAnnotated = sym.annotations.exists(a => mainFqns.contains(annoFqn(a)))
      if isMainAnnotated then
        dd.rhs match
          case Some(body) =>
            emitSourceAttribution(sym)
            line("void main() {")
            indent += 1
            emitBodyAsStatements(body, returnLast = false)
            indent -= 1
            line("}")
            blank()
          case None => ()
        return

      // Regular top-level `def` (including `inline def`, since Scala 3's
      // TASTy retains the uninlined form when the call site is in the same
      // compilation unit). Emit as a Dart top-level function.
      val retType = emitTypeRef(dd.returnTpt.tpe)
      val params  = dd.paramss.flatMap(_.params).collect { case vd: ValDef => vd }
      val paramStr = params.map(p => s"${emitTypeRef(p.tpt.tpe)} ${dartSafeName(p.name)}").mkString(", ")
      val tparams  = typeParamSig(dd)
      emitSourceAttribution(sym)
      dd.rhs match
        case Some(body) =>
          line(s"$retType ${sym.name}$tparams($paramStr) {")
          indent += 1
          emitBodyAsStatements(body, returnLast = retType != "void")
          indent -= 1
          line("}")
          blank()
        case None =>
          line(s"$retType ${sym.name}$tparams($paramStr);")

    private def emitTopLevelVal(vd: ValDef): Unit =
      val sym = vd.symbol
      if sym.flags.is(Flags.Synthetic) then return
      val typeSym = vd.tpt.tpe.typeSymbol
      // Case-object singleton val: `case object UnitSquare` creates both a
      // module class `UnitSquare$` and a val `UnitSquare` of that type.
      // We emit the case-object as a plain Dart class (`class UnitSquare`)
      // via `emitCaseObject`, which IS the Dart identity — the pointer
      // val has no meaning in Dart and would just dangle.
      if typeSym.flags.is(Flags.Case) && typeSym.flags.is(Flags.Module) then return
      // For a val whose static type is a module class (e.g. the synthesised
      // singleton behind `given intFormatter: Formatter[Int] with { … }`)
      // widen to the first real parent, so the Dart variable references
      // the *abstraction* (`Formatter<int>`) rather than the internal
      // module class name.
      val renderedType = emitTypeRef(declaredTypeFor(vd.tpt.tpe))
      val prefix = if sym.flags.is(Flags.Mutable) then "" else "final "
      val init = vd.rhs.map(r => s" = ${emitExpr(r)}").getOrElse("")
      emitSourceAttribution(sym)
      line(s"$prefix$renderedType ${vd.name}$init;")
      blank()

    /** When `tpe` is a module-class singleton, widen to the first non-trivial
     *  parent (skipping Object/Product/Serializable/DartObject). For other
     *  types, returns `tpe` unchanged.
     */
    private def declaredTypeFor(tpe: TypeRepr): TypeRepr =
      val sym = tpe.typeSymbol
      if !sym.flags.is(Flags.Module) then tpe
      else
        val parentSym = tpe.baseClasses.drop(1).find { bc =>
          !skippedParentFqns(bc.fullName) && !skippedParentSimples(bc.name)
        }
        parentSym.map(tpe.baseType).getOrElse(tpe)

    // ── Body emission ────────────────────────────────────────────────────

    /** Emit a tree as a sequence of Dart statements. When `returnLast` is
     *  true, the final expression is prefixed with `return`.
     */
    private def emitBodyAsStatements(t: Tree, returnLast: Boolean): Unit = t match
      // Temp-val desugar at body position — route through the expression
      // path so the block-inliner collapses the synthetic `val xN$M = …`
      // hoisting into a single call. Without this, method bodies that
      // construct a widget tree with a mix of named+default args emit with
      // an ugly prelude of intermediate vals.
      case block @ Block(stats, _: Term) if stats.nonEmpty && stats.forall { case _: ValDef => true; case _ => false } =>
        emitTerminal(block, returnLast)
      case Block(stats, expr) =>
        stats.foreach(emitStmt)
        emitTerminal(expr, returnLast)
      case tryTree: Try =>
        emitTryStatement(tryTree, returnLast)
      case other: Term =>
        emitTerminal(other, returnLast)
      case other =>
        line(s"/* TODO body ${other.getClass.getSimpleName} */")

    /** Emit `try { … } on E catch (e) { … } finally { … }` as a Dart
     *  statement. Each catch-clause body is itself dispatched back through
     *  `emitBodyAsStatements`, so `return` still lands correctly when this
     *  Try is the tail of a non-Unit method.
     */
    private def emitTryStatement(t: Try, returnLast: Boolean): Unit =
      line("try {")
      indent += 1
      emitBodyAsStatements(t.body, returnLast)
      indent -= 1

      for c <- t.cases do
        val header = c.pattern match
          // `case _: E => …`                 → `on E { … }`
          case Typed(Ident("_"), tpt) =>
            s"} on ${emitTypeRef(tpt.tpe)} {"
          // `case e: E => …`                 → `on E catch (e) { … }`  (or
          // `on E {` when the body doesn't use `e`; keeps Dart's
          // `unused_catch_clause` lint quiet.)
          case Bind(name, Typed(Ident("_"), tpt)) =>
            val t = emitTypeRef(tpt.tpe)
            if bodyUsesIdent(c.rhs, name) then s"} on $t catch ($name) {"
            else s"} on $t {"
          // `case e => …` (type inferred)   → `catch (e) { … }`
          case Bind(name, Ident("_")) =>
            if bodyUsesIdent(c.rhs, name) then s"} catch ($name) {"
            else s"} catch (_) {"
          case Ident("_") =>
            s"} catch (_) {"
          case _ =>
            s"} catch (_) { /* TODO complex catch pattern */"
        line(header)
        indent += 1
        emitBodyAsStatements(c.rhs, returnLast)
        indent -= 1

      t.finalizer match
        case Some(body) =>
          line("} finally {")
          indent += 1
          emitBodyAsStatements(body, returnLast = false)
          indent -= 1
          line("}")
        case None =>
          line("}")

    private def emitTerminal(t: Tree, returnLast: Boolean): Unit = t match
      case Literal(c) if c.value == () =>
        () // nothing to emit; a Unit-valued body trails off
      case term: Term =>
        if returnLast then line(s"return ${emitExpr(term)};")
        else line(s"${emitExpr(term)};")
      case _ =>
        line(s"/* TODO terminal ${t.getClass.getSimpleName} */")

    private def emitStmt(t: Tree): Unit = t match
      case vd: ValDef =>
        val prefix = if vd.symbol.flags.is(Flags.Mutable) then "" else "final "
        val init = vd.rhs.map(r => s" = ${emitExpr(r)}").getOrElse("")
        line(s"$prefix${emitTypeRef(vd.tpt.tpe)} ${vd.name}$init;")
      case Assign(lhs, rhs) =>
        line(s"${emitExpr(lhs)} = ${emitExpr(rhs)};")
      case tryTree: Try =>
        emitTryStatement(tryTree, returnLast = false)
      case term: Term =>
        line(s"${emitExpr(term)};")
      case _: DefDef =>
        // Nested defs (e.g. lambda-lifted) shouldn't appear at statement
        // position in the subset we support.
        line(s"/* TODO nested def */")
      case _ =>
        line(s"/* TODO stmt ${t.getClass.getSimpleName} */")

    // ── Expressions ──────────────────────────────────────────────────────

    private def emitExpr(t: Term): String = t match
      case Literal(c) => emitConstant(c)
      // Hand-ported stdlib singletons — must precede the generic `Ident` /
      // `Select` fallbacks or those would swallow the reference.
      case t if isSartRef(t, "sart.stdlib.None") => "null"
      case Ident(name) => dartSafeName(name)
      case This(_) => "this"

      // Scala's Predef auto-inserts implicit wrappers (`augmentString(s)`,
      // `intWrapper(n)`, etc.) so its stdlib-style methods/operators are
      // reachable. Dart's native `String`/`int`/`double` provide equivalent
      // operators directly, so we strip the wrapper and emit just the
      // underlying argument. This case has to run before the generic
      // `Apply(Select(qual, name), args)` branch would otherwise emit
      // `Predef.augmentString(s)` literally.
      case Apply(fn, List(arg)) if isScalaImplicitWrapper(fn) =>
        emitExpr(arg)
      case Apply(TypeApply(fn, _), List(arg)) if isScalaImplicitWrapper(fn) =>
        emitExpr(arg)

      // s"..." → Dart single-quoted string with $x / ${e} interpolation.
      // The qualifier of `.s(args*)` is a StringContext construction; we
      // accept several tree shapes the compiler may produce.
      case Apply(Select(qual, "s"), args) if stringContextParts(qual).nonEmpty =>
        val parts = stringContextParts(qual)
        val actualArgs = args match
          case List(Typed(Repeated(items, _), _)) => items
          case List(Repeated(items, _))           => items
          case other                              => other
        emitInterpolationParts(parts, actualArgs)

      // List(a, b, ...) → [a, b, ...]  (empty `List()` → `[]`)
      case Apply(TypeApply(Select(Ident("List"), "apply"), _), List(arg)) if isVarargs(arg) =>
        varargsItems(arg).map(emitExpr).mkString("[", ", ", "]")
      case Apply(Select(Ident("List"), "apply"), List(arg)) if isVarargs(arg) =>
        varargsItems(arg).map(emitExpr).mkString("[", ", ", "]")

      // Set(a, b, ...) → {a, b, ...}  (Dart set literal; empty `Set()` →
      // `<dynamic>{}` would be ambiguous with a Map, so we fall through
      // to the generic path when empty.)
      case Apply(TypeApply(Select(Ident("Set"), "apply"), _), List(arg)) if varargsItems(arg).nonEmpty =>
        varargsItems(arg).map(emitExpr).mkString("{", ", ", "}")
      case Apply(Select(Ident("Set"), "apply"), List(arg)) if varargsItems(arg).nonEmpty =>
        varargsItems(arg).map(emitExpr).mkString("{", ", ", "}")

      // Map("a" -> 1, "b" -> 2) → {'a': 1, 'b': 2}  (Dart map literal).
      // Scala compiles `"a" -> 1` to an `ArrowAssoc.->` call, which we
      // unwrap to `key: value` pairs.
      case Apply(TypeApply(Select(Ident("Map"), "apply"), _), List(arg)) if varargsItems(arg).nonEmpty =>
        varargsItems(arg).flatMap(mapEntry).mkString("{", ", ", "}")
      case Apply(Select(Ident("Map"), "apply"), List(arg)) if varargsItems(arg).nonEmpty =>
        varargsItems(arg).flatMap(mapEntry).mkString("{", ", ", "}")

      // `new Foo(args)` → `Foo(args)`. For facade classes (@native) we keep
      // Scala named args as Dart named args (Dart constructor is named-form).
      // For user classes we strip names — the emitted Dart ctor is positional.
      case Apply(Select(New(tpt), _), args) =>
        recordAnnotations(tpt.tpe.typeSymbol)
        val ctorName = dartName(tpt.tpe.typeSymbol)
        val argStr = if hasNative(tpt.tpe.typeSymbol) then emitArgs(args) else emitPositionalArgs(args)
        s"$ctorName($argStr)"
      case Apply(TypeApply(Select(New(tpt), _), _), args) =>
        recordAnnotations(tpt.tpe.typeSymbol)
        val ctorName = dartName(tpt.tpe.typeSymbol)
        val argStr = if hasNative(tpt.tpe.typeSymbol) then emitArgs(args) else emitPositionalArgs(args)
        s"$ctorName($argStr)"

      // `sart.stdlib.Some(x)` → just `x` — Dart promotes the non-null value
      // into the nullable type automatically.
      case Apply(Select(qual, "apply"), args) if isSartRef(qual, "sart.stdlib.Some") =>
        args.headOption.map(emitExpr).getOrElse("null")
      case Apply(TypeApply(Select(qual, "apply"), _), args) if isSartRef(qual, "sart.stdlib.Some") =>
        args.headOption.map(emitExpr).getOrElse("null")

      // `Todo.apply(x, y)` on a case-class companion → `Todo(x, y)`. Scala
      // compiles `Foo(args)` (no `new`) into a call to the companion's
      // synthesised `apply`; Dart has no apply-on-companion concept, so we
      // rewrite it to the positional constructor.
      case Apply(Select(qual, "apply"), args) if isCaseClassCompanion(qual) =>
        val ctorName = caseClassNameFor(qual)
        s"$ctorName(${emitPositionalArgs(args)})"
      case Apply(TypeApply(Select(qual, "apply"), _), args) if isCaseClassCompanion(qual) =>
        val ctorName = caseClassNameFor(qual)
        s"$ctorName(${emitPositionalArgs(args)})"

      // `opt.getOrElse(d)` → `(opt ?? d)` — Dart's null-coalescing operator
      // is the exact native equivalent.
      case Apply(Select(recv, "getOrElse"), List(arg)) if isOptionReceiver(recv) =>
        s"(${emitExpr(recv)} ?? ${emitExpr(arg)})"
      case Apply(TypeApply(Select(recv, "getOrElse"), _), List(arg)) if isOptionReceiver(recv) =>
        s"(${emitExpr(recv)} ?? ${emitExpr(arg)})"

      // Presence checks → Dart null-comparison. Handles both getter-style
      // `Select` and zero-arg `Apply(Select(...), Nil)` tree shapes.
      case Select(recv, "isDefined") if isOptionReceiver(recv) => s"(${emitExpr(recv)} != null)"
      case Select(recv, "isEmpty")   if isOptionReceiver(recv) => s"(${emitExpr(recv)} == null)"
      case Select(recv, "nonEmpty")  if isOptionReceiver(recv) => s"(${emitExpr(recv)} != null)"
      case Apply(Select(recv, "isDefined"), Nil) if isOptionReceiver(recv) => s"(${emitExpr(recv)} != null)"
      case Apply(Select(recv, "isEmpty"),   Nil) if isOptionReceiver(recv) => s"(${emitExpr(recv)} == null)"
      case Apply(Select(recv, "nonEmpty"),  Nil) if isOptionReceiver(recv) => s"(${emitExpr(recv)} != null)"

      // (`sart.stdlib.None` is handled at the top of `emitExpr` — before
      //  the generic `Ident` fallback — so a bare `None` reference lands
      //  as `null`.)

      // Closure: Block(List(DefDef), Closure) — zero-arg `() => expr` or
      // `() => { stmts; expr }`.
      case Block(List(dd: DefDef), _: Closure) =>
        emitClosure(dd)

      // A Block with no statements is just a wrapper around the trailing
      // expression — pass through. Scala 3 compiles `case x => 0` into
      // `Block(Nil, Literal(0))` for tree uniformity, so this unwrap is
      // what makes pattern-match arms land as clean Dart expressions.
      case Block(Nil, expr) =>
        emitExpr(expr)

      // Block with actual statements in expression position. The common
      // shape is a Scala desugar that hoists constructor arguments into
      // temp vals so default-arg / evaluation-order rules are satisfied.
      // We inline each val back into the trailing expression by string
      // substitution post-emission. Refs to vals whose RHS is a default-arg
      // synthesiser (`Foo.$lessinit$greater$default$N`) are marked and then
      // stripped from the emitted arg list.
      case Block(stats, expr: Term) if stats.nonEmpty && stats.forall { case _: ValDef => true; case _ => false } =>
        inlineTempValBlock(stats.collect { case vd: ValDef => vd }, expr)

      // Blocks with non-ValDef statements (e.g. inner defs, assignments) —
      // fall back to an immediately-invoked closure. Valid Dart; less clean
      // than the temp-val inliner but correct.
      case Block(stats, expr) =>
        val sb = new StringBuilder("(() { ")
        stats.foreach { s =>
          sb.append(stmtInline(s))
          sb.append(' ')
        }
        expr match
          case Literal(c) if c.value == () => ()
          case term: Term => sb.append("return ").append(emitExpr(term)).append("; ")
          case _          => ()
        sb.append("})()")
        sb.toString

      // String concatenation: in Scala `"x" + 42` calls `String.+` which
      // silently coerces; in Dart the `+` on String requires a String rhs,
      // so we wrap non-string operands in `.toString()` on the way through.
      // Match both sides to catch `"x" + n` and `n + "x"`.
      case Apply(Select(lhs, "+"), List(rhs)) if isStringType(lhs.tpe) || isStringType(rhs.tpe) =>
        val l = if isStringType(lhs.tpe) then emitExpr(lhs) else s"${emitExpr(lhs)}.toString()"
        val r = if isStringType(rhs.tpe) then emitExpr(rhs) else s"${emitExpr(rhs)}.toString()"
        s"$l + $r"

      // List append `xs :+ x` → Dart spread `[...xs, x]`. Dart lacks a
      // native append operator but the spread literal is idiomatic.
      case Apply(Select(lhs, name), List(rhs)) if isListLikeReceiver(lhs) && (name == ":+" || name == "appended") =>
        s"[...${emitExpr(lhs)}, ${emitExpr(rhs)}]"
      // List prepend `x +: xs` → `[x, ...xs]`.
      case Apply(Select(lhs, name), List(rhs)) if isListLikeReceiver(lhs) && (name == "+:" || name == "prepended") =>
        s"[${emitExpr(rhs)}, ...${emitExpr(lhs)}]"
      case Apply(TypeApply(Select(lhs, name), _), List(rhs)) if isListLikeReceiver(lhs) && (name == ":+" || name == "appended") =>
        s"[...${emitExpr(lhs)}, ${emitExpr(rhs)}]"
      case Apply(TypeApply(Select(lhs, name), _), List(rhs)) if isListLikeReceiver(lhs) && (name == "+:" || name == "prepended") =>
        s"[${emitExpr(rhs)}, ...${emitExpr(lhs)}]"

      // `xs(i)` (index access) → `xs[i]`.
      case Apply(Select(recv, "apply"), List(idx)) if isListLikeReceiver(recv) =>
        s"${emitExpr(recv)}[${emitExpr(idx)}]"

      // `xs.updated(i, x)` → `[...xs.sublist(0, i), x, ...xs.sublist(i+1)]`.
      // Scala List is immutable; we produce a fresh Dart list with the
      // element at index `i` replaced.
      case Apply(Select(recv, "updated"), List(idx, value)) if isListLikeReceiver(recv) =>
        val r = emitExpr(recv); val i = emitExpr(idx); val v = emitExpr(value)
        s"[...$r.sublist(0, $i), $v, ...$r.sublist($i + 1)]"
      case Apply(TypeApply(Select(recv, "updated"), _), List(idx, value)) if isListLikeReceiver(recv) =>
        val r = emitExpr(recv); val i = emitExpr(idx); val v = emitExpr(value)
        s"[...$r.sublist(0, $i), $v, ...$r.sublist($i + 1)]"

      // Binary operator: `a + b`, `a == b`, etc. Parenthesize operands
      // that are themselves binary ops (or `if`/`match`/assignment) so
      // Dart's operator precedence matches Scala's grouping — otherwise
      // `(x + 1) % y` silently emits as `x + 1 % y` and reparses as
      // `x + (1 % y)`.
      case Apply(Select(lhs, op), List(rhs)) if isBinaryOp(op) =>
        val l = emitExpr(lhs); val r = emitExpr(rhs)
        val lp = if needsParensAsReceiver(lhs) then s"($l)" else l
        val rp = if needsParensAsReceiver(rhs) then s"($r)" else r
        s"$lp ${op} $rp"

      // `runApp.apply(arg)` — the `@native` singleton pattern for top-level
      // Dart functions. Emit as a bare call. Second case covers generic
      // apply like `Right.apply[L, R](x)` where TASTy wraps in TypeApply.
      case Apply(Select(idQual, "apply"), args) if isNativeSingleton(idQual) =>
        val fn = dartName(idQual.tpe.termSymbol)
        recordAnnotations(idQual.tpe.termSymbol)
        s"$fn(${emitArgs(args)})"
      case Apply(TypeApply(Select(idQual, "apply"), _), args) if isNativeSingleton(idQual) =>
        val fn = dartName(idQual.tpe.termSymbol)
        recordAnnotations(idQual.tpe.termSymbol)
        s"$fn(${emitArgs(args)})"

      // Curried call flattening. Scala lets methods have multiple value
      // parameter lists (`def fold(z)(f)`), and call sites mirror the
      // shape: `xs.fold(0)(f)`. Dart has no curried calls, so we collapse
      // each nested `Apply(Apply(inner, args1), args2)` to a single call
      // `inner(args1 ++ args2)`. Applies to direct method calls only —
      // cases where `f(x)(y)` really is a function-returning-function get
      // rewritten as wrong code, but the method-call shape covers 99%
      // of real Scala code.
      case Apply(Apply(Select(qual, name), args1), args2) =>
        recordAnnotations(qual.tpe.typeSymbol)
        emitMemberCall(qual, name, args1 ++ args2)
      case Apply(Apply(TypeApply(Select(qual, name), _), args1), args2) =>
        recordAnnotations(qual.tpe.typeSymbol)
        emitMemberCall(qual, name, args1 ++ args2)
      case Apply(Apply(Ident(name), args1), args2) =>
        s"$name(${emitArgs(args1 ++ args2)})"
      case Apply(Apply(TypeApply(Ident(name), _), args1), args2) =>
        s"$name(${emitArgs(args1 ++ args2)})"

      // `fn.apply(args)` on a Scala FunctionN → `fn(args)`. Scala renders
      // lambda invocation through `apply`; Dart calls a function value
      // directly with parentheses.
      case Apply(Select(qual, "apply"), args) if isFunctionType(qual.tpe) =>
        s"${emitExpr(qual)}(${emitArgs(args)})"
      case Apply(TypeApply(Select(qual, "apply"), _), args) if isFunctionType(qual.tpe) =>
        s"${emitExpr(qual)}(${emitArgs(args)})"

      // `throw expr` is lowered by Scala 3 to `Apply(Ident("throw"), args)`.
      // The Dart keyword `throw` is also a prefix-expression operator.
      // Positioned here (before the generic Apply catchall) so the
      // throw-shaped tree doesn't get eaten by the fallback.
      case Apply(id: Ident, List(arg)) if id.name == "throw" =>
        s"throw ${emitExpr(arg)}"
      case Apply(TypeApply(id: Ident, _), List(arg)) if id.name == "throw" =>
        s"throw ${emitExpr(arg)}"

      // Normal call: `obj.method(args)` or `Ident(method)(args)` for local calls.
      case Apply(Select(qual, name), args) =>
        recordAnnotations(qual.tpe.typeSymbol)
        emitMemberCall(qual, name, args)
      // Generic method call: `obj.method[T](args)`. Same as above but with
      // an inner `TypeApply` that Scala types but Dart's type inference
      // handles on its own — so we drop the explicit type arguments.
      case Apply(TypeApply(Select(qual, name), _), args) =>
        recordAnnotations(qual.tpe.typeSymbol)
        emitMemberCall(qual, name, args)
      case Apply(fn, args) =>
        s"${emitExpr(fn)}(${emitArgs(args)})"

      // Scala's unary operators (`!x`, `-x`, `~x`) compile to
      // `Select(x, "unary_!")` etc. Dart spells these as prefix forms, so
      // we can't route them through the generic member-access path.
      case Select(recv, "unary_!") =>
        val r = emitExpr(recv)
        if needsParensAsReceiver(recv) then s"!($r)" else s"!$r"
      case Select(recv, "unary_-") =>
        val r = emitExpr(recv)
        if needsParensAsReceiver(recv) then s"-($r)" else s"-$r"
      case Select(recv, "unary_~") =>
        val r = emitExpr(recv)
        if needsParensAsReceiver(recv) then s"~($r)" else s"~$r"
      case Select(recv, "unary_+") =>
        emitExpr(recv)

      // Field / method ref (no parens): `widget.title`, `Colors.deepPurple`.
      case Select(qual, name) =>
        recordAnnotations(qual.tpe.typeSymbol)
        recordAnnotations(t.tpe.typeSymbol)
        emitMemberAccess(qual, name)

      // Assignment as an expression (Dart allows this). Also handles the
      // case where a method body is a bare `x = y` — `emitBodyAsStatements`
      // routes non-Block terms through `emitExpr` via `emitTerminal`.
      case Assign(lhs, rhs) =>
        s"${emitExpr(lhs)} = ${emitExpr(rhs)}"

      // `if cond then t else e` → Dart ternary. Good enough when the if is
      // at expression position; statement-level if/else would want a block
      // shape, which we'll add when a fixture hits it.
      case If(cond, thenp, elsep) =>
        s"${emitExpr(cond)} ? ${emitExpr(thenp)} : ${emitExpr(elsep)}"

      // (Duplicate-throw case removed: the effective throw rewrite now
      // lives earlier in emitExpr, before the generic Apply catchall.)

      // `scrutinee match { case p => rhs; … }` → Dart 3 switch expression.
      // Emitted on a single line; `dart format` reformats to multi-line.
      // Pattern emission considers both the guard and the body when
      // deciding whether a bound name is "used".
      case Match(scrutinee, cases) =>
        val arms = cases.map { c =>
          val usageScope: Tree = c.guard match
            case Some(g) => Block(List(g), c.rhs)
            case None    => c.rhs
          val pat   = emitPattern(c.pattern, usageScope)
          val guard = c.guard.map(g => s" when ${emitExpr(g)}").getOrElse("")
          val rhs   = emitExpr(c.rhs)
          s"$pat$guard => $rhs"
        }.mkString(", ")
        s"switch (${emitExpr(scrutinee)}) { $arms }"

      case Typed(expr, _) =>
        emitExpr(expr)

      case Inlined(_, _, expansion) =>
        emitExpr(expansion)

      case other =>
        s"/* TODO expr ${other.getClass.getSimpleName} */"

    private def isNativeSingleton(t: Term): Boolean =
      val sym = t.tpe.termSymbol
      sym.exists && hasNative(sym)

    /** True when the term refers to an `@DartTopLevel`-marked facade
     *  object — its method calls emit without the object qualifier
     *  because the members are Dart top-level functions in reality.
     */
    private def isDartTopLevel(t: Term): Boolean =
      val sym = t match
        case id: Ident => id.symbol
        case s: Select => s.symbol
        case _         => Symbol.spliceOwner
      sym.exists && sym.annotations.exists(a => annoFqn(a) == "sart.dart.DartTopLevel")

    /** Names that are **getters** on common Dart types (String, List,
     *  Map, Set, int/double). Scala may compile a bare reference or a
     *  zero-arg call; Dart requires no parens.
     */
    private val dartGetterNames = Set(
      "isEmpty", "isNotEmpty", "length", "hashCode", "runtimeType",
      "first", "last", "single", "reversed", "keys", "values"
    )

    /** Names that are **methods** on common Dart types. Scala syntax
     *  often drops the parens for these; Dart requires them.
     */
    private val dartMethodNamesNeedingParens = Set(
      "toList", "toSet", "toMap", "toString", "toInt", "toDouble",
      "trim", "toUpperCase", "toLowerCase", "clear", "dispose"
    )

    /** Does this term have an Option-like static type? Covers both the
     *  hand-ported `sart.stdlib.Option` and Scala's built-in `scala.Option`.
     */
    private def isOptionReceiver(t: Term): Boolean =
      val sym = t.tpe.typeSymbol
      sym.exists && (sym.fullName == "sart.stdlib.Option" || sym.fullName == "scala.Option")

    /** Match a term that resolves to a specific fully-qualified Scala name,
     *  used for hand-ported stdlib special-cases (`sart.stdlib.Some`,
     *  `sart.stdlib.None`, etc.).
     */
    private def isSartRef(t: Term, fqn: String): Boolean =
      val sym = t match
        case id: Ident  => id.symbol
        case s: Select  => s.symbol
        case _          => Symbol.spliceOwner   // a dummy non-matching symbol
      sym.exists && sym.fullName == fqn

    /** Scala 3 inserts Predef-side implicit wrappers (`augmentString(s)`,
     *  `intWrapper(n)`, etc.) so `StringOps` / `RichInt` methods and
     *  operators are reachable on primitives. Dart's native `String`/`int`
     *  /`double` already provide those operators, so we strip the wrapper.
     *
     *  Matching by **simple name** rather than FQN because these methods
     *  are inherited through several `LowPriorityImplicits` parents and
     *  their FQN varies across Scala versions; the simple names are stable
     *  and unlikely to clash with user code.
     */
    private val scalaImplicitWrapperSimples = Set(
      "augmentString", "unaugmentString",
      "intWrapper", "longWrapper", "floatWrapper", "doubleWrapper",
      "charWrapper", "byteWrapper", "shortWrapper", "booleanWrapper",
      "wrapRefArray", "wrapIntArray", "wrapDoubleArray", "wrapLongArray",
      "wrapFloatArray", "wrapCharArray", "wrapByteArray", "wrapShortArray",
      "wrapBooleanArray", "wrapUnitArray", "genericWrapArray",
      "refArrayOps"
    )

    private def isScalaImplicitWrapper(t: Term): Boolean =
      val sym = t match
        case id: Ident           => id.symbol
        case s: Select           => s.symbol
        case TypeApply(inner, _) => inner match
          case id: Ident => id.symbol
          case s: Select => s.symbol
          case _         => Symbol.spliceOwner
        case _ => Symbol.spliceOwner
      sym.exists
        && scalaImplicitWrapperSimples(sym.name)
        && sym.fullName.startsWith("scala.")

    /** Produce the `"<qual>."` prefix for a member access, or `""` when the
     *  qualifier is `this` (Dart makes `this.` optional everywhere except a
     *  constructor initializer list, which we never emit via this path).
     *
     *  A more cautious version would preserve `this.` when a local variable
     *  in scope shadows the field; for the current subset we have no
     *  shadowing, so unconditional elision is safe.
     */
    private def selectPrefix(qual: Term): String = qual match
      case This(_) => ""
      case _       =>
        val s = emitExpr(qual)
        if needsParensAsReceiver(qual) then s"($s)." else s"$s."

    /** Trees whose emitted form binds looser than `.` in Dart — if they're
     *  used as the receiver of a `Select`/method call, we have to wrap them
     *  in parens so `(r * c).toString()` doesn't render as
     *  `r * c.toString()`.
     */
    private def needsParensAsReceiver(t: Term): Boolean = t match
      case Apply(Select(_, op), List(_)) if isBinaryOp(op) => true
      case If(_, _, _)                                     => true
      case Match(_, _)                                     => true
      case Assign(_, _)                                    => true
      case _                                               => false

    /** No-argument member access (`Select(qual, name)`). Consults the
     *  `StdlibRewrite` table for getter-style mappings (e.g. `xs.size` →
     *  `xs.length`, `xs.headOption` → `xs.isEmpty ? null : xs.first`),
     *  falling back to a direct `qual.name` emission.
     */
    private def emitMemberAccess(qual: Term, name: String): String =
      // @DartTopLevel facade field / constant → drop the qualifier so
      // `math.pi` emits as `pi`.
      if isDartTopLevel(qual) then
        recordAnnotations(qual.tpe.termSymbol)
        return name

      // Conversely, a Scala getter-style `x.toList` on an Iterable really
      // calls Dart's `toList()` method — add parens.
      if dartMethodNamesNeedingParens(name) then
        return s"${selectPrefix(qual)}$name()"

      stdlibRewrite(qual, name, isGetter = true) match
        case Some(rendered) => rendered
        case None           => s"${selectPrefix(qual)}$name"

    /** Single place to render `qual.name(args…)` so Scala → Dart method
     *  name mappings land consistently regardless of which emitExpr entry
     *  point found the call. Consults the `StdlibRewrite` table for
     *  receiver-aware renames / polyfills.
     */
    private def emitMemberCall(qual: Term, name: String, args: List[Term]): String =
      // @DartTopLevel facade method → emit as a top-level Dart call
      // (no qualifier). This is how `math.sqrt(x)` lands as `sqrt(x)`.
      if isDartTopLevel(qual) then
        recordAnnotations(qual.tpe.termSymbol)
        return s"$name(${emitArgs(args)})"

      // Scala allows zero-arg method calls to be written without parens,
      // but also compiles `s.isEmpty` as `Apply(Select, Nil)` when
      // `isEmpty` has an empty parameter list. Dart is strict about
      // getter-vs-method, so no-arg calls to Dart *getters* must drop
      // the parens we'd otherwise emit.
      if args.isEmpty && dartGetterNames(name) then
        return emitMemberAccess(qual, name)

      // Future.map/flatMap both map to Dart's `.then` — `.then` already
      // handles both the value-returning and Future-returning shapes via
      // its overloads, so we don't need the Scala distinction in Dart.
      // Drop the implicit ExecutionContext argument Scala inserts.
      val cleanedArgs =
        if isFutureReceiver(qual) then args.filterNot(isExecutionContextArg)
        else args
      // Render each arg the same way `emitArgs` does (NamedArg handling,
      // default-arg filtering) so rewrite templates see the same forms
      // whether they reach for `args` (joined) or `argList` (per-arg).
      val argList = cleanedArgs.filterNot(isDefaultArg).map {
        case NamedArg(name, value) => s"$name: ${emitExpr(value)}"
        case other                 => emitExpr(other)
      }
      val argStr = argList.mkString(", ")

      stdlibRewrite(qual, name, isGetter = false, argList, argStr) match
        case Some(rendered) => rendered
        case None           => s"${selectPrefix(qual)}$name($argStr)"

    /** Lookup helper: walks `stdlibRewrites`, returning the first matching
     *  template's rendered output or `None`. Method-call entries receive
     *  both `argList` (one Dart expr per Scala argument) and `args` (the
     *  comma-joined form); getter-call entries get empty values.
     */
    private def stdlibRewrite(
      qual: Term, name: String, isGetter: Boolean,
      argList: List[String] = Nil, argStr: String = ""
    ): Option[String] =
      stdlibRewrites.find { e =>
        e.scalaName == name && e.isGetter == isGetter && e.receiver(qual)
      }.map { e =>
        e.emit(RewriteCtx(
          prefix   = selectPrefix(qual),
          qualExpr = emitExpr(qual),
          args     = argStr,
          argList  = argList
        ))
      }

    /** A single Scala→Dart method-call rewrite. `prefix` is `qExpr.` (or
     *  empty when `qual` is `this`) — preserves the existing call-site
     *  elision behaviour. `qualExpr` is the bare expression for templates
     *  that need to reference it twice (e.g. `(q.isEmpty ? null : q.first)`).
     *  `argList` exposes pre-rendered individual args for templates that
     *  need to reorder or skip them (e.g. `Map.getOrElse(k, default)`).
     */
    private case class RewriteCtx(
      prefix:   String,
      qualExpr: String,
      args:     String,
      argList:  List[String]
    )

    private case class StdlibRewrite(
      receiver:  Term => Boolean,
      scalaName: String,
      isGetter:  Boolean,
      emit:      RewriteCtx => String
    )

    // Convenience constructors keep the table dense and readable.
    private def listGet(name: String, dartName: String) =
      StdlibRewrite(isListLikeReceiver, name, isGetter = true, c => s"${c.prefix}$dartName")

    private def listGetExpr(name: String)(template: String => String) =
      StdlibRewrite(isListLikeReceiver, name, isGetter = true, c => template(c.qualExpr))

    private def listCall(name: String)(template: RewriteCtx => String) =
      StdlibRewrite(isListLikeReceiver, name, isGetter = false, template)

    private def listRename(scalaName: String, dartName: String) =
      listCall(scalaName)(c => s"${c.prefix}$dartName(${c.args})")

    /** Scala→Dart method/getter mappings that depend on the receiver type.
     *  The order is irrelevant (predicates are mutually exclusive across
     *  types and `scalaName`+`isGetter` keys are unique within each type).
     *  Adding a new mapping is a one-line addition here.
     */
    private val stdlibRewrites: Seq[StdlibRewrite] = Seq(
      // ── List / Iterable getters ─────────────────────────────────────
      listGet("size",     "length"),
      listGet("head",     "first"),
      listGet("nonEmpty", "isNotEmpty"),
      // Templates that reference the qualifier multiple times.
      listGetExpr("init")      (q => s"$q.sublist(0, $q.length - 1)"),
      listGetExpr("tail")      (q => s"$q.sublist(1)"),
      listGetExpr("reverse")   (q => s"$q.reversed.toList()"),
      listGetExpr("headOption")(q => s"($q.isEmpty ? null : $q.first)"),
      listGetExpr("lastOption")(q => s"($q.isEmpty ? null : $q.last)"),

      // ── List / Iterable methods ─────────────────────────────────────
      // Materialising chain ops — Scala returns List, Dart returns
      // Iterable, so we force `.toList()` to keep the static type aligned.
      listCall("map")       (c => s"${c.prefix}map(${c.args}).toList()"),
      listCall("filter")    (c => s"${c.prefix}where(${c.args}).toList()"),
      listCall("withFilter")(c => s"${c.prefix}where(${c.args}).toList()"),
      listCall("flatMap")   (c => s"${c.prefix}expand(${c.args}).toList()"),
      // Terminal scalars — no .toList() wrap.
      listCall("foldLeft")  (c => s"${c.prefix}fold(${c.args})"),
      listCall("mkString")  (c => s"${c.prefix}join(${c.args})"),
      // Direct renames where Dart's name differs from Scala's.
      listRename("drop",      "skip"),
      listRename("dropWhile", "skipWhile"),
      listRename("exists",    "any"),
      listRename("forall",    "every"),
      // Same-name passthroughs that exist on Dart's Iterable.
      listRename("take",      "take"),
      listRename("takeWhile", "takeWhile"),
      listRename("contains",  "contains"),
      listRename("indexOf",   "indexOf"),

      // ── Map ────────────────────────────────────────────────────────
      // Getters: `m.size`/`nonEmpty` rename; `keys`/`values` exist in Dart
      // unchanged but are listed explicitly so the table is the single
      // source of truth.
      StdlibRewrite(isMapReceiver, "size",     isGetter = true,  c => s"${c.prefix}length"),
      StdlibRewrite(isMapReceiver, "nonEmpty", isGetter = true,  c => s"${c.prefix}isNotEmpty"),
      StdlibRewrite(isMapReceiver, "keys",     isGetter = true,  c => s"${c.prefix}keys"),
      StdlibRewrite(isMapReceiver, "values",   isGetter = true,  c => s"${c.prefix}values"),
      // Methods.
      StdlibRewrite(isMapReceiver, "contains", isGetter = false,
        c => s"${c.prefix}containsKey(${c.args})"),
      // Scala's `m.get(k): Option[V]` matches Dart's `m[k]: V?` — Sart
      // models Option as a nullable, so the index form is exactly right.
      StdlibRewrite(isMapReceiver, "get", isGetter = false,
        c => s"${c.qualExpr}[${c.args}]"),
      // `m.getOrElse(k, default)` becomes `m[k] ?? default`.
      StdlibRewrite(isMapReceiver, "getOrElse", isGetter = false,
        c => s"(${c.qualExpr}[${c.argList(0)}] ?? ${c.argList(1)})"),

      // ── Option (nullable receiver via the sart_option.dart shim) ───
      // `o.orElse(alt)` → `(o ?? alt)`; both are nullable types.
      StdlibRewrite(isNullableOptionReceiver, "orElse", isGetter = false,
        c => s"(${c.qualExpr} ?? ${c.args})"),
      // `o.contains(x)` → `o == x` — works because Sart maps `Some(x)` to
      // a non-null value and `None` to `null`, so equality is exact.
      StdlibRewrite(isNullableOptionReceiver, "contains", isGetter = false,
        c => s"(${c.qualExpr} == ${c.args})"),
      // `o.exists(p)` → `o != null && p(o)` — guard then test.
      StdlibRewrite(isNullableOptionReceiver, "exists", isGetter = false,
        c => s"(${c.qualExpr} != null && (${c.args})(${c.qualExpr}!))"),
      // `o.forall(p)` → `o == null || p(o)` — vacuously true on absence.
      StdlibRewrite(isNullableOptionReceiver, "forall", isGetter = false,
        c => s"(${c.qualExpr} == null || (${c.args})(${c.qualExpr}!))"),
      // `o.filter(p)` → `o != null && p(o) ? o : null`.
      StdlibRewrite(isNullableOptionReceiver, "filter", isGetter = false,
        c => s"(${c.qualExpr} != null && (${c.args})(${c.qualExpr}!) ? ${c.qualExpr} : null)"),

      // ── Future ─────────────────────────────────────────────────────
      // `.map`/`.flatMap` collapse to Dart's overloaded `.then` — both
      // value- and Future-returning callbacks resolve through it.
      StdlibRewrite(isFutureReceiver, "map",     isGetter = false,
        c => s"${c.prefix}then(${c.args})"),
      StdlibRewrite(isFutureReceiver, "flatMap", isGetter = false,
        c => s"${c.prefix}then(${c.args})")
    )

    /** True when `t` has a Scala `List`-style static type — we rewrite its
     *  chain methods to their Dart Iterable equivalents and append
     *  `.toList()`. Keep the check narrow (FQN starts with
     *  `scala.collection.`) so user-defined types named "List" aren't
     *  accidentally caught.
     */
    private def isListLikeReceiver(t: Term): Boolean =
      val sym = t.tpe.typeSymbol
      sym.exists && sym.fullName.startsWith("scala.collection.") && !isMapReceiver(t)

    /** True when `t`'s static type is `scala.concurrent.Future[...]`. */
    private def isFutureReceiver(t: Term): Boolean =
      val sym = t.tpe.typeSymbol
      sym.exists && sym.fullName == "scala.concurrent.Future"

    /** True when `t`'s static type is a Scala `Map`. Matches the common
     *  immutable / mutable / root variants.
     */
    private def isMapReceiver(t: Term): Boolean =
      val fq = t.tpe.typeSymbol.fullName
      fq == "scala.collection.immutable.Map" ||
      fq == "scala.collection.mutable.Map"   ||
      fq == "scala.collection.Map"

    /** True when `t`'s static type is one of the Option flavours Sart
     *  models as Dart nullables (`scala.Option` or `sart.stdlib.Option`).
     *  Used by the rewrite table to attach Option-specific method
     *  polyfills (orElse, contains, exists, forall, filter) on top of the
     *  ones already covered by the sart_option.dart shim (map/flatMap/
     *  fold/foreach).
     */
    private def isNullableOptionReceiver(t: Term): Boolean =
      val fq = t.tpe.typeSymbol.fullName
      fq == "scala.Option" || fq == "sart.stdlib.Option"

    /** True when `t` references the companion object of a case class
     *  (i.e. `Ref(Todo)` where `class Todo` is a case class). Detects
     *  the `Foo.apply(...)` → `Foo(...)` rewrite site.
     */
    private def isCaseClassCompanion(t: Term): Boolean =
      val sym = t match
        case id: Ident => id.symbol
        case s: Select => s.symbol
        case _         => Symbol.spliceOwner
      sym.exists && sym.flags.is(Flags.Module) && {
        val companion = sym.companionClass
        companion.exists && companion.flags.is(Flags.Case)
      }

    /** Dart class name for a case-class companion reference — strips the
     *  `$` suffix Scala adds to module names if any, honouring `@DartName`.
     */
    private def caseClassNameFor(t: Term): String =
      val sym = t match
        case id: Ident => id.symbol
        case s: Select => s.symbol
        case _         => Symbol.spliceOwner
      val companion = sym.companionClass
      if companion.exists then dartName(companion) else sym.name.stripSuffix("$")

    /** Recognise Scala's implicit `ExecutionContext` argument so we can
     *  drop it when emitting a Dart Future call — Dart has no EC concept.
     */
    private def isExecutionContextArg(t: Term): Boolean =
      val fq = t.tpe.typeSymbol.fullName
      fq == "scala.concurrent.ExecutionContext" || fq == "scala.concurrent.ExecutionContextExecutor"

    private def isBinaryOp(op: String): Boolean =
      Set("+", "-", "*", "/", "%", "==", "!=", "<", ">", "<=", ">=", "&&", "||").contains(op)

    private def isStringType(tpe: TypeRepr): Boolean =
      val fq = tpe.typeSymbol.fullName
      fq == "java.lang.String" || fq == "scala.Predef.String"

    private def isFunctionType(tpe: TypeRepr): Boolean =
      tpe.typeSymbol.fullName.matches("scala\\.Function\\d+")

    /** Extract the items of a Scala varargs argument. Matches both the
     *  `Typed(Repeated(items, _), _)` shape (most common) and a bare
     *  `Repeated(items, _)` that sometimes appears.
     */
    private def varargsItems(t: Term): List[Term] = t match
      case Typed(Repeated(items, _), _) => items
      case Repeated(items, _)           => items
      case _                            => Nil

    /** True when `t` is syntactically a varargs wrapper (Repeated/Typed-
     *  Repeated), even if the enclosed item list is empty. Used as a
     *  guard on literal-collection patterns so `List()` still matches
     *  the List-literal rewrite and produces `[]` rather than a generic
     *  `List.apply()` call.
     */
    private def isVarargs(t: Term): Boolean = t match
      case Typed(Repeated(_, _), _) => true
      case Repeated(_, _)           => true
      case _                        => false

    /** Extract a `"k" -> v` Scala entry as a `"k: v"` Dart map-literal
     *  fragment. Returns `None` for shapes we don't recognise so the
     *  caller can substitute a TODO / omit.
     */
    private def mapEntry(t: Term): Option[String] = t match
      // Predef.ArrowAssoc(k).->(v)
      case Apply(Select(Apply(_, List(key)), "->"), List(value)) =>
        Some(s"${emitExpr(key)}: ${emitExpr(value)}")
      case Apply(TypeApply(Select(Apply(_, List(key)), "->"), _), List(value)) =>
        Some(s"${emitExpr(key)}: ${emitExpr(value)}")
      case Apply(Select(Apply(TypeApply(_, _), List(key)), "->"), List(value)) =>
        Some(s"${emitExpr(key)}: ${emitExpr(value)}")
      case _ =>
        None

    /** Drop references to Scala's synthesised default-argument methods
     *  (e.g. `Text.$lessinit$greater$default$2`). Dart named args with
     *  defaults simply go unmentioned at the call site.
     */
    private def isDefaultArg(t: Term): Boolean = t match
      case s: Select if s.name.contains("$default$") => true
      case Ident(n) if n.contains("$default$") => true
      case Apply(inner, _) => isDefaultArg(inner)
      case TypeApply(inner, _) => isDefaultArg(inner)
      case NamedArg(_, inner) => isDefaultArg(inner)
      case _ => false

    private def emitArgs(args: List[Term]): String =
      args.filterNot(isDefaultArg).map {
        case NamedArg(name, value) => s"$name: ${emitExpr(value)}"
        case other => emitExpr(other)
      }.mkString(", ")

    /** Variant of `emitArgs` that drops any `NamedArg` wrapper, emitting
     *  every argument positionally. Used when the target has a positional
     *  Dart constructor (user classes) but the Scala source passed values
     *  using named-argument syntax.
     */
    private def emitPositionalArgs(args: List[Term]): String =
      args.filterNot(isDefaultArg).map {
        case NamedArg(_, value) => emitExpr(value)
        case other              => emitExpr(other)
      }.mkString(", ")

    private def emitConstant(c: Constant): String = c.value match
      case s: String  => "'" + escapeDartString(s) + "'"
      case b: Boolean => b.toString
      case n: Int     => n.toString
      case n: Long    => n.toString
      case n: Double  => n.toString
      case n: Float   => n.toString
      case ()         => "null"
      case null       => "null"
      case other      => s"/* TODO const $other */"

    private def escapeDartString(s: String): String =
      s.flatMap {
        case '\\' => "\\\\"
        case '\'' => "\\'"
        case '\n' => "\\n"
        case '\r' => "\\r"
        case '\t' => "\\t"
        case '$'  => "\\$"
        case c    => c.toString
      }

    /** Translate a Scala match-pattern tree to a Dart 3 pattern arm.
     *  Drops the binding name when the case body doesn't reference it,
     *  so Dart's unused-variable lint stays quiet.
     */
    private def emitPattern(p: Tree, body: Tree): String = p match
      case Literal(c)                        => emitConstant(c)
      case Ident("_")                        => "_"
      // Scala 3 emits `Wildcard()` for `_` inside Unapply sub-patterns
      // (distinct from `Ident("_")` in the outer pattern form).
      case w: Wildcard                       => "_"
      case Bind(name, Wildcard())            =>
        if bodyUsesIdent(body, name) then s"var $name" else "_"
      case Bind(name, Ident("_")) =>
        if bodyUsesIdent(body, name) then s"var $name" else "_"
      case Typed(Ident("_"), tpt)            => s"${emitTypeRef(tpt.tpe)} _"
      case Bind(name, Typed(Ident("_"), tpt)) =>
        val t = emitTypeRef(tpt.tpe)
        if bodyUsesIdent(body, name) then s"$t $name" else s"$t _"

      // Constructor patterns — `case Foo(a, b)` / `case Success(v)`.
      // Dart 3 object patterns spell this `Foo(field: subpattern, …)` by
      // field name, not by position. So we look up the case class's
      // caseFields (which are in declaration order) and pair them with
      // the Scala pattern subtrees.
      case u: Unapply =>
        emitUnapplyPattern(u, body, explicitType = None)
      // A `Typed(Unapply(…), tpt)` OR Scala 3's `TypedOrTest(Unapply(…),
      // tpt)` — both come up when pattern-matching a subtype of a
      // sealed hierarchy (e.g. `case Success(v)` on a `Try[Int]`). Carry
      // the type as the Dart pattern prefix.
      case Typed(u: Unapply, tpt) =>
        emitUnapplyPattern(u, body, explicitType = Some(tpt.tpe))
      case TypedOrTest(u: Unapply, tpt) =>
        emitUnapplyPattern(u, body, explicitType = Some(tpt.tpe))

      case s: Select => emitExpr(s)
      case Ident(n)  => n
      case _         => s"/* TODO pattern ${p.getClass.getSimpleName} */"

    /** Render a Scala `Unapply(fun, _, subPatterns)` as a Dart object
     *  pattern. Uses the case-class's declared field names to label the
     *  subpatterns, since Dart 3 object patterns are name-based.
     */
    private def emitUnapplyPattern(u: Unapply, body: Tree, explicitType: Option[TypeRepr]): String =
      val ctorSym = ctorSymFor(u.fun)
      val fieldNames: List[String] = ctorSym.flatMap(caseFieldNames).getOrElse(Nil)
      val typeName =
        explicitType.map(emitTypeRef)
          .orElse(ctorSym.map(dartName))
          .getOrElse("_")
      val argStrs: List[String] = u.patterns.zipWithIndex.map { case (subPat, idx) =>
        val field = fieldNames.lift(idx).getOrElse("")
        val rendered = emitPattern(subPat, body)
        if field.isEmpty then rendered else s"$field: $rendered"
      }
      s"$typeName(${argStrs.mkString(", ")})"

    /** Extract the case class's companion-class symbol from an Unapply's
     *  `fun`, whatever wrapper shape it arrived in.
     */
    private def ctorSymFor(fun: Term): Option[Symbol] =
      val sym = fun match
        case TypeApply(Select(id: Ident, "unapply"), _) => id.symbol
        case Select(id: Ident, "unapply")               => id.symbol
        case TypeApply(Select(sel: Select, "unapply"), _) => sel.symbol
        case Select(sel: Select, "unapply")             => sel.symbol
        case _ => Symbol.spliceOwner
      val companion = if sym.exists then sym.companionClass else Symbol.spliceOwner
      if companion.exists then Some(companion) else None

    /** Primary-ctor parameter names in declaration order — the Scala case
     *  class's `unapply` decomposes by position, and these names are how
     *  we surface each position to Dart's named-field pattern syntax.
     */
    private def caseFieldNames(classSym: Symbol): Option[List[String]] =
      val ctor = classSym.primaryConstructor
      if !ctor.exists then return None
      ctor.tree match
        case dd: DefDef =>
          Some(dd.paramss.flatMap(_.params).collect { case vd: ValDef => vd.name })
        case _ => None

    /** Scan `tree` for any `Ident(name)` reference. Used to decide whether
     *  a pattern's Bind needs to carry its name over or can become `_`.
     */
    private def bodyUsesIdent(tree: Tree, name: String): Boolean =
      var found = false
      object Finder extends TreeTraverser:
        override def traverseTree(t: Tree)(owner: Symbol): Unit =
          if !found then t match
            case Ident(n) if n == name => found = true
            case _ => super.traverseTree(t)(owner)
      Finder.traverseTree(tree)(Symbol.spliceOwner)
      found

    /** Strip `Inlined(...)` wrappers the compiler sometimes adds. */
    private def unwrap(t: Term): Term = t match
      case Inlined(_, _, e) => unwrap(e)
      case _ => t

    private def isStringContextRef(t: Term): Boolean = unwrap(t) match
      case Ident("StringContext") => true
      case Select(_, "StringContext") => true
      case _ => false

    /** Attempt to recognise a `StringContext(parts...)` construction at any
     *  of the shapes the compiler may produce and return the constant string
     *  parts. Empty list means "not a StringContext construction."
     */
    private def stringContextParts(t: Term): List[String] =
      unwrap(t) match
        case Apply(Select(ref, "apply"), argList) if isStringContextRef(ref) =>
          val partsTerms = argList match
            case List(Typed(Repeated(ps, _), _)) => ps
            case List(Repeated(ps, _))           => ps
            case ps                              => ps
          partsTerms.flatMap(p => litValue(p).collect { case s: String => s })
        case Apply(TypeApply(Select(ref, "apply"), _), argList) if isStringContextRef(ref) =>
          val partsTerms = argList match
            case List(Typed(Repeated(ps, _), _)) => ps
            case List(Repeated(ps, _))           => ps
            case ps                              => ps
          partsTerms.flatMap(p => litValue(p).collect { case s: String => s })
        case _ => Nil

    /** Render `'prefix $x middle ${expr} suffix'` given the string parts and
     *  the interpolation argument expressions.
     */
    private def emitInterpolationParts(parts: List[String], args: List[Term]): String =
      val b = new StringBuilder("'")
      val partsIter = parts.iterator
      val argsIter  = args.iterator
      if partsIter.hasNext then b.append(escapeDartString(partsIter.next()))
      while argsIter.hasNext do
        val a = argsIter.next()
        a match
          case Ident(n) => b.append("$").append(n)
          case Select(This(_), n) => b.append("$").append(n)
          case other => b.append("${").append(emitExpr(other)).append('}')
        if partsIter.hasNext then b.append(escapeDartString(partsIter.next()))
      b.append('\'')
      b.toString

    /** Emit the body of a lifted anonymous function as a Dart arrow or block
     *  expression. DefDef's `rhs` is the lambda body.
     */
    private def emitClosure(dd: DefDef): String =
      val params = dd.paramss.flatMap(_.params).collect { case vd: ValDef => vd }
      val paramStr = params.map(p => p.name).mkString(", ")
      dd.rhs match
        case Some(body) =>
          body match
            // Temp-val desugar inside a closure body — inline the same way
            // we do for method bodies. Without this, closures that build
            // a widget with named/default args come out as `(ctx, i) {
            // final Foo x$1 = …; ListTile(x$1, …); }` with a dangling
            // statement and default-ref leaks.
            //
            // The guard uses `case _: ValDef` rather than `isInstanceOf`
            // because the quoted-reflect runtime classes for `DefDef` and
            // `ValDef` overlap at the JVM level — an `isInstanceOf` check
            // would wrongly admit blocks whose stats are inner closure
            // DefDefs, strip them, and emit the trailing `Literal(())` as
            // `null` (regression hit by `onTap = () => pushRoute(...)`).
            case Block(stats, expr: Term) if stats.nonEmpty && stats.forall { case _: ValDef => true; case _ => false } =>
              val inlined = inlineTempValBlock(stats.collect { case vd: ValDef => vd }, expr)
              s"($paramStr) => $inlined"
            case Block(stats, expr) =>
              val sb = new StringBuilder(s"($paramStr) { ")
              stats.foreach { s =>
                sb.append(stmtInline(s))
                sb.append(' ')
              }
              expr match
                case Literal(c) if c.value == () => ()
                case term: Term => sb.append(emitExpr(term)).append("; ")
                case _ => ()
              sb.append("}")
              sb.toString
            case Assign(lhs, rhs) =>
              s"($paramStr) { ${emitExpr(lhs)} = ${emitExpr(rhs)}; }"
            case term: Term =>
              s"($paramStr) => ${emitExpr(term)}"
        case None => s"($paramStr) => null"

    /** Inline a `Block(ValDef*, trailingExpr)` desugar — typical output of
     *  Scala's constructor-call lowering for default/reordered named args —
     *  by substituting each val's emitted RHS back into the trailing
     *  expression via text replacement. ValDefs whose RHS is a
     *  `…$default$N` synthesiser get stripped from the resulting call.
     */
    private def inlineTempValBlock(stats: List[ValDef], expr: Term): String =
      val marker = "__SART_DEFAULT_ARG__"
      val subs: Map[String, String] = stats.map { vd =>
        val value = vd.rhs match
          case Some(rhs) if isDefaultArg(rhs) => marker
          case Some(rhs)                      => emitExpr(rhs)
          case None                           => ""
        vd.name -> value
      }.toMap

      var out = emitExpr(expr)
      for (name, value) <- subs do
        out = out.replaceAll(
          s"\\b${java.util.regex.Pattern.quote(name)}\\b",
          java.util.regex.Matcher.quoteReplacement(value)
        )

      // Strip arguments whose value is the default-arg marker. Handle the
      // various surrounding-comma/paren shapes that can appear.
      val id = "[a-zA-Z_$][a-zA-Z_0-9$]*"
      out
        .replaceAll(s"$id: $marker, ",        "")
        .replaceAll(s", $id: $marker",        "")
        .replaceAll(s"$marker, ",             "")
        .replaceAll(s", $marker",             "")
        .replaceAll(s"\\($marker\\)",         "()")
        .replaceAll(s"$id: $marker",          "")
        .replaceAll(marker,                   "null")  // any survivor → `null`

    private def stmtInline(t: Tree): String = t match
      case vd: ValDef =>
        val prefix = if vd.symbol.flags.is(Flags.Mutable) then "" else "final "
        val init = vd.rhs.map(r => s" = ${emitExpr(r)}").getOrElse("")
        s"$prefix${emitTypeRef(vd.tpt.tpe)} ${vd.name}$init;"
      case Assign(lhs, rhs) => s"${emitExpr(lhs)} = ${emitExpr(rhs)};"
      case term: Term       => s"${emitExpr(term)};"
      case _                => s"/* TODO stmt-inline */"

    // ── Type references ──────────────────────────────────────────────────

    private def emitTypeRef(tpe: TypeRepr): String =
      val sym = tpe.typeSymbol
      recordAnnotations(sym)

      // Hand-ported stdlib types with custom Dart representations — these
      // need to bypass the standard `base<T, U>` template because they
      // format differently (e.g. `Option[T]` → `T?`, not `Option<T>`).
      sym.fullName match
        case "sart.stdlib.Option" | "scala.Option" =>
          // Both the hand-ported `sart.stdlib.Option` and Scala's built-in
          // `scala.Option` map to Dart's `T?` nullable. Flag the shim AND
          // its import so `.map` / `.flatMap` / `.fold` resolve in Dart.
          shimsNeeded += optionShim
          imports     += optionShim.fileName
          return tpe match
            case AppliedType(_, List(arg: TypeRepr)) => s"${emitTypeRef(arg)}?"
            case _                                   => "Object?"
        // scala.Function0..FunctionN → Dart `R Function(T1, …, Tn)`.
        case fqn if fqn.matches("scala\\.Function\\d+") =>
          return tpe match
            case AppliedType(_, args) if args.nonEmpty =>
              val Ts = args.init.map { case t: TypeRepr => emitTypeRef(t) }.mkString(", ")
              val R  = emitTypeRef(args.last.asInstanceOf[TypeRepr])
              s"$R Function($Ts)"
            case _ => "Function"
        case _ =>

      val base = sym.fullName match
        case "scala.Int"     => "int"
        case "scala.Long"    => "int"
        case "scala.Double"  => "double"
        case "scala.Float"   => "double"
        case "scala.Boolean" => "bool"
        case "scala.Unit"    => "void"
        case "scala.Any" | "scala.AnyRef" | "java.lang.Object" => "Object"
        case "scala.AnyVal"  => "Object"
        case "scala.Nothing" => "Never"
        case "java.lang.String" | "scala.Predef.String" => "String"
        // Throwables have no direct Dart analog; Dart uses `Object` as
        // the throwable super type for `catch (e)` and `throw e`. Match
        // simple name too because some Scala versions expose `Throwable`
        // without the `java.lang.` prefix we'd normally filter on.
        case fq if fq == "java.lang.Throwable" || fq == "scala.Throwable" ||
                   fq == "java.lang.Exception" || fq == "java.lang.RuntimeException" ||
                   sym.name == "Throwable" || sym.name == "Exception" => "Object"
        case _ => dartName(sym)

      // Render type arguments for `State[MyHomePage]` etc.
      tpe match
        case AppliedType(_, args) if args.nonEmpty =>
          val argStr = args.map {
            case t: TypeRepr => emitTypeRef(t)
          }.mkString("<", ", ", ">")
          base + argStr
        case _ =>
          base
