package sart.facadegen

/** Turn a parsed Dart library into Scala facade source. Output contains:
 *  - one `@native @DartImport(…) class …` per Dart class
 *  - top-level `@native` `def`s per Dart free function (if any)
 *  - scalacOptions-compatible `sart.dart.*` imports at the top
 *
 *  Identifiers that collide with Scala keywords get renamed with an
 *  `@DartName(…)` annotation carrying the original.
 */
object FacadeWriter:

  def render(lib: LibraryInfo, dartImport: String): String =
    val sb = new StringBuilder
    sb.append("// Generated by sart-facadegen. Do not edit by hand.\n")
    sb.append(s"// Source: ${lib.path}\n\n")
    sb.append("package ").append(sanitizePackage(lib.libraryName)).append("\n\n")
    sb.append("import sart.dart.*\n\n")

    for cls <- lib.classes do
      renderClass(sb, cls, dartImport)
      sb.append('\n')

    for en <- lib.enums do
      renderEnum(sb, en, dartImport)
      sb.append('\n')

    for fn <- lib.functions do
      renderFunction(sb, fn, dartImport)
      sb.append('\n')

    sb.toString

  // ── Enums ────────────────────────────────────────────────────────────

  /** Dart enums map to a `@native class` + companion object with one
   *  val per case, matching how the Sart compiler recognises an enum-
   *  like facade (the pattern used by `MainAxisAlignment` in
   *  flutter-facades). Using Scala 3's own `enum` keyword here would
   *  also work but requires the emitter's enum-companion path to kick
   *  in, whereas the class+object pattern is already well-tested.
   */
  private def renderEnum(sb: StringBuilder, en: EnumInfo, dartImport: String): Unit =
    sb.append("@native\n")
    sb.append(s"""@DartImport("$dartImport")\n""")
    sb.append("class ").append(safeName(en.name)).append(" extends DartObject\n\n")
    sb.append("@native\n")
    sb.append(s"""@DartImport("$dartImport")\n""")
    sb.append("object ").append(safeName(en.name)).append(":\n")
    for c <- en.constants do
      sb.append(s"  val ${safeName(c)}: ${safeName(en.name)} = native.value\n")

  // ── Classes ──────────────────────────────────────────────────────────

  private def renderClass(sb: StringBuilder, cls: ClassInfo, dartImport: String): Unit =
    sb.append("@native\n")
    sb.append(s"""@DartImport("$dartImport")\n""")
    sb.append("class ").append(safeName(cls.name))
    if cls.typeParams.nonEmpty then
      sb.append(cls.typeParams.mkString("[", ", ", "]"))

    // Constructor: if we can find an instance field list, use that as the
    // primary-ctor params; otherwise emit an empty ctor. Full constructor
    // parsing is a follow-up; for MVP the field list is a reasonable
    // starting point for hand-refinement.
    val instanceFields = cls.fields // keep all; author edits as needed
    if instanceFields.nonEmpty then
      sb.append("(\n")
      sb.append(instanceFields.map(f =>
        s"  val ${safeName(f.name)}: ${scalaType(f.tpe)} = native.value"
      ).mkString(",\n"))
      sb.append("\n)")

    cls.extendsClause.foreach { parent =>
      sb.append(" extends ").append(scalaType(parent))
    }

    val publicMethods = cls.methods.filter(m => !m.name.startsWith("_") && m.name != cls.name)
    val (staticMethods, instanceMethods) = publicMethods.partition(_.isStatic)

    if instanceMethods.isEmpty then
      sb.append("\n")
    else
      sb.append(":\n")
      for m <- instanceMethods do
        sb.append("  ")
        renderMethodDecl(sb, m)
        sb.append(" = native.value\n")

    // Dart static methods belong on the Scala companion object.
    if staticMethods.nonEmpty then
      sb.append('\n')
      sb.append("@native\n")
      sb.append(s"""@DartImport("$dartImport")\n""")
      sb.append("object ").append(safeName(cls.name)).append(":\n")
      for m <- staticMethods do
        sb.append("  ")
        renderMethodDecl(sb, m)
        sb.append(" = native.value\n")

  private def renderMethodDecl(sb: StringBuilder, m: Method): Unit =
    sb.append("def ").append(safeName(m.name))
    if m.params.nonEmpty then
      sb.append("(")
      sb.append(m.params.map(renderParam).mkString(", "))
      sb.append(")")
    sb.append(": ").append(scalaType(m.returnType))

  private def renderParam(p: Param): String =
    val default = if !p.required && !p.named then " = native.value" else ""
    s"${safeName(p.name)}: ${scalaType(p.tpe)}$default"

  // ── Free functions ──────────────────────────────────────────────────

  private def renderFunction(sb: StringBuilder, fn: FunctionInfo, dartImport: String): Unit =
    sb.append("@native\n")
    sb.append(s"""@DartImport("$dartImport")\n""")
    sb.append("def ").append(safeName(fn.name))
    if fn.params.nonEmpty then
      sb.append("(")
      sb.append(fn.params.map(renderParam).mkString(", "))
      sb.append(")")
    sb.append(": ").append(scalaType(fn.returnType))
    sb.append(" = native.value\n")

  // ── Type mapping ─────────────────────────────────────────────────────

  /** Dart → Scala type-name mapping. Primitive names swap; any
   *  `Foo<T1, …, Tn>` rewrites to `Foo[T1, …, Tn]` with `Foo` also
   *  mapped. Nullable `T?` becomes `T` for now (Matt's Option-shim
   *  mapping would be done per-facade by the author).
   */
  private def scalaType(dart: String): String =
    val t = dart.trim
    val stripped = if t.endsWith("?") then t.dropRight(1) else t
    stripped match
      case "int"     => "Int"
      case "double"  => "Double"
      case "num"     => "Double"
      case "bool"    => "Boolean"
      case "String"  => "String"
      case "void"    => "Unit"
      case "dynamic" => "Any"
      case "Object"  => "Any"
      case FunctionT(retTpe, argList) =>
        val args = splitTypeArgs(argList).map(scalaType)
        val R    = scalaType(retTpe.trim)
        if args.isEmpty then s"() => $R"
        else if args.size == 1 then s"${args.head} => $R"
        else args.mkString("(", ", ", s") => $R")
      case GenericT(base, args) =>
        val baseMapped = base match
          case "Future" => "scala.concurrent.Future"
          case other    => scalaType(other)
        val argsMapped = splitTypeArgs(args).map(scalaType).mkString(", ")
        s"$baseMapped[$argsMapped]"
      case other => other

  private val GenericT = """^([A-Za-z_][A-Za-z0-9_.]*)<(.+)>$""".r
  // `<retTpe> Function(<args>)` — Dart function-type syntax.
  private val FunctionT = """^(.+?)\s+Function\s*\((.*)\)$""".r

  /** Split a comma-separated type-args list respecting nested angle-brackets. */
  private def splitTypeArgs(s: String): List[String] =
    val parts = scala.collection.mutable.ListBuffer[String]()
    val sb    = new StringBuilder
    var depth = 0
    for c <- s do c match
      case '<' => depth += 1; sb.append(c)
      case '>' => depth -= 1; sb.append(c)
      case ',' if depth == 0 =>
        parts += sb.toString.trim
        sb.clear()
      case _ => sb.append(c)
    if sb.nonEmpty then parts += sb.toString.trim
    parts.toList

  // ── Naming ───────────────────────────────────────────────────────────

  private val scalaKeywords = Set(
    "class", "object", "trait", "def", "val", "var", "match", "case",
    "type", "package", "import", "given", "using", "then", "end", "new",
    "return", "throw", "try", "catch", "finally", "if", "else", "while",
    "for", "do", "yield", "this", "super", "null", "true", "false", "with",
    "extends", "implicit", "private", "protected", "override", "abstract",
    "final", "sealed", "lazy"
  )

  private def safeName(name: String): String =
    if scalaKeywords.contains(name) then s"`$name`" else name

  private def sanitizePackage(name: String): String =
    val base = name.replace('-', '_').replaceAll("[^a-zA-Z0-9_.]", "")
    if base.isEmpty then "generated" else base
