package sart.facadegen

/** Turn a resolved Dart API dump into Scala facade source (v2).
 *
 *  Conventions match the hand-written `flutter-facades` style:
 *  - `@native @DartImport(…) class X(…) extends Parent` per Dart class,
 *    with the unnamed constructor's parameters as `val` ctor params —
 *    optional params default to `native.value`, required ones don't.
 *  - Named/factory constructors and statics live on a companion object.
 *  - Dart enums render as a `class X` + companion object of `val` cases.
 *  - Types with no facade collapse to the nearest facaded ancestor
 *    (via the dump's `typeAncestors`), bottoming out at `DartObject`.
 */
object FacadeWriter:

  case class GenConfig(
    scalaPackage: String,
    dartImport: String,
    curated: Set[String],                 // referenceable, never emitted
    curatedGeneric: Map[String, Int],     // curated generics, name -> arity
    keepByFile: Map[String, Set[String]], // dart file path -> decl names
    scalaImports: List[String] = Nil,     // extra Scala imports in output
    dartPackages: List[(String, String)] = Nil, // pubspec deps per decl
    flattenInherited: Boolean = false     // subclassable facades: pull in
                                          // inherited API from ancestors
                                          // that have no facade
  )

  def render(dump: ApiDump, config: GenConfig): String =
    val keptClasses: List[ClassInfo] =
      for
        file <- dump.files
        keep  = config.keepByFile.getOrElse(file.path, Set.empty)
        cls  <- file.classes if keep.contains(cls.name)
      yield cls
    val keptEnums: Set[String] =
      (for
        file <- dump.files
        keep  = config.keepByFile.getOrElse(file.path, Set.empty)
        en   <- file.enums if keep.contains(en.name)
      yield en.name).toSet
    // Every facaded name mapped to its type-parameter arity.
    val arity: Map[String, Int] =
      config.curated.map(_ -> 0).toMap ++
        config.curatedGeneric ++
        keptEnums.map(_ -> 0).toMap ++
        keptClasses.map(c => c.name -> c.typeParams.size).toMap
    // Parents must be constructible from an `extends P` clause with no
    // arguments: curated anchors, kept enums, or kept classes whose
    // primary constructor is callable with zero args (no params, or all
    // params optional — generated params default to `native.value`).
    val safeParents: Set[String] =
      config.curated ++ keptEnums ++
        keptClasses.filter(c => c.ctors.find(_.name == "")
            .forall(_.params.forall(p => !p.required || p.hasDefault)))
          .map(_.name)
    // Parents whose primary ctor HAS params (all optional) need explicit
    // `()` in the extends clause — Scala only elides it for parameterless
    // constructors.
    val parenParents: Set[String] =
      keptClasses.filter(c => c.ctors.find(_.name == "").exists(_.params.nonEmpty))
        .map(_.name).toSet
    // Emitted member names per kept class (ctor vals + getters): a subclass
    // whose ctor re-declares one of its facaded parent's members needs the
    // `override` modifier (e.g. Center(key, child) extends Align(key, child)).
    val memberNames: Map[String, Set[String]] =
      keptClasses.map { c =>
        c.name -> (c.ctors.find(_.name == "").map(_.params.map(_.name).toSet).getOrElse(Set.empty)
          ++ c.instanceGetters.map(_.name) ++ c.instanceMethods.map(_.name))
      }.toMap
    val ctx = new Ctx(arity, dump.typeAncestors)
    // Each kept class's chosen Scala parent (same selection rule as
    // renderClass) — lets override-elision walk the transitive chain.
    val chosenParent: Map[String, Option[String]] =
      keptClasses.map { c =>
        c.name -> c.ancestors.find(a => safeParents.contains(a) &&
          (ctx.arityOf(a) == 0 || ctx.arityOf(a) == c.typeParams.size))
      }.toMap
    // Does the parent chain starting at `parent` provide `name`? Kept
    // parents are checked against their real members and recurse upward;
    // a curated parent's members are unknown — assume it provides (the
    // pre-existing behavior for direct curated parents).
    def chainProvides(parent: Option[String], name: String): Boolean = parent match
      case scala.None => false
      case scala.Some(p) =>
        memberNames.get(p) match
          case scala.None => true
          case scala.Some(ms) =>
            ms.contains(name) || chainProvides(chosenParent.getOrElse(p, scala.None), name)

    val sb = new StringBuilder
    sb.append("// Generated by sart-facadegen. Do not edit by hand —\n")
    sb.append("// regenerate via `sbt sartFacadesRegen` (see facadegen.conf).\n")
    sb.append(s"package ${config.scalaPackage}\n\n")
    sb.append("import sart.dart.*\n")
    for imp <- config.scalaImports do sb.append(s"import $imp\n")
    sb.append('\n')

    for
      file <- dump.files
      keep  = config.keepByFile.getOrElse(file.path, Set.empty)
    do
      val kept = file.classes.filter(c => keep.contains(c.name))
      if kept.nonEmpty || file.enums.exists(e => keep.contains(e.name)) then
        sb.append(s"// ─── ${file.path.split('/').last} ").append("─" * 40).append("\n\n")
      for cls <- kept do
        renderClass(sb, cls, config, ctx, safeParents, parenParents, memberNames, chainProvides)
        sb.append('\n')
      for en <- file.enums if keep.contains(en.name) do
        renderEnum(sb, en, config)
        sb.append('\n')

    sb.toString

  // ── Enums ────────────────────────────────────────────────────────────

  private def renderEnum(sb: StringBuilder, en: EnumInfo, config: GenConfig): Unit =
    annotate(sb, config)
    sb.append("class ").append(safeName(en.name)).append(" extends DartObject\n\n")
    annotate(sb, config)
    sb.append("object ").append(safeName(en.name)).append(":\n")
    for c <- en.constants do
      sb.append(s"  val ${safeName(c)}: ${safeName(en.name)} = native.value\n")

  // ── Classes ──────────────────────────────────────────────────────────

  private def renderClass(
    sb: StringBuilder, cls: ClassInfo, config: GenConfig, ctx: Ctx,
    safeParents: Set[String], parenParents: Set[String],
    memberNames: Map[String, Set[String]],
    chainProvides: (Option[String], String) => Boolean
  ): Unit =
    // A Dart `extension Foo on T` with static members has no instances —
    // render only the object of statics. Call sites read exactly like the
    // Dart originals (`FlexThemeData.dark(...)`).
    if cls.extensionStatics then
      annotate(sb, config)
      sb.append("object ").append(safeName(cls.name)).append(":\n")
      for f <- cls.staticFields.filter(f => isPlainName(f.name)).distinctBy(_.name) do
        sb.append(s"  def ${safeName(f.name)}: ${ctx.scalaType(f.tpe, Set.empty)} = native.value\n")
      for m <- cls.staticMethods.filter(m => isPlainName(m.name)).distinctBy(_.name) do
        sb.append("  ")
        renderMethodDecl(sb, m, m.typeParams.toSet, m.typeParams, ctx)
        sb.append(" = native.value\n")
      return

    val tparams = cls.typeParams.toSet
    // A generic parent is kept when its arity matches this class's own
    // type params — rendered as `P[T…]` on the assumption (near-universal
    // in Flutter/pub code: PopupMenuItem<T> extends PopupMenuEntry<T>,
    // WidgetStatePropertyAll<T> implements WidgetStateProperty<T>) that
    // the params pass through in order.
    val parentName = cls.ancestors.find(a => safeParents.contains(a) &&
      (ctx.arityOf(a) == 0 || ctx.arityOf(a) == cls.typeParams.size))
    val parent = parentName
      .map { a =>
        val args   = if ctx.arityOf(a) == 0 then "" else cls.typeParams.mkString("[", ", ", "]")
        val parens = if parenParents.contains(a) then "()" else ""
        a + args + parens
      }
      .getOrElse("DartObject")
    // Members the kept parent already declares — ctor vals re-declared
    // here must carry `override`. One level deep: kept-parent chains in
    // practice bottom out in curated anchors (which declare no vals).
    val parentMembers: Set[String] =
      parentName.flatMap(memberNames.get).getOrElse(Set.empty)

    annotate(sb, config)
    if cls.isAbstract then sb.append("abstract ")
    sb.append("class ").append(safeName(cls.name))
    if cls.typeParams.nonEmpty then
      sb.append(cls.typeParams.mkString("[", ", ", "]"))

    val primary = cls.ctors.find(_.name == "")
    val ctorParamNames = primary.map(_.params.map(_.name).toSet).getOrElse(Set.empty)
    primary match
      case Some(ctor) if ctor.params.nonEmpty =>
        sb.append("(\n")
        sb.append(ctor.params.map { p =>
          val dflt = if p.required && !p.hasDefault then "" else " = native.value"
          val ovr  = if parentMembers.contains(p.name) then "override " else ""
          s"  ${ovr}val ${safeName(p.name)}: ${ctx.scalaType(p.tpe, tparams)}$dflt"
        }.mkString(",\n"))
        sb.append("\n)")
      case _ => ()

    sb.append(" extends ").append(parent)

    // Subclassable facades flatten inherited API from ancestors that
    // have no facade of their own (a Scala subclass couldn't reach
    // `notifyListeners` otherwise). Members from facaded ancestors come
    // through normal Scala inheritance instead.
    val flatGetters =
      if config.flattenInherited then
        cls.inheritedGetters.filter(g => !ctx.isFacaded(g.from) && isPlainName(g.name))
      else Nil
    val flatMethods =
      if config.flattenInherited then
        cls.inheritedMethods.filter(m => !ctx.isFacaded(m.from) && isPlainName(m.name))
      else Nil

    // An overriding member is elided only when the Scala parent chain can
    // actually provide it: a kept parent that declares it, or a curated
    // parent (whose members we can't see — assume it does). With no
    // facaded parent, "overrides" just means the member re-declares an
    // un-facaded interface (ChangeNotifier.addListener over Listenable) —
    // dropping it would lose the API entirely.
    // Universal Object members always resolve through Scala's Any.
    val universalMembers = Set("toString", "hashCode", "noSuchMethod", "runtimeType", "equals")
    def parentProvides(name: String): Boolean =
      universalMembers.contains(name) || chainProvides(parentName, name)
    val getters = (cls.instanceGetters
      .filter(g => (!g.overrides || !parentProvides(g.name))
        && !ctorParamNames.contains(g.name) && isPlainName(g.name))
        ++ flatGetters)
      .distinctBy(_.name)
      .filterNot(g => ctorParamNames.contains(g.name))
    val methods = (cls.instanceMethods
      .filter(m => (!m.overrides || !parentProvides(m.name)) && isPlainName(m.name)) ++ flatMethods)
      .filterNot(m => getters.exists(_.name == m.name))
      .distinctBy(_.name)

    if getters.isEmpty && methods.isEmpty then sb.append("\n")
    else
      sb.append(":\n")
      for g <- getters.distinctBy(_.name) do
        sb.append(s"  def ${safeName(g.name)}: ${ctx.scalaType(g.tpe, tparams)} = native.value\n")
      for m <- methods do
        sb.append("  ")
        renderMethodDecl(sb, m, tparams ++ m.typeParams, m.typeParams, ctx)
        sb.append(" = native.value\n")

    // Companion: named/factory constructors, static methods, static fields.
    val namedCtors = cls.ctors.filter(c => c.name.nonEmpty && isPlainName(c.name))
    val statics    = cls.staticMethods.filter(m => isPlainName(m.name)).distinctBy(_.name)
    val staticVals = cls.staticFields.filter(f => isPlainName(f.name)).distinctBy(_.name)
    if namedCtors.nonEmpty || statics.nonEmpty || staticVals.nonEmpty then
      sb.append('\n')
      annotate(sb, config)
      sb.append("object ").append(safeName(cls.name)).append(":\n")
      // `def`, not `val`: a facade object with thousands of members (Icons
      // has ~7k) would blow the JVM's 64KB <clinit> limit with eager vals.
      for f <- staticVals do
        sb.append(s"  def ${safeName(f.name)}: ${ctx.scalaType(f.tpe, Set.empty)} = native.value\n")
      for c <- namedCtors do
        val selfType =
          if cls.typeParams.isEmpty then safeName(cls.name)
          else safeName(cls.name) + cls.typeParams.mkString("[", ", ", "]")
        sb.append(s"  def ${safeName(c.name)}")
        if cls.typeParams.nonEmpty then sb.append(cls.typeParams.mkString("[", ", ", "]"))
        renderParams(sb, c.params, cls.typeParams.toSet, ctx)
        sb.append(s": $selfType = native.value\n")
      for m <- statics do
        sb.append("  ")
        // Statics referencing the class's type params get those params on the
        // def — but a static's OWN type param of the same name shadows the
        // class's (Dart statics can't see class params), so dedupe by name.
        val referenced = cls.typeParams.filter(tp =>
          (m.returnType +: m.params.map(_.tpe)).exists(t => mentions(t, tp)))
        val declTps = (referenced ++ m.typeParams).distinct
        renderMethodDecl(sb, m, declTps.toSet, declTps, ctx)
        sb.append(" = native.value\n")

  private def renderMethodDecl(
    sb: StringBuilder, m: Method, tparams: Set[String], declTps: List[String], ctx: Ctx
  ): Unit =
    sb.append("def ").append(safeName(m.name))
    if declTps.nonEmpty then sb.append(declTps.mkString("[", ", ", "]"))
    renderParams(sb, m.params, tparams, ctx)
    sb.append(": ").append(ctx.scalaType(m.returnType, tparams))

  // Methods ALWAYS carry parens — a zero-arg Dart method emitted
  // paren-less would round-trip as a Dart getter (and Scala overrides
  // couldn't add the parens back). Getters render separately.
  private def renderParams(sb: StringBuilder, params: List[Param], tparams: Set[String], ctx: Ctx): Unit =
    sb.append("(")
    sb.append(params.map { p =>
      val dflt = if p.required && !p.hasDefault then "" else " = native.value"
      s"${safeName(p.name)}: ${ctx.scalaType(p.tpe, tparams)}$dflt"
    }.mkString(", "))
    sb.append(")")

  private def annotate(sb: StringBuilder, config: GenConfig): Unit =
    sb.append("@native\n")
    sb.append(s"""@DartImport("${config.dartImport}")\n""")
    for (name, version) <- config.dartPackages do
      sb.append(s"""@DartPackage("$name", version = "$version")\n""")

  private def mentions(tpe: String, tparam: String): Boolean =
    tpe.split("[^A-Za-z0-9_]").contains(tparam)

  private def isPlainName(n: String): Boolean =
    n.nonEmpty && !n.contains('$') && !n.startsWith("_")

  // ── Types ────────────────────────────────────────────────────────────

  /** Type-mapping context: knows which names have facades and how to
   *  collapse the ones that don't.
   */
  private class Ctx(arity: Map[String, Int], ancestors: Map[String, List[String]]):

    def isFacaded(name: String): Boolean = arity.contains(name)

    def arityOf(name: String): Int = arity.getOrElse(name, 0)

    /** Facade name with wildcard args if the facade is generic —
     *  `State` → `State[?]`.
     */
    private def wildcarded(name: String): String =
      arity.getOrElse(name, 0) match
        case 0 => name
        case n => name + List.fill(n)("?").mkString("[", ", ", "]")

    /** Collapse a Dart type name onto a facade: itself if facaded, else
     *  the nearest facaded ancestor, else DartObject. Returns the bare
     *  name (caller decides about type arguments).
     */
    def collapse(name: String, tparams: Set[String]): String =
      if tparams.contains(name) then name
      else if arity.contains(name) then name
      else ancestors.getOrElse(name, Nil).find(a => arity.contains(a))
        .getOrElse("DartObject")

    def collapseWildcarded(name: String, tparams: Set[String]): String =
      val c = collapse(name, tparams)
      if tparams.contains(c) || c == "DartObject" then c else wildcarded(c)

    def scalaType(dart: String, tparams: Set[String]): String =
      val t = dart.trim
      val stripped = if t.endsWith("?") then t.dropRight(1).trim else t
      stripped match
        case "int"     => "Int"
        case "double"  => "Double"
        case "num"     => "Double"
        case "bool"    => "Boolean"
        case "String"  => "String"
        case "void"    => "Unit"
        case "dynamic" => "Any"
        case "Object"  => "Any"
        case "Never"   => "Nothing"
        case FunctionT(retTpe, argList) =>
          val args = functionArgs(argList).map(scalaType(_, tparams))
          val r    = scalaType(retTpe.trim, tparams)
          if args.isEmpty then s"() => $r"
          else if args.size == 1 then s"${args.head} => $r"
          else args.mkString("(", ", ", s") => $r")
        case GenericT(base, args) =>
          val mapped = splitTypeArgs(args).map(scalaType(_, tparams))
          base match
            case "Future"             => s"scala.concurrent.Future[${mapped.mkString(", ")}]"
            case "Stream"             => s"sart.stdlib.Stream[${mapped.mkString(", ")}]"
            case "List" | "Iterable"  => s"List[${mapped.mkString(", ")}]"
            case "Set"                => s"Set[${mapped.mkString(", ")}]"
            case "Map"                => s"Map[${mapped.mkString(", ")}]"
            case other =>
              val collapsed = collapse(other, tparams)
              val n = arityOf(collapsed)
              // Keep real args only when the facade itself is generic with
              // matching arity; otherwise drop them (arity 0) or fall back
              // to wildcards (collapsed onto a differently-shaped facade).
              if collapsed == other && n > 0 && n == mapped.size then
                s"$collapsed[${mapped.mkString(", ")}]"
              else if n == 0 then collapsed
              else collapsed + List.fill(n)("?").mkString("[", ", ", "]")
        case "Duration" => "sart.stdlib.Duration"
        case id if id.matches("[A-Za-z_][A-Za-z0-9_]*") => collapseWildcarded(id, tparams)
        case _ => "DartObject" // records, intersection shapes, etc.

    /** Split a Dart function-type argument list, dropping optional/named
     *  bracket wrappers and trailing parameter names.
     */
    private def functionArgs(raw: String): List[String] =
      val cleaned = raw.replaceAll("[{\\[\\]}]", "")
      splitTypeArgs(cleaned).filter(_.nonEmpty).map { arg =>
        // "Widget? child" → "Widget?": drop a trailing lowercase identifier
        // that sits outside any type syntax.
        val tokens = arg.split("\\s+")
        if tokens.length >= 2 && tokens.last.matches("[a-z][A-Za-z0-9_]*")
           && !tokens.init.last.endsWith(",") then tokens.init.mkString(" ")
        else arg
      }

  private val GenericT = """^([A-Za-z_][A-Za-z0-9_.]*)<(.+)>$""".r
  // `<retTpe> Function(<args>)` — Dart function-type syntax.
  private val FunctionT = """^(.+?)\s+Function\s*\((.*)\)\??$""".r

  /** Split a comma-separated type-args list respecting nested brackets. */
  private def splitTypeArgs(s: String): List[String] =
    val parts = scala.collection.mutable.ListBuffer[String]()
    val sb    = new StringBuilder
    var angle = 0
    var paren = 0
    for c <- s do c match
      case '<' => angle += 1; sb.append(c)
      case '>' => angle -= 1; sb.append(c)
      case '(' => paren += 1; sb.append(c)
      case ')' => paren -= 1; sb.append(c)
      case ',' if angle == 0 && paren == 0 =>
        parts += sb.toString.trim
        sb.clear()
      case _ => sb.append(c)
    if sb.nonEmpty then parts += sb.toString.trim
    parts.toList

  // ── Naming ───────────────────────────────────────────────────────────

  private val scalaKeywords = Set(
    "class", "object", "trait", "def", "val", "var", "match", "case",
    "type", "package", "import", "given", "using", "then", "end", "new",
    "return", "throw", "try", "catch", "finally", "if", "else", "while",
    "for", "do", "yield", "this", "super", "null", "true", "false", "with",
    "extends", "implicit", "private", "protected", "override", "abstract",
    "final", "sealed", "lazy"
  )

  private def safeName(name: String): String =
    // Names ending in `_` need backticks: Scala's lexer would fuse a
    // following `:` into the identifier (`class_:`).
    if scalaKeywords.contains(name) || name.endsWith("_") then s"`$name`" else name
