// Generated by Sart — platform-variant switch. Do not edit.
export 'platform_name_stub.dart'
    if (dart.library.io) 'platform_name_io.dart'
    if (dart.library.js_interop) 'platform_name_web.dart';
