// Generated by Sart — do not edit.
// Scala's Try as a sealed Dart hierarchy. Mirrors the facades in
// sart.stdlib.Try / Success / Failure.

sealed class Try<T> {
  const Try();

  Try<R> map<R>(R Function(T) f);
  Try<R> flatMap<R>(Try<R> Function(T) f);
  R fold<R>(R Function(Object) onFailure, R Function(T) onSuccess);
  T getOrElse(T fallback);
  bool get isSuccess;
  bool get isFailure;
  // Sart maps Option<T> to a Dart nullable T?.
  T? get toOption;
}

final class Success<T> extends Try<T> {
  final T value;
  const Success(this.value);

  @override
  Try<R> map<R>(R Function(T) f) => Success<R>(f(value));
  @override
  Try<R> flatMap<R>(Try<R> Function(T) f) => f(value);
  @override
  R fold<R>(R Function(Object) onFailure, R Function(T) onSuccess) =>
      onSuccess(value);
  @override
  T getOrElse(T fallback) => value;
  @override
  bool get isSuccess => true;
  @override
  bool get isFailure => false;
  @override
  T? get toOption => value;
}

final class Failure<T> extends Try<T> {
  final Object error;
  const Failure(this.error);

  @override
  Try<R> map<R>(R Function(T) f) => Failure<R>(error);
  @override
  Try<R> flatMap<R>(Try<R> Function(T) f) => Failure<R>(error);
  @override
  R fold<R>(R Function(Object) onFailure, R Function(T) onSuccess) =>
      onFailure(error);
  @override
  T getOrElse(T fallback) => fallback;
  @override
  bool get isSuccess => false;
  @override
  bool get isFailure => true;
  @override
  T? get toOption => null;
}
