// Generated by Sart — do not edit.
// Right-biased Either as a sealed Dart hierarchy. Mirrors the
// facades in sart.stdlib.Either / Left / Right.

sealed class Either<L, R> {
  const Either();

  Either<L, R2> map<R2>(R2 Function(R) f);
  Either<L, R2> flatMap<R2>(Either<L, R2> Function(R) f);
  X fold<X>(X Function(L) onLeft, X Function(R) onRight);
  bool get isLeft;
  bool get isRight;
  // Right value or `fallback` (right-biased).
  R getOrElse(R fallback);
  // Sart maps Option<R> to a Dart nullable R?.
  R? get toOption;
  // Flip Left/Right: Right(x).swap == Left(x).
  Either<R, L> get swap;
}

final class Left<L, R> extends Either<L, R> {
  final L value;
  const Left(this.value);

  @override
  Either<L, R2> map<R2>(R2 Function(R) f) => Left<L, R2>(value);
  @override
  Either<L, R2> flatMap<R2>(Either<L, R2> Function(R) f) => Left<L, R2>(value);
  @override
  X fold<X>(X Function(L) onLeft, X Function(R) onRight) => onLeft(value);
  @override
  bool get isLeft => true;
  @override
  bool get isRight => false;
  @override
  R getOrElse(R fallback) => fallback;
  @override
  R? get toOption => null;
  @override
  Either<R, L> get swap => Right<R, L>(value);
}

final class Right<L, R> extends Either<L, R> {
  final R value;
  const Right(this.value);

  @override
  Either<L, R2> map<R2>(R2 Function(R) f) => Right<L, R2>(f(value));
  @override
  Either<L, R2> flatMap<R2>(Either<L, R2> Function(R) f) => f(value);
  @override
  X fold<X>(X Function(L) onLeft, X Function(R) onRight) => onRight(value);
  @override
  bool get isLeft => false;
  @override
  bool get isRight => true;
  @override
  R getOrElse(R fallback) => value;
  @override
  R? get toOption => value;
  @override
  Either<R, L> get swap => Left<R, L>(value);
}
