// Generated by Sart — do not edit.
// Right-biased Either as a sealed Dart hierarchy. Mirrors the
// facades in sart.stdlib.Either / Left / Right.

sealed class Either<L, R> {
  const Either();

  Either<L, R2> map<R2>(R2 Function(R) f);
  Either<L, R2> flatMap<R2>(Either<L, R2> Function(R) f);
  X fold<X>(X Function(L) onLeft, X Function(R) onRight);
  bool get isLeft;
  bool get isRight;
}

final class Left<L, R> extends Either<L, R> {
  final L value;
  const Left(this.value);

  @override
  Either<L, R2> map<R2>(R2 Function(R) f) => Left<L, R2>(value);
  @override
  Either<L, R2> flatMap<R2>(Either<L, R2> Function(R) f) => Left<L, R2>(value);
  @override
  X fold<X>(X Function(L) onLeft, X Function(R) onRight) => onLeft(value);
  @override
  bool get isLeft => true;
  @override
  bool get isRight => false;
}

final class Right<L, R> extends Either<L, R> {
  final R value;
  const Right(this.value);

  @override
  Either<L, R2> map<R2>(R2 Function(R) f) => Right<L, R2>(f(value));
  @override
  Either<L, R2> flatMap<R2>(Either<L, R2> Function(R) f) => f(value);
  @override
  X fold<X>(X Function(L) onLeft, X Function(R) onRight) => onRight(value);
  @override
  bool get isLeft => false;
  @override
  bool get isRight => true;
}
