// Generated by Sart — do not edit.
// Extension methods mirroring sart.stdlib.Option's Scala vocabulary
// on Dart nullable types.

extension SartOption<T extends Object> on T? {
  R? map<R extends Object>(R Function(T) f) =>
      this == null ? null : f(this as T);

  R? flatMap<R extends Object>(R? Function(T) f) =>
      this == null ? null : f(this as T);

  R fold<R>(R ifEmpty, R Function(T) ifPresent) =>
      this == null ? ifEmpty : ifPresent(this as T);

  void foreach(void Function(T) f) {
    if (this != null) f(this as T);
  }
}
